### ISSUE TITLE
plotting LOCPOT from vasp calculation

### ISSUE THREAD

**Issue by jyang2009** [pyiron/pyiron_atomistics#1001]
Dear all,

I've recently had a vasp calculation from which I would like to get the electrostatic potential profile (LOCPOT). However, the `job.get_electrostatic_potential()` seems to be failing even if a LOCPOT file is generated by the calculation. I'm just wondering if pyiron offers a way to manually read in the LOCPOT file and plot the electrostatic profile. Please let me know. Thanks a lot. 

Best,
Jing

**Comment by jan-janssen** [comment]
@jyang2009 Can you check if `job.electrostatic_potential` is populated? If it is not you can try to manually read it using: 
```
job.electrostatic_potential.from_file(filename=os.path.join(directory, "LOCPOT"), normalize=False)
```
Does this return an error message for you? (If the output of your job is compressed, you can decompress it using `job.decompress()`.

**Comment by jyang2009** [comment]
Hi Jan,

I tried manually reading it and it returned the message: 
'Vasp' object has no attribute 'electrostatic_potential'

Best,
Jing

**Comment by jan-janssen** [comment]
@jyang2009 Can you upload an example for us to debug it?

**Comment by jyang2009** [comment]
Hi Jan, 

Is there no way of directly reading in a LOCPOT file? If you need a LOCPOT file to test, here is an example. [LOCPOT](https://datashare.mpcdf.mpg.de/s/4WMzf1ZLqrHTk0O)

Best,
Jing

**Comment by jyang2009** [comment]
Dear all,

I've figured out a workaround for this issue. The problem lies in that `job.get_electrostatic_potential()` would skip reading the LOCPOT file when the job status is not `finished`. So one can use:

`job.status.finished = True`
`job.collect_output()`
`job.get_electrostatic_potential()`

to force pyiron to read the LOCPOT file. 

Best,
Jing

**Comment by pmrv** [comment]
I'll reopen, since it appears that the workaround could be included in pyiron easily.

**Comment by jyang2009** [comment]
Dear all,

I figured out another way to manually read in vasp volumetric data in case pyiron does not automatically collect the output file from an uncoverged calculation. I write it here:

`import pyiron_atomistics`
`pot = pyiron_atomistics.vasp.volumetric_data.VaspVolumetricData()`
`pot.from_file(job.working_directory+'/LOCPOT')`

In this way you get the same volumetric data instance as you get from `job.get_electrostatic_potential()`

Best,
Jing
