### ISSUE TITLE
How does pyiron know the enumeration of the species?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#1004]
Inside this potential "1985--Foiles-S-M--Ni-Cu--LAMMPS--ipr1" I see the following Lammps input lines:

```python
['pair_style eam\n',
 'pair_coeff 1 1 Cu_smf7.eam\n',
 'pair_coeff 2 2 Ni_smf7.eam\n']
```

How does pyiron know or make sure that the element number 1 is Cu and number 2 is Ni? (Same for "1986--Foiles-S-M--Ag-Au-Cu-Ni-Pd-Pt--LAMMPS--ipr1" and many other potentials)

**Comment by pmrv** [comment]
Should be defined in one of the columns in the potential dataframe/csv.  Iirc it's called `Elements`, but I can't check right now.  It's just a list of the chemical elements in the order that lammps assigns the numbers.

**Comment by samwaseda** [comment]
Sorry my question was rather: how does pyiron make sure that the elements defined in the structures are in the same order as the species in the potential file?

**Comment by jan-janssen** [comment]
As @pmrv said in addition to the `config` column, there is an `Elements` or `species` column. The order in this second column defines the order in the potential and pyiron internally matches this one to the order of the structure.

**Comment by jan-janssen** [comment]
https://github.com/eisenforschung/pyiron-resources-mpie/blob/master/lammps/potentials/potentials_lammps.csv - for the `Al_Zn_Mg_MEAM_Jang_HS_2020` potential the `Species` column says `['Al', 'Zn', 'Mg']` this is not an alphabetical ordering but the ordering in the potential. So based on this line pyiron knows: 
```
Al -> 1
Zn -> 2
Mg -> 3
```
As LAMMPS starts counting with `1` while pyiron internally counts starting with `0`. 


`

**Comment by samwaseda** [comment]
Ok I finally understood how it happens. The synchronisation is actually done inside `structure.py` in [this line](https://github.com/pyiron/pyiron_atomistics/blob/7009db50edddad6e9639db60eff4341a848c6a35/pyiron_atomistics/lammps/structure.py#L413). I guess this one is a bit problematic for [the idea of `pr.create.potential`](https://github.com/pyiron/pyiron_atomistics/issues/997). I'll think about how to implement it.
