### ISSUE TITLE
Input / Output murnaghan - possible unit confusion

### ISSUE THREAD

**Issue by fkoermann** [pyiron/pyiron_atomistics#1014]
When we do a murn-fit like 
```# [e0, b0, bP, v0], [e0_error, b0_error, bP_error, v0_error] = murn._fit_leastsq(volume_lst, energy_lst,fittype='vinet')```
we have the units in eV, GPa, and Ang^3. 

However, when using the vinet equation as implemented (as in ase/eos.py)
```def vinet_energy(V, E0, B0, BP, V0):
    "Vinet equation from PRB 70, 224107"
    eta = (V / V0) ** (1 / 3)
    return E0 + 2 * B0 * V0 / (BP - 1) ** 2 * (
        2 - (5 + 3 * BP * (eta - 1) - 3 * eta) * np.exp(-3 * (BP - 1) * (eta - 1) / 2)
    )
```

The `B0` in there is defined as in ase in eV/Ang^3. The result is that one has to add a unit conversion factor as in 
https://pyiron.readthedocs.io/en/latest/source/notebooks/energy_volume_curve.html (eq. [15]).

I think this unit conversion is a bit confusing and one has to be careful in distinguishing units of variables for different modules / functions....

**Comment by jan-janssen** [comment]
@fkoermann - I agree that handling units in python can be confusing. In pyiron we try to provide the units as defined in: 
https://pyiron.readthedocs.io/en/latest/source/faq.html#what-units-does-pyiron-use

But when users use `ase` functions we cannot convert the units for them. Still we are definitely open for suggestions how to do it differently. There is currently some work on refactoring pyiron into smaller packages which can also be used as standalone packages, like https://github.com/pyiron/structuretoolkit so if there is anybody interested to develop a standalone thermodynamics package, which starts with the Murnaghan/ Debye model, then the harmonic and quasi-harmonic approximation using phonopy and finally tools like thermodynamic integration and the melting point calculation, that could definitely be useful within pyiron and beyond.

**Comment by liamhuber** [comment]
> But when users use ase functions we cannot convert the units for them. 

I think the problem is that _inside pyiron_ we require the conversion factor; this is a totally fair criticism.

> The result is that one has to add a unit conversion factor as in
https://pyiron.readthedocs.io/en/latest/source/notebooks/energy_volume_curve.html (eq. [15]).

This reads: `plt.plot(vol_lst, murn.fit_module.vinet_energy(vol_lst, e0, b0/ 160.21766208, bP, v0), label='vinet')`, where `murn` is an instance of our `Murnaghan` job class. The variables `e0`, `b0`, `bP`, and `v0` are also all outputs of `murn._fit_leastsq` (which, if it's being used in our demo notebooks probably should _not_ be a private method, but that's another issue...)

Since it is pyiron that's wrapping the ASE functionality the whole way through, I think the complaint about the unit conversion is totally fair -- we should seriously consider doing this when we wrap the functionality.

I'll go look for the source code line reference now.

**Comment by liamhuber** [comment]
[`fit_module` is set here](https://github.com/pyiron/pyiron_atomistics/blob/cfb9c1866100b813b546c8d8c0409d9be43a4125/pyiron_atomistics/atomistics/master/murnaghan.py#L760)

[It has a `vinet_energy` method](https://github.com/pyiron/pyiron_atomistics/blob/cfb9c1866100b813b546c8d8c0409d9be43a4125/pyiron_atomistics/atomistics/master/murnaghan.py#L608)

Which is [just a function _we_ define](https://github.com/pyiron/pyiron_atomistics/blob/cfb9c1866100b813b546c8d8c0409d9be43a4125/pyiron_atomistics/atomistics/master/murnaghan.py#L58):
```python
def vinet_energy(V, E0, B0, BP, V0):
    "Vinet equation from PRB 70, 224107"
    eta = (V / V0) ** (1 / 3)
    return E0 + 2 * B0 * V0 / (BP - 1) ** 2 * (
        2 - (5 + 3 * BP * (eta - 1) - 3 * eta) * np.exp(-3 * (BP - 1) * (eta - 1) / 2)
    )
```

I.e. it's entirely internal to the pyiron-verse, and requiring users to add a manual unit transformation (if indeed the docs are up-to-date and this is still required!) is weird. IMO either the docs are out of date and need to be updated, or we should be doing this transformation on users' behalf so we aren't forcing them outside pyiron's set of units.

**Comment by liamhuber** [comment]
I tagged this as a good first issue because the code change is super simple, but it requires some MatSci... Are there any MSc or new PhD students at MPIE who want to get their hands dirty?

**Comment by jan-janssen** [comment]
@liamhuber but the energy fit module internally converts the units correctly:
https://github.com/pyiron/pyiron_atomistics/blob/cfb9c1866100b813b546c8d8c0409d9be43a4125/pyiron_atomistics/atomistics/master/murnaghan.py#L588

**Comment by liamhuber** [comment]
I'm just on my mobile so I can't dig around well enough to figure the specifics out, but then is it not something like we return (with the private method and elsewhere) b0 in GPa but expect it (in the energy fit and maybe elsewhere) in eV/A^3?

Ultimately I'm just really uncomfortable that the demo notebook has a manual unit conversion when all the function calls related are pure pyiron...

**Comment by niklassiemer** [comment]
I would say units of private functions may be wrong (should be documented!) and all user facing functions should return proper values. And of course, users should not be forced to call private functions!

**Comment by samwaseda** [comment]
> @liamhuber but the energy fit module internally converts the units correctly:
> 
> https://github.com/pyiron/pyiron_atomistics/blob/cfb9c1866100b813b546c8d8c0409d9be43a4125/pyiron_atomistics/atomistics/master/murnaghan.py#L588

Actually this is exactly the problem. We have a problem with pressures and energy values because the pressures are always given by GPa, while the energy eV. Since GPa != eV/A^3, we always do this conversion of 160.2.... wherever needed. Especially if you take a look at the code, you will realize that the conversions must take place everywhere, which brings me back to my statement during the pyiron meeting that there's a fundamental problem, and while fixing the current problem is easy, it will definitely resurface at some point later...

**Comment by samwaseda** [comment]
While fixing the problem [in this PR](https://github.com/pyiron/pyiron_atomistics/pull/1026), I started to feel that the best thing is to remove the example notebook. I see multiple problems with the units, private functions, variable handling, missing documentation, duplicate functions etc. So in my opinion the only one fair choice is to offer the Murnaghan as a job type, and the auxiliary functionality should not be part of the tutorial.

**Comment by jan-janssen** [comment]
>  I started to feel that the best thing is to remove the example notebook.

We can update it, but we should not remove it. The calculation of energy volume curves is one of the very basic properties we support.

**Comment by samwaseda** [comment]
> > I started to feel that the best thing is to remove the example notebook.
> 
> We can update it, but we should not remove it. The calculation of energy volume curves is one of the very basic properties we support.

ok "remove the notebook" was not the right expression, but would it be ok for you if we simply show only our Murnaghan and not the first part, where the user themselves generates the data points and fit them using the Murnaghan?

**Comment by samwaseda** [comment]
Problem solved with [this PR](https://github.com/pyiron/pyiron/pull/1479)
