### ISSUE TITLE
import pyiron issue

### ISSUE THREAD

**Issue by jhung12** [pyiron/pyiron_atomistics#1035]
Hi
I just install pyiron using conda-forge
I got this 
![Screenshot from 2023-05-08 17-15-16](https://user-images.githubusercontent.com/87548929/236963246-f33bdb33-0677-4c21-9eee-eed9b72f409d.png)

I went to check pyiron_base, the __init__.py is different to the one on the github
It does not import any pyrion_base.utils
![Screenshot from 2023-05-08 17-17-19](https://user-images.githubusercontent.com/87548929/236963384-7a22a981-92a3-4171-9a8b-3eb8a925095e.png)

**Comment by jan-janssen** [comment]
It seems your version of `pyiron_base` or `pyiron_atomistics` is incompatible to `pyiron`. Can you try `conda update pyiron_atomistics` ?

**Comment by jhung12** [comment]
there is no update when i do conda update pyrion_atomistics
which version shold it be?
i got
![Screenshot from 2023-05-09 10-27-50](https://github.com/pyiron/pyiron_atomistics/assets/87548929/15a8c39d-0a80-421a-88d2-6097c6112d6b)

**Comment by jan-janssen** [comment]
Can you run the following?
```
conda install -c conda-forge pyiron_atomistics=0.2.66 pyiron_base=0.5.37
```

**Comment by jhung12** [comment]
thanks for the help!!
it works now
