### ISSUE TITLE
How to get the output magnetic moment of a static vasp calculation?

### ISSUE THREAD

**Issue by jyang2009** [pyiron/pyiron_atomistics#1060]
Dear all,

I would like to check the output magnetic moment of a static vasp calculation in pyiron. I've tried two methods:

1. `job.get_magnetic_moments()`      doesn't return anything
2. ` job['output/structure/spins']`    gives the values as set in MAGMOM, not the output values.

Does anyone know how to do this? Thanks in advance. 

Best,
Jing

**Comment by samwaseda** [comment]
I took a look at it and indeed it doesn't seem to be available. I'll try to take care of it.

**Comment by samwaseda** [comment]
I started looking into it, but I don't really understand where to find the magnetic moments in VASP output files. Maybe @ligerzero-ai ? Or maybe there's something like a pymatgen parser??

**Comment by jyang2009** [comment]
Hi Sam,

Thanks a lot for looking into this. I've figured it out. 
It appears that vasp only print out magnetic moments for individual atoms when LORBIT = 11 is specified. Then both methods work for reading the output. 

Best,
Jing
