### ISSUE TITLE
Output the kinetic energy of each atom from LAMMPS calculations using pyiron

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron_atomistics#1102]
**Output the kinetic energy of each atom from LAMMPS calculations using pyiron**

I am looking into the energy of each atom in a structure from the LAMMPS output. One can obtain this by

compute pe all ke/atom
dump [....] x y z c_ke

**We can use job.input.control.energy_pot_per_atom() to output the potential energy of each atoms. Can we also output the kinetic energy of each atom using pyiron?  Thanks a lot in advance.**

**Comment by pmrv** [comment]
You'll need to activate that before you run the job by doing

```python
job.input.control.energy_pot_per_atom()
```

After running the job its `job['output/generic']` has a corresponding entry.

This is documented [online](https://pyiron-atomistics.readthedocs.io/en/readthedocs/apidoc/pyiron_atomistics.lammps.control.html#pyiron_atomistics.lammps.control.LammpsControl.energy_pot_per_atom), but I'm afraid it's not findable unless you know what you are looking for.

**Comment by lfzhu-phys** [comment]
Great, thanks a lot, I will try it out.

**Comment by lfzhu-phys** [comment]
job.input.control.energy_pot_per_atom() will output the energy per atom, i.e., total energy/number of atoms, but not the energy of each atom, right?

**Comment by lfzhu-phys** [comment]
I just read the source code. I think it will do as I expected. Thanks again:)

**Comment by lfzhu-phys** [comment]
Sorry, I reopen this issue again. Could we also output the local kinetic energy for each atom? job.input.control.energy_pot_per_atom() only gives the potential energy. Thank you very much!

**Comment by pmrv** [comment]
Ah, sorry, I hadn't carefully read the first.  It should be easy.  I will have a look in a bit.

**Comment by lfzhu-phys** [comment]
Thanks a lot, I didn't describe it accurately at the first place:)
