### ISSUE TITLE
Can `open` ever return, like, multiple files?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_atomistics#1144]
I was playing around in `pyiron_atomistics.lammps.output` for #1143, and I found [this snippet](https://github.com/pyiron/pyiron_atomistics/blob/9ab2c32999a12a3bbacdf11548d6a13f04914587/pyiron_atomistics/lammps/output.py#L65):

```python
with open(file_name, "r") as f:
        ...
        dfs = []
        for l in f:
            ...  # Nothing with dfs
        dfs.append(pd.read_csv(...))

    if len(dfs) == 1:
        df = dfs[0]
    else:
        df = pd.concat[dfs]
```

This looks super weird to me -- how is it possible that `dfs` can ever be anything other than length 1? I don't see anything in [pandas.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) about returning multiple values, but even if it did I would still expect `len(dfs) == 1` even if `len(dfs[0]) != 1`... Is this code just redundant?

**Comment by pmrv** [comment]
`pd.concat[dfs]` would immediately throw an error, so I don't think it was ever triggered.  Ok to cut it imo.

**Comment by liamhuber** [comment]
> `pd.concat[dfs]` would immediately throw an error, so I don't think it was ever triggered. Ok to cut it imo.

Super. This was my suspicion, but since this is supposed to be a pure refactor I wanted a second opinion before deleting so many lines!
