### ISSUE TITLE
Why does the executable automatically change?

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron_atomistics#1174]
On Sep 15 I ran jobs and the executable points to
"/cmmc/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/thermodynamics/bin/**run_thermointdfteam_0.01_mpi.sh**"

All jobs are finished.

Now I run the same notebook. The executable points to a different file
"/cmmc/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/thermodynamics/bin/**run_thermointdfteam_0.01.sh**"

Job crashed.

Two questions:
1) What can be the possible reason for such change?

2) How to modify the executable path?

I tried to modify it by 

ham.executable = "/cmmc/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/thermodynamics/bin/**run_thermointdfteam_0.01_mpi.sh**"

But it complains 

"ValueError: Error occurred: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(50)

Any suggestion for this.

Thanks a lot in advance.

**Comment by ligerzero-ai** [comment]
(I think) Your job name is too long... pyiron limits job names to 50 character long, otherwise this happens. I've complained about this in the past https://github.com/pyiron/pyiron_base/pull/960 but there was no resolution. Maybe @jan-janssen can comment?

**Comment by ligerzero-ai** [comment]
also - the mpi vs no mpi I suspect has to do with core allocation. Can you confirm you are using the same amount of cores in both? If the no. of cores > 1 it defaults to mpi versions of the executable, otherwise basic core=1 jobs default to the non-mpi version.

**Comment by pmrv** [comment]
> (I think) Your job name is too long... pyiron limits job names to 50 character long, otherwise this happens. I've complained about this in the past [pyiron/pyiron_base#960](https://github.com/pyiron/pyiron_base/pull/960) but there was no resolution. Maybe @jan-janssen can comment?

It's a sneaky bug, but it actually complains about the executable name being too long, because that is also saved into a (similarly limited) database column.

Otherwise the mpi vs. no mpi should be correct.  Probably you ran the notebook this time without specifying cores and the non mpi executable does something wrong.  In this case we should have to update the resource files for this job.

**Comment by lfzhu-phys** [comment]
Using the automatically executable "run_thermointdfteam_0.01.sh":
The error message is:
```
[unset]: Can't get nodes informationINTERNAL ERROR: invalid error code ffffffff (Ring Index out of range) in MPID_Init:2124
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2124)......: fail failed
```

I guess it's related to MPI, right?

The executable "run_thermointdfteam_0.01.sh" is as following:
```
#!/bin/bash
module load intel/18.0.5 
module load impi/2018.4

if [ $(hostname) == 'cmti001' ];
then
        export I_MPI_HYDRA_BOOTSTRAP=fork;
        exec /u/bzg/Thermodynamics/vasp_Langevin/vasp_5.3.5/vasp
else
        exec /u/bzg/Thermodynamics/vasp_Langevin/vasp_5.3.5/vasp
fi
```

I wonder the problem is "exec"  command for running the executable? When I use "srun /u/bzg/Thermodynamics/vasp_Langevin/vasp_5.3.5/vasp", it works well in the local terminal. 

The previous executalbe "run_thermointdfteam_0.01_mpi.sh" is like following:
```
if [ $(hostname) == 'cmti001' ];
then
        export I_MPI_HYDRA_BOOTSTRAP=fork;
        mpiexec -n $1 /u/lfzhu/Thermodynamics_2018/vasp_Langevin/vasp_5.3.5/vasp-stable-cmmc-08.03.2018
else
        srun -n $1 /u/lfzhu/Thermodynamics_2018/vasp_Langevin/vasp_5.3.5/vasp-stable-cmmc-08.03.2018
fi
```
The difference is "mpiexec" command and  "srun". This executable was working well two weeks ago.

Sorry for the long message. Any clue about this?

**Comment by lfzhu-phys** [comment]
> also - the mpi vs no mpi I suspect has to do with core allocation. Can you confirm you are using the same amount of cores in both? If the no. of cores > 1 it defaults to mpi versions of the executable, otherwise basic core=1 jobs default to the non-mpi version.

Ah, I see the problem I have now. I will check about it.

**Comment by lfzhu-phys** [comment]
Thanks you all very much:) The problem is the location for setting up the number of cores.

If it likes this:

                ham.server.queue = "s_cmfe"
                ham.server.cores = 40
                ham.server.run_mode.manual = True
                ham.run()
                shutil.copy(os.path.join(EqCoords_direct_path, "EqCoords_direct"), ham.working_directory)
                copytree(ExternalFile_path,ham.working_directory,symlinks=False,ignore=None)
                ham.server.run_mode.queue = True
                ham.status.created = True
                ham.run()

It will run on 40 cores. However, if setting up the cores before the final "ham.run()", like this:

                ham.server.run_mode.manual = True
                ham.run()
                shutil.copy(os.path.join(EqCoords_direct_path, "EqCoords_direct"), ham.working_directory)
                copytree(ExternalFile_path,ham.working_directory,symlinks=False,ignore=None)
                ham.server.run_mode.queue = True
                ham.server.queue = "s_cmfe"
                ham.server.cores = 40
                ham.status.created = True
                ham.run()

It goes to a single core and job crashes.
