### ISSUE TITLE
What's the problem with VASP outcar parser?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#1273]
I just tested the [VASP outcar parser](https://github.com/pyiron/pyiron_atomistics/blob/main/pyiron_atomistics/vasp/parser/outcar.py) on my computer, by parsing the [outcar examples](https://github.com/pyiron/pyiron_atomistics/tree/main/tests/static/vasp_test_files/outcar_samples). It takes 3.81 microseconds for all 10 files. I had the feeling that there were a lot of discussions about the inherent problems of the parsers (e.g. reading file each time etc.), but I don't really see what's the problem if it takes only a fraction of microsecond for a file. Can someone remind me what was actually the problem again?

**Comment by niklassiemer** [comment]
That is in agreement with @ligerzero-ai findings. The problem seem to come from multiple (re)opening operations on the HDF file to store all the information. Thus, a parsing to a dict with subsequent writing to HDF will probably fix the issue.
