### ISSUE TITLE
From pyiron.atomistics import Project does not work.

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_atomistics#128]
I am not sure how we want to handle this, however, if I am not mistaken we want to support the nomenclature `from pyiron.atomistics import Project`. Right now, we bind the `atomistics` module of `pyiron_atomistics` to `pyiron.atomistics` to be backwards compatible. Any thoughts about how to resolve this naming conflict? 

https://github.com/pyiron/pyiron/blob/40f43e069bd963bea2c48602220b5b2df0776186/pyiron/__init__.py#L16-L19

**Comment by liamhuber** [comment]
@niklassiemer I guess we've all just gotten used to the current behaviour (`from pyiron_atomistics import Project`/`from pyiron import Project`/`from pyiron_base import Project; import pyiron_atomistics`) and this can be closed?

**Comment by niklassiemer** [comment]
Especially, if we go forward not having different projects all over the place this should be fine to close here 👍
