### ISSUE TITLE
Which one is the recommended kernel to use Pyiron?

### ISSUE THREAD

**Issue by usaikia** [pyiron/pyiron_atomistics#1301]
Which one is the recommended kernel to use Pyiron?
`pr.create.structure.aimsgb.info(axis=[1,0,0], max_sigma=15)` is returning me the following error if I use `pyiron/latest (Python3.10)` kernel. However, if I use `Python 3 (ipykernel)` everything is working fine.  It looks like `aimsgb` package is not installed in `pyiron/latest (Python3.10)`

```
File /cmmc/ptmp/pyironhb/mambaforge/envs/pyiron_latest/lib/python3.10/site-packages/structuretoolkit/build/aimsgb.py:41, in get_grainboundary_info(axis, max_sigma)
     21 def get_grainboundary_info(axis, max_sigma):
     22     """
     23     Provides a list of possible GB structures for a given rotational axis and upto the given maximum sigma value.
     24 
   (...)
     39     GBBuilder.gb_build() function along with the rotational axis and initial bulk structure.
     40     """
---> 41     from aimsgb import GBInformation
     42     return GBInformation(axis=axis, max_sigma=max_sigma)

ModuleNotFoundError: No module named 'aimsgb'
```

**Comment by pmrv** [comment]
@niklassiemer Seems like this is missing in the cluster env.

**Comment by pmrv** [comment]
`pyiron/latest` is the one kept up to date for now, so it should be preferred.

**Comment by usaikia** [comment]
@pmrv Thanks!

**Comment by niklassiemer** [comment]
I installed `aimsgb` in the `pyiron/latest` :)
