### ISSUE TITLE
"import pyiron.atomistics" does not work

### ISSUE THREAD

**Issue by edmen-dev** [pyiron/pyiron_atomistics#131]
**Summary**

A simple cell containing "import pyiron.atomistics" does not work, providing the following error:
ImportError: cannot import name 'gaussian' from 'pyiron_atomistics' (/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/__init__.py)

pyiron_atomistics.__file__:
'/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/__init__.py'

Please can I have some help?

**Comment by sudarsan-surendralal** [comment]
I think the reason is that the pyiron version on the cluster should be updated to include the changes in these lines:

https://github.com/pyiron/pyiron/blob/3a402275e610316bc8978066c1759ee39133738a/pyiron/__init__.py#L18-20


@jan-janssen @muh-hassani

**Comment by max-hassani** [comment]
@sudarsan-surendralal, I have updated pyiron_atomistics, but the error still persists.
```
pyiron_atomistics    0.2.8  pyhd8ed1ab_1  conda-forge/noarch
```

**Comment by sudarsan-surendralal** [comment]
@muh-hassani I think you should update pyiron not pyiron_atomistics

**Comment by max-hassani** [comment]
it solved the issue.

**Comment by edmen-dev** [comment]
Thank you, now it works.
