### ISSUE TITLE
Next release patch or minor?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_atomistics#1327]
As soon as #1326 I am going to be keen to release a new version.

At a quick glance of what this would entail, the only thing I see that might require a minor bump as #1319, but I looked at it and it seems that @pmrv used `@deprecate` to maintain compatibility. But if I can't clearly see that it _does_ need a minor bump, I'd like to get confirmation from the contributors that it _doesn't_ need a minor bump!

* Merge main by @jan-janssen in https://github.com/pyiron/pyiron_atomistics/pull/1320
* Use dot notation by @jan-janssen in https://github.com/pyiron/pyiron_atomistics/pull/1321
* Merge main by @jan-janssen in https://github.com/pyiron/pyiron_atomistics/pull/1323
* [minor] Make height available in plot3d by @samwaseda in https://github.com/pyiron/pyiron_atomistics/pull/1314
* Files file not found by @jan-janssen in https://github.com/pyiron/pyiron_atomistics/pull/1324
* Merge main by @jan-janssen in https://github.com/pyiron/pyiron_atomistics/pull/1325
* Deprecate workdir path getter in favour of job.files by @pmrv in https://github.com/pyiron/pyiron_atomistics/pull/1319
* Add pyxtal wrapper by @pmrv in https://github.com/pyiron/pyiron_atomistics/pull/1093
* Call `collect_output` when VASP job is not compressed at restart by @samwaseda in https://github.com/pyiron/pyiron_atomistics/pull/1315

**Comment by jan-janssen** [comment]
I created a patch release https://github.com/pyiron/pyiron_atomistics/releases/tag/pyiron_atomistics-0.4.15
