### ISSUE TITLE
Changes to lammps output hdf5

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron_atomistics#1340]
The format of lammps h5 output seems to have changed recently. This broke the pyrionFileReader of ovito https://github.com/ovito-org/pyironFileReader.
I implemented a fix in https://github.com/ovito-org/pyironFileReader/pull/1, which reads pbc and species from input/structure instead of
the removed output/structure. This works for both, old and new lammps hdf5 files. However, I am not sure whether it could cause problems due to internal mappings changing species or similar.
So the question is has output/structure been removed because it  doubled data or are there actual differences?

**Comment by jan-janssen** [comment]
Let me have a look - I feel this is a bug in the current pyiron version.
