### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_atomistics#1362]
It's been about a month since the last release and `pyiron_atomistics` is now pinning downstream dependencies to a version of base that is two patches out of date. Would the following contributors please indicate whether their changes are patch or minor version updates? Are there any outstanding objections to a new release?

## What's Changed
* Fix typo by @pmrv in https://github.com/pyiron/pyiron_atomistics/pull/1342
* add keyword to blockdict by @Leimeroth in https://github.com/pyiron/pyiron_atomistics/pull/1349
* Lammps: Fix final structure not being stored by @jan-janssen in https://github.com/pyiron/pyiron_atomistics/pull/1341
* Bump mp-api from 0.39.5 to 0.40.1 by @dependabot in https://github.com/pyiron/pyiron_atomistics/pull/1345
* Bump pylammpsmpi from 0.2.13 to 0.2.14 by @dependabot in https://github.com/pyiron/pyiron_atomistics/pull/1344
* Bump pandas from 2.2.0 to 2.2.1 by @dependabot in https://github.com/pyiron/pyiron_atomistics/pull/1346
* Bump mp-api from 0.41.0 to 0.41.1 by @dependabot in https://github.com/pyiron/pyiron_atomistics/pull/1351
* Import MPRester also in by_id by @pmrv in https://github.com/pyiron/pyiron_atomistics/pull/1352
* Fix typo in pyxtal wrapper by @pmrv in https://github.com/pyiron/pyiron_atomistics/pull/1354
* Bump mp-api from 0.41.1 to 0.41.2 by @dependabot in https://github.com/pyiron/pyiron_atomistics/pull/1358
* Bump pyiron-base from 0.7.10 to 0.7.11 by @dependabot in https://github.com/pyiron/pyiron_atomistics/pull/1357
* Update atomistics to 0.1.24 by @jan-janssen in https://github.com/pyiron/pyiron_atomistics/pull/1359

**Comment by jan-janssen** [comment]
We are currently waiting for https://github.com/pyiron/pyiron_atomistics/pull/1347#issuecomment-1976369077

**Comment by liamhuber** [comment]
@samwaseda you are flagged for review there. @ahmedabdelkawy I see Marvin re-pinged you yesterday, but allow me to throw more fuel on that fire with this "@" as well.

**Comment by ahmedabdelkawy** [comment]
Sorry for the late reply. Currently, I am facing a problem with cloned pyiron repos in my local directory on the cluster. The exported path in the bashrc is not seen in jupter notebooks and also the visual studio instance on the cluster is no longer available I think since the last updates. So I currently can test changes.
