### ISSUE TITLE
changing input parameter in sphinx 

### ISSUE THREAD

**Issue by mostafajoulaian** [pyiron/pyiron_atomistics#140]
**Summary**

as initial parameter in sphinx for field evaporation calculation but I can not do it see below 

**pyiron Version and Platform**

I used latest version of pyiron in cloud 
**Expected Behavior**

I try to do field evaporation calculation and want to set to initial parameter as input (charge and z) same as 

- [ https://github.com/pyiron/pyiron/pull/592] 
    job.input.sphinx.initialGuess.rho.charged={"charge": charge, "z": bottom}

I was expecting to this dictionary put charge and z coordinate in initial input 

**Actual Behavior**

however I think it is work in literal way i.e. it is adding what I wrote in dictionary. as actual error that I got in log file is 
"""Illegal character '{' in ./input.sx:256."""
and when I look at in input file I have 

`charged = {'charge': 1.1242386117856127, 'z': 10.000000000000004};`

I also try below line 
`    job.input.sphinx.initialGuess.rho.set_group("charged",{"charge":charge ,"z":bottom})`
but still I have same error massage

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by pmrv** [comment]
Your hunch is correct, the problem is putting the literal dictionary in the input list.  For a quick fix convert the dictionary to a sphinx `Group` manually, like so
```python
job.input.sphinx.intialGuess.rho.charged = job.input.sphinx.__class__({"charge": charge, "z": bottom})
```
or 
```python
from pyiron_atomistics.atomistics.sphinx.base import Group
job.input.sphinx.intialGuess.rho.charged = Group({"charge": charge, "z": bottom})
```

Meanwhile we should make this work more seamlessly.  When we set dictionaries to `Group` we don't really want wrap them in `Group` recursively (we did this before and it was messy), but maybe we can just wrap the "first level" of mappings and maybe only if the key they are set to doesn't exist yet.  Other ideas?

**Comment by mostafajoulaian** [comment]
Thank you for your answer. 
my problem is temporary solved. I totally agree with your approach. however I think maybe it is nice to update error message as well. """Illegal character"""  does not give you sufficient information about what exactly problem is.
I will close the issue.

**Comment by jan-janssen** [comment]
In addition once the group class is updated please also update the example notebook in https://github.com/pyiron/pyiron_generalized_dipole/blob/master/dipole.ipynb
