### ISSUE TITLE
import job to pyiron

### ISSUE THREAD

**Issue by jyang2009** [pyiron/pyiron_atomistics#1518]
Dear all,

I have been using `pr.import_from_path()` to import jobs into pyiron project. (I mostly use this when I need to copy other people's job files and do my own analysis). But the `import_from_path` function doesn't seem to be existing any more. Could you please let me know what is the substitute method? Thanks a lot.

Best,
Jing

**Comment by jan-janssen** [comment]
Which version of `pyiron_atomistics` are you using? The function is available on the current `main` branch: 
https://github.com/pyiron/pyiron_atomistics/blob/main/pyiron_atomistics/project.py#L418

You can check your version with:
```
conda list pyiron_atomistics
```

**Comment by jyang2009** [comment]
Hi Jan,

Thanks a lot for the reply. I checked it again and the problem was that I was importing project from `pyiron_contrib`. After correcting it it's working now. Thanks again.  

Best,
Jing
