### ISSUE TITLE
LAMMPS job crash immediately "couldn't read file /mpcdf/soft/SLE_15/packages/x86_64/Modules/5.0.1/libexec/modulecmd.tcl"

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron_atomistics#1553]
I just tried to submit a few lammps jobs. They crash immediately with following error. Does anyone else also encounter these problem?

-----------------

> couldn't read file "/mpcdf/soft/SLE_15/packages/x86_64/Modules/5.0.1/libexec/modulecmd.tcl": no such file or directory
> couldn't read file "/mpcdf/soft/SLE_15/packages/x86_64/Modules/5.0.1/libexec/modulecmd.tcl": no such file or directory
> couldn't read file "/mpcdf/soft/SLE_15/packages/x86_64/Modules/5.0.1/libexec/modulecmd.tcl": no such file or directory
> [cmti093:37763] OPAL ERROR: Unreachable in file pmix3x_client.c at line 111
> 
> The application appears to have been direct launched using "srun",
> but OMPI was not built with SLURM's PMI support and therefore cannot
> execute. There are several options for building PMI support under
> SLURM, depending upon the SLURM version you are using:
> 
>   version 16.05 or later: you can use SLURM's PMIx support. This
>   requires that you configure and build SLURM --with-pmix.
> 
>   Versions earlier than 16.05: you must use either SLURM's PMI-1 or
>   PMI-2 support. SLURM builds PMI-1 by default, or you can manually
>   install PMI-2. You must then build Open MPI using --with-pmi pointing
>   to the SLURM PMI library location.

------------------------------------------

**Comment by niklassiemer** [comment]
What version of lammps did you use? Can you usually load the `module`s stated therein?

**Comment by lfzhu-phys** [comment]
@niklassiemer Thanks a lot for looking into it. I just tested one job it works again. Did you do anything on the cluster? If not, the only difference is that yesterday I submitted the job in home, but used the same notebook. I wonder that would affect anything. If you have any clue about it, please let me know. Thanks.

**Comment by niklassiemer** [comment]
No, I did not change anything and I am not aware of any difference in functionality between `/u` and `/cmmc/ptmp`. Nonetheless, thanks a lot for the issue, thats the only way I can know of potential problems even if they might dissappear :) (just to be sure, your new calculations did also run on cmti and not on cmmg?)

**Comment by pmrv** [comment]
I observed this back then as well, but I believe it to be related to an upgrade of the cluster itself.  It went away after restarting shells for me.
