### ISSUE TITLE
Importing unfinished POSCAR from VASP

### ISSUE THREAD

**Issue by gongyilun** [pyiron/pyiron_atomistics#160]
Importing unfinished POSCAR from VASP (after several steps of ion relaxation) results in empty HDF5 file.

**Comment by sudarsan-surendralal** [comment]
Could you please post the error message that you get and/or the POSCAR file?

**Comment by gongyilun** [comment]
there is no error message when 'import_from_path', However, it gives
following error:

>>> pr['job_12']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/Users/ygong/opt/anaconda3/lib/python3.7/site-packages/pyiron_base/project/generic.py",
line 1392, in __getitem__
    return self._get_item_helper(item=item, convert_to_object=True)
  File
"/Users/ygong/opt/anaconda3/lib/python3.7/site-packages/pyiron_base/project/generic.py",
line 1445, in _get_item_helper
    return self.load(item)
  File
"/Users/ygong/opt/anaconda3/lib/python3.7/site-packages/pyiron_base/project/generic.py",
line 765, in load
    job_id=job_id, convert_to_object=convert_to_object
  File
"/Users/ygong/opt/anaconda3/lib/python3.7/site-packages/pyiron/project.py",
line 233, in load_from_jobpath
    job_id=job_id, db_entry=db_entry, convert_to_object=convert_to_object
  File
"/Users/ygong/opt/anaconda3/lib/python3.7/site-packages/pyiron_base/project/generic.py",
line 786, in load_from_jobpath
    convert_to_object=convert_to_object, project=job.project_hdf5.copy()
  File
"/Users/ygong/opt/anaconda3/lib/python3.7/site-packages/pyiron_base/job/core.py",
line 549, in load_object
    return self.to_object(project=job_dir, job_name=self._name)
  File
"/Users/ygong/opt/anaconda3/lib/python3.7/site-packages/pyiron_base/job/core.py",
line 482, in to_object
    + "\" is empty, so it can not be loaded."
ValueError: The HDF5 file of this job with the job_name: "job_12" is empty,
so it can not be loaded.

**Comment by sudarsan-surendralal** [comment]
Could you please try the following and post what happens:

```
job_import = pr.create_job("Vasp", "import_trial")
job_import.from_directory(<path_to_the_vasp_older_that_failed>)
```

**Comment by gongyilun** [comment]
POSCAR & CONTCAR files are attached.
[Archive.zip](https://github.com/pyiron/pyiron_atomistics/files/6338798/Archive.zip)

**Comment by sudarsan-surendralal** [comment]
I see that it is related to parsing from the POTCAR file. Just to confirm, can you rename your POTCAR file to something else and then try importing again?

**Comment by gongyilun** [comment]
The POTCAR file should be fine, since I have another finished run (with
exactly the same POTCAR), and that one can be imported correctly.

**Comment by sudarsan-surendralal** [comment]
> exactly the same POTCAR), and that one can be imported correctly.

Importing the CONTCAR and POSCAR files worked fine for me. So I'll need the entire folder (incl. the POTCAR file) to figure out what is going on. Can you send this via email?

**Comment by sudarsan-surendralal** [comment]
@gongyilun, as I suspected the problem seems to be in the POTCAR file.  Line 4 of your POTCAR file has `VRHFIN =r: 4s4p5s4d` while it should be `VRHFIN =Zr: 4s4p5s4d`. pyiron crashes when it tries to read the chemical element from this line. Could you fix this line, delete the job, and re-import it? Please let me know if this works

**Comment by gongyilun** [comment]
Thanks! It solved the issue! Would it be possible to skip POTCAR reading
once it crashes? That would be much helpful.

**Comment by sudarsan-surendralal** [comment]
> 
> Thanks! It solved the issue! Would it be possible to skip POTCAR reading once it crashes? That would be much helpful.

Yes, I agree with you. I've linked a pull request which does this
