### ISSUE TITLE
What's the difference between SQS and SQSMaster?

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_atomistics#169]
Has anyone used SQS lately and knows the difference between

https://github.com/pyiron/pyiron_atomistics/blob/master/pyiron_atomistics/atomistics/master/sqsmaster.py

and 

https://github.com/pyiron/pyiron_atomistics/blob/master/pyiron_atomistics/atomistics/job/sqs.py

or might even be deigned to write some docs?

**Comment by jan-janssen** [comment]
The sqs job creates a set of sqs structures ranked by randomness for one concentration, the sqsmater does the same for a list of concentrations. It is primarily used for https://github.com/pyiron/phasediagram-workshop-2020/blob/master/Exercise4.ipynb
