### ISSUE TITLE
Updating `Atoms.symbols` does not update structure

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_atomistics#184]
`symbols` is inherited from ASE, but never referenced from our code.  Updating it therefore doesn't have an effect on what pyiron thinks is inside the structure.

**Comment by sudarsan-surendralal** [comment]
@pmrv I remember a while ago Sravan mentioned a similar issue (https://github.com/pyiron/pyiron_atomistics/issues/185). We couldn't solve it then and somehow it slipped under the radar! I had a go at it again and I think I fixed it in the linked PR. Perhaps this fixes @Leimeroth's issue too?
