### ISSUE TITLE
Can I submit an interactive job?

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_atomistics#202]
I have a few thousand structures that I want to put through Lammps.  I could use a `StructureListMaster`, but I thought it's more convenient to use an interactive job and keep changing the structure (since I have the same number of atoms/alloying atoms).  

I used the following snippet, but the job ends up running on the login node.
```python
j = pr.create.job.Lammps('gb_110_n4', delete_existing_job=True)
j.potential = pr.data.potential

j.server.queue = 'cm'
j.server.cores = 4
j.server.run_time = 60 * 60 * 2

j.interactive_open()

from itertools import combinations

n = 4
for I in combinations(np.where(find_sites(gbr)!=-1)[0], n):
    if not ( (gbr.cell[1, 1] * 1/4 < gbr.positions[I, 1]) & (gbr.positions[I, 1] < gbr.cell[1, 1] * 3/4) ).all(): continue
    j.structure = gbr.copy()

    for i in I:
        j.structure[i] = 'Al'
    j.calc_minimize(pressure=0)
    j.input.control.energy_pot_per_atom()
    j.run()

j.interactive_close()
```

**Comment by niklassiemer** [comment]
You could at least submit the whole notebook, not sure about the interactive jobs...

**Comment by liamhuber** [comment]
We use interactive mode heavily in children of `Protocol`, but the protocols themselves aren't running interactively. You might be able to quickly write an `InteractiveWrapper` to accomplish what you want?

**Comment by pmrv** [comment]
> You could at least submit the whole notebook, not sure about the interactive jobs...

I'd like to avoid submitting the notebook, because it's a lot less flexible, but if nothing else works...



> We use interactive mode heavily in children of `Protocol`, but the protocols themselves aren't running interactively. You might be able to quickly write an `InteractiveWrapper` to accomplish what you want?

I don't understand how `InteractiveWrapper` is supposed to work, but I'll have a look at the protocols, maybe that will give me an idea.

So far I've tried to use a `ParallelMaster` via the `StructureListMaster`, but that creates a child job for every structure, which blows my file quota left and right...

**Comment by jan-janssen** [comment]
The interactive wrapper takes all you code in the run_static function, as you only combine two codes I guess it is the simpler solution:
https://github.com/pyiron/pyiron_atomistics/blob/master/pyiron_atomistics/interactive/scipy_minimizer.py#L108 

Still as basically what you do is calculating a list of structures - then you can place them all in a structure list master and then create a pipeline with a `for each structure function` https://github.com/pyiron/pyiron_atomistics/blob/master/notebooks/pipeline.ipynb

Of do you need any kind of feedback to adjust the way the calculation is executed based on the result of a previous calculation? In that case you need a GenericMaster or Protocol. For the explanation above I assume that you can create the list of structures before submitting the calculation.
