### ISSUE TITLE
pyiron_base broken!?

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_atomistics#223]
I tried to increase the version number of `pyiron_base` in #221 and this breaks our tests! (see below)

@pmrv I fear this is related to the changes in the `copy_to` we made in base? Since the tests for the new `pyiron_base` release are failing and I am in holidays from tomorrow on, could you please take over this release cycle? @muh-hassani please follow the discussion before updating the packages.

```
Traceback (most recent call last):
full_job_sample full_job_sample
  File "/home/runner/work/pyiron_atomistics/pyiron_atomistics/tests/vasp/test_vasp.py", line 345, in test_run_complete
job was stored with the job ID  1
    self.assertTrue(h_out.list_nodes() == [])
full_job_minor_glitch full_job_minor_glitch
AssertionError: False is not true
```

**Comment by liamhuber** [comment]
Did the new hierarchy interface get included in this release? Given that a `.list_nodes` call is failing, I am suspicious.

Also, I think there is `assertListEqual`, which might give us a more useful error message on failure.

**Comment by niklassiemer** [comment]
No, we do not have the new `.list_nodes` interface, yet. In this case actually also just an `self.assertEqual` would help to see what is actually given back by the `list_nodes`.

**Comment by niklassiemer** [comment]
I made a [PR](https://github.com/conda-forge/pyiron_atomistics-feedstock/pull/29) at our conda-forge feedstock to strictly fix to the older `pyiron_base` version to prevent breaking the environment for all `pyiron_atomistics` users.

**Comment by pmrv** [comment]
Seems like the test is checking that the output was not copied, but it did.  So it's almost surely a bug from me in `copy_to`.

**Comment by pmrv** [comment]
Fixed in [here](https://github.com/pyiron/pyiron_base/pull/338).

**Comment by niklassiemer** [comment]
Thanks a lot! Let's do a new release of base and update our dependencies 🙂

**Comment by pmrv** [comment]
conda update is running right now, I'll bump the version to >= 0.2.15 tomorrow morning then.

**Comment by niklassiemer** [comment]
Perfect! Once base is in, a `conda install pyiron`(`_atomistics`) will give a working base! Thanks a lot for taking care of this!

**Comment by pmrv** [comment]
New release is tagged.
