### ISSUE TITLE
Computing mean square displacement in LAMMPS

### ISSUE THREAD

**Issue by ibrsam** [pyiron/pyiron_atomistics#231]
I want to calculate the mean square displacement at a given temerature in LAMMPS, and I found out that it should be done using these commands,

```
compute 1 all msd com yes
variable msd equal c_1[4]
```

I tried to use these commands in pyiron as follows,

```
job.input.control["compute___2"] = "all msd com yes"
job.input.control["variable"] = " msd equal c_1[4]"
job.input.control['dump___1'] =  'all custom ${dumptime} dump.out id type xsu ysu zsu fx fy fz vx vy vz msd'
```

Then, I run a `calc_md` job, but I get the following error,

```
ERROR: Invalid attribute in dump custom command (src/dump_custom.cpp:130)
Last command: dump 1 all custom ${dumptime} dump.out id type xsu ysu zsu fx fy fz vx vy vz msd
```

Can anyone let me know how can I do this correctly? Or, it would be also nice if one of the developers implement this feature in pyiron.

**Comment by samwaseda** [comment]
If there's no particular need for LAMMPS-internal computation, the easier way to calculate MSD is via `job.output.total_displacements`. In your case I presume it can be done via `np.linalg.norm(job.output.total_displacements, axis=-1)`.

**Comment by samwaseda** [comment]
Has the problem been solved?

**Comment by ibrsam** [comment]
Partially, your opinion worked with me (e.g. Calculating the spring constant from the total displacements). I want to give it more time to see if anyone else has an idea about modifying the input file and get it from Lammps. I just want this to reproduce the results in the same way as the author that I am following. But, any way I think I can close the issue as being solved (even it is partially solved).
