### ISSUE TITLE
Deprecation Warning when using SPHInX for workfunction calculations

### ISSUE THREAD

**Issue by skatnagallu** [pyiron/pyiron_atomistics#250]
Hi,

I am running some work function calculations for Ni fcc surfaces using SPHInX. The calculations run smoothly but I get the following deprecation warning.

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: pyiron_atomistics.sphinx.base.set_convergence_precision(ionic_energy=0.01) is deprecated.
  after removing the cwd from sys.path.

What should I be using instead?

**Comment by sudarsan-surendralal** [comment]
Use `ionic_energy_tolerance` instead of `ionic_energy`. It's a more accurate description of the same parameter.

**Comment by samwaseda** [comment]
Thanks @skatnagallu and @sudarsan-surendralal . I'll update the deprecation warning to make the message clearer.
