### ISSUE TITLE
What to use instead of get_symmetry?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_atomistics#268]
`Atoms.get_symmetry` is flagged `@deprecatesoon`, but I can't find any alternatives. What is it that I should be using instead?

**Comment by samwaseda** [comment]
Is it possible that it happened when we decided to do systematic review of functions that use `phonopy`? I guess the idea was to move all of them to `Analyse`. Maybe @niklassiemer knows more about it?
