### ISSUE TITLE
Problems in selecting SPHInX executable versions

### ISSUE THREAD

**Issue by skatnagallu** [pyiron/pyiron_atomistics#286]
Hello. I am trying to use a different SPHInX version for a job. However, when I am trying to use the version for e.g. 'hdf5_mpi' or 'latest_mpi', I am getting an error (ValueError: could not convert string to float: 'hdf5'). This is not an issue if I use a version that starts with a number for e.g "2.6.1_default_mpi" or "3.0_mpi". This is the case even though 'hdf5_mpi' is listed as an available version in the SPHInX executable versions.

**Comment by pmrv** [comment]
I'm not that familiar with the code to set the code version, but it sounds like that's not behavior we want.  Can you post specific code you've used?  Then I'll have a look where we can make it more consistent.

**Comment by skatnagallu** [comment]
```
 job.executable.version = 'hdf5_mpi'
 job.calc_static( electronic_steps=60,
                  retain_charge_density = True,   
                  retain_electrostatic_potential=True)
```

I am trying to do a static calculation on a relaxation job to store wavefunctions using SPHInX 'hdf5_mpi' version.

**Comment by jan-janssen** [comment]
@skatnagallu Is this issue resolved?

**Comment by skatnagallu** [comment]
I think the issue is similar to #297 . For now, saving the job before running it solves the issue.

**Comment by jan-janssen** [comment]
@skatnagallu Thanks for the feedback. I have the feeling there are some issues with the current Sphinx job type @samwaseda  can you comment on this?
