### ISSUE TITLE
Unittests fail for Atoms

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_atomistics#294]
due to `_mendeleev_property_lst = None` (see #293)

**Comment by niklassiemer** [comment]
@pmrv @muh-hassani FYI, I won't trigger a new release until we have resolved this issue.

**Comment by pmrv** [comment]
Does that happen locally for you? All tests pass for me locally as well as on the cluster.

**Comment by niklassiemer** [comment]
No, locally it runs ok. I am curious to see the ci for the last merge! And if this runs smoothly, I am even more puzzled by #293...

**Comment by niklassiemer** [comment]
I am very puzzled by #293, however, on the current master it only breaks/ runs forever on windows. Thus I close this.
