### ISSUE TITLE
Lammps error when using openkim potentials

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron_atomistics#31]
**Summary**

Lammps jobs abort when using openkim potentials

**pyiron Version and Platform**
conda to install dependencies, pyiron in recent git version

**Expected Behavior**
jobs with kim potentials run like jobs with other potentials

**Actual Behavior**
Lammps throws an error like this one:

```
2021-01-20 10:57:54,629 - pyiron_log - WARNING - Job aborted
2021-01-20 10:57:54,630 - pyiron_log - WARNING - LAMMPS (24 Dec 2020)
Reading data file ...
  orthogonal box = (0.0000000 0.0000000 0.0000000) to (3.6000000 3.6000000 3.6000000)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  4 atoms
  read_data CPU = 0.000 seconds
ERROR: Must use 'kim_init' command before simulation box is defined (src/KIM/kim_init.cpp:87)
Last command: kim_init SNAP_ZuoChenLi_2019_Cu__MO_931672895580_000 metal

2021-01-20 10:57:54,790 - pyiron_log - WARNING - Job aborted
2021-01-20 10:57:54,791 - pyiron_log - WARNING - LAMMPS (24 Dec 2020)
Reading data file ...
  orthogonal box = (0.0000000 0.0000000 0.0000000) to (3.6000000 3.6000000 3.6000000)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  4 atoms
  read_data CPU = 0.000 seconds
ERROR: Must use 'kim_init' command before simulation box is defined (src/KIM/kim_init.cpp:87)
Last command: kim_init SNAP_ZuoChenLi_2019quadratic_Cu__MO_265210066873_000 metal
```

**Steps to Reproduce**
Try to run a lammps job with a potential that states kim_init in config

**Further Information, Files, and Links**

Maybe openkim potentials have to be used in another way, if thats the case it would help to improve the error message.

Also I am not sure if this should be here (pyiron_atomistics) or in the pyiron issues?

**Comment by jan-janssen** [comment]
OpenKIM SNAP models are not implemented in pyiron at the moment. You can manually modify the input file to match the modern OpenKIM syntax https://lammps.sandia.gov/doc/kim_commands.html which is required for these new potentials but by default pyiron is still using the traditional `pair_style` and `pair_coeff` commands.

**Comment by jan-janssen** [comment]
Just for clarification all other OpenKIM potentials should work, as explained in: 
https://github.com/pyiron/pyiron/issues/1293#issuecomment-762305260
but they require the `openkim-models` conda package to be installed which is not included in the pyiron dependencies and has to be installed manually.

**Comment by Leimeroth** [comment]
So every potential that does not start with SNAP should work ?

**Comment by jan-janssen** [comment]
> So every potential that does not start with SNAP should work ?

Yes I tested it here https://github.com/jan-janssen/pyiron_test_potentials as explained in https://github.com/pyiron/pyiron/issues/1293#issuecomment-762305260

**Comment by Leimeroth** [comment]
In your mybinder version the potential config starts with pair style kim in mine it starts with kim init. Did you change that manually?
[kim_init EMT_Asap_MetalGlass_PaduraruKenoufiBailey_2007_CuZr__MO_987541074959_001 metal\n, kim_interactions Cu Zr\n]

**Comment by jan-janssen** [comment]
The binder version is installed based on the dependencies in https://github.com/jan-janssen/pyiron_test_potentials/blob/master/binder/environment.yml there are no manual manipulations to the files.

**Comment by Leimeroth** [comment]
I tried a few more things and for some reason the resources downloaded using pyiron.install() (pyiron version 0.4.0 dev5) are different from the ones coming with the conda installation even when are both the same version.

**Comment by jan-janssen** [comment]
Ok, now I see what is causing the issue - I tried to fix it in https://github.com/pyiron/pyiron-resources/pull/29

**Comment by jan-janssen** [comment]
The update resources are included in the next version of `pyiron_base` https://github.com/pyiron/pyiron_base/pull/150

**Comment by jan-janssen** [comment]
Can you try to update to pyiron_base 0.1.45 ? and test if the install works then?

**Comment by Leimeroth** [comment]
I did and it works, just forgot to report back here sorry
