### ISSUE TITLE
Sphinx Tests

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_atomistics#311]
Sometimes the notebooks fail, sometimes they pass - I am not exactly sure what this is related to. I tried debugging it in https://github.com/pyiron/pyiron_atomistics/pull/304 but that did not work out. @samwaseda Can you take a look at this?

**Comment by samwaseda** [comment]
Which tests? `tests_sphinx_sphinx_check_all.ipynb`?

**Comment by jan-janssen** [comment]
Yes, basically the sphinx executable does not start at all - https://github.com/pyiron/pyiron_atomistics/runs/3222546908 
While in other tests like https://github.com/pyiron/pyiron_atomistics/runs/3230915095 everything works fine - so I have the feeling a Sphinx conda package or a dependency is broken.
