### ISSUE TITLE
Unable to run Lammps job in pyiron

### ISSUE THREAD

**Issue by usaikia** [pyiron/pyiron_atomistics#336]
I am getting the following error while tried to run a Lammps job with pyiron. This is just a example md job as given in the pyiron tutorial examples. I have run the same job successfully  before. Please have a look in to it. The error is as follows:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_36408/4143958703.py in <module>
----> 1 job.run()

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/generic/util.py in decorated(*args, **kwargs)
    211                         stacklevel=2
    212                     )
--> 213             return function(*args, **kwargs)
    214         return decorated
    215 

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    663                 self._run_if_repair()
    664             elif status == "initialized":
--> 665                 self._run_if_new(debug=debug)
    666             elif status == "created":
    667                 self._run_if_created()

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py in _run_if_new(self, debug)
   1311             print("job exists already and therefore was not created!")
   1312         else:
-> 1313             self.save()
   1314             self.run()
   1315 

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py in save(self)
   1163         if self._check_if_input_should_be_written():
   1164             self.project_hdf5.create_working_directory()
-> 1165             self.write_input()
   1166             _copy_restart_files(job=self)
   1167         self.status.created = True

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/lammps/base.py in write_input(self)
    377             file_name="potential.inp", cwd=self.working_directory
    378         )
--> 379         self.input.potential.copy_pot_files(self.working_directory)
    380 
    381     def _get_executable_version_number(self):

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/lammps/potential.py in copy_pot_files(self, working_directory)
     92 
     93     def copy_pot_files(self, working_directory):
---> 94         if self.files is not None:
     95             _ = [shutil.copy(path_pot, working_directory) for path_pot in self.files]
     96 

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/lammps/potential.py in files(self)
     84                     path=path,
     85                     resource_path_lst=resource_path_lst,
---> 86                     rel_path=os.path.join("lammps", "potentials")
     87                 ))
     88             if len(absolute_file_paths) != len(list(self._df["Filename"])[0]):

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/atomistics/job/potentials.py in find_potential_file_base(path, resource_path_lst, rel_path)
    204                 return path_indirect
    205     raise ValueError("Either the filename or the functional has to be defined.",
--> 206                      path, resource_path_lst)

ValueError: ('Either the filename or the functional has to be defined.', 'AlCaMg_potential/library.meam,AlCaMg_potential/AlCaMg.meam', ['/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc', '/u/system/SLES12/soft/pyiron/dev/anaconda3/share/pyiron', '/u/system/SLES12/soft/pyiron/dev/anaconda3/share/iprpy', '/u/system/SLES12/soft/pyiron/dev/anaconda3/share/iprpy', '/u/system/SLES12/soft/pyiron/dev/anaconda3/share/iprpy', '/u/system/SLES12/soft/pyiron/dev/anaconda3/share/iprpy'])
```

**Comment by usaikia** [comment]
**Here is my code :**
```
from pyiron import Project
import numpy as np
import matplotlib.pyplot as plt

pr = Project('calculations')

# Bulk
## fcc Al3Sc

basis = pr.create_ase_bulk('Al', cubic=True)
supercell_3x3x3 = basis.repeat([3, 3, 3])
supercell_3x3x3.plot3d()

job = pr.create_job(job_type=pr.job_type.Lammps, job_name='Al_T800K', delete_existing_job=True)

#ham = pr.create_job(job_type=pr.job_type.Lammps, job_name='relax', delete_existing_job=True)

job.structure = supercell_3x3x3
job.calc_md(temperature=800, pressure=0, n_ionic_steps=10000)

#job.list_potentials()

pot = job.list_potentials()[0]
print ('Selected potential: ', pot)
job.potential = pot

job.run()
```

**Comment by max-hassani** [comment]
@usaikia, I tried your code snippet with another potential and it worked, i.g. `job.potential = job.potentail_list()[2]`. I am not sure, though what is wrong with the initial potential. Maybe others have more experience and give us some feedbacks.

**Comment by pmrv** [comment]
> @usaikia, I tried your code snippet with another potential and it worked, i.g. `job.potential = job.potentail_list()[2]`. I am not sure, though what is wrong with the initial potential. Maybe others have more experience and give us some feedbacks.

I think this also tripped me once.  Were you specifically looking for this potential or did it just happened to be the first one?  If you need this potential we'll have to look into it, otherwise I'd suggest we just kick it out for now.

**Comment by usaikia** [comment]
@muh-hassani Thanks. The first two potentials are not working. I will use another potential.

**Comment by usaikia** [comment]
I have my own potential file and I want to run the Lammps job with this EAM potential. What is the right way to assign my own potential file to the job?

**Comment by pmrv** [comment]
You can define your own potential by passing a [custom dataframe](https://pyiron-atomistics.readthedocs.io/en/latest/source/faq.html#how-to-use-a-custom-potential-in-lammps).

**Comment by usaikia** [comment]
> > @usaikia, I tried your code snippet with another potential and it worked, i.g. `job.potential = job.potentail_list()[2]`. I am not sure, though what is wrong with the initial potential. Maybe others have more experience and give us some feedbacks.
> 
> I think this also tripped me once. Were you specifically looking for this potential or did it just happened to be the first one? If you need this potential we'll have to look into it, otherwise I'd suggest we just kick it out for now.

**Comment by pmrv** [comment]
> You can define your own potential by passing a [custom dataframe](https://pyiron-atomistics.readthedocs.io/en/latest/source/faq.html#how-to-use-a-custom-potential-in-lammps).

The part under 'Config' gives the lammps commands to you would usually write into your input script.

**Comment by usaikia** [comment]
@pmrv  Thanks. I will try this custom dataframe.

**Comment by usaikia** [comment]
@pmrv I have a AlSc eam potential file. I modified the custom dataframe as given below. Now, my lammps job is running fine with this potential. Thanks for your help!
Please have a look at my custom dataframe to check I am defining everything correctly or not.

```python
custom_potential = pd.DataFrame({
  'Name': ['alsc_eam_alloy_UdayGajera_beta_version'],
  'Filename': [[]],
  'Model': ['Custom'],
  'Species': [['Al', 'Sc']],
  'Config': [['pair_style eam/alloy \n',
              'pair_coeff * * /u/usaikia/lammps_potentials/Al_Sc/alsc_eam_alloy_UdayGajera_beta_version.eam Al Sc \n']]
})
```

**Comment by pmrv** [comment]
> @pmrv I have a AlSc eam potential file. I modified the custom dataframe as given below. Now, my lammps job is running fine with this potential. Thanks for your help!
> Please have a look at my custom dataframe to check I am defining everything correctly or not.
> 
> ```python
> custom_potential = pd.DataFrame({
>   'Name': ['alsc_eam_alloy_UdayGajera_beta_version'],
>   'Filename': [[]],
>   'Model': ['Custom'],
>   'Species': [['Al', 'Sc']],
>   'Config': [['pair_style eam/alloy \n',
>               'pair_coeff * * /u/usaikia/lammps_potentials/Al_Sc/alsc_eam_alloy_UdayGajera_beta_version.eam Al Sc \n']]
> })
> ```

This works, but the recommended way would be to give a relative file name in config only and give the full path in the 'Filename' column.  This file would then be copied over before the job runs and therefor would not be lost if you delete the original file.

Something like
```python
custom_potential = pd.DataFrame({
  'Name': ['alsc_eam_alloy_UdayGajera_beta_version'],
  'Filename': [['/u/usaikia/lammps_potentials/Al_Sc/alsc_eam_alloy_UdayGajera_beta_version.eam']],
  'Model': ['Custom'],
  'Species': [['Al', 'Sc']],
  'Config': [['pair_style eam/alloy \n',
              'pair_coeff * * alsc_eam_alloy_UdayGajera_beta_version.eam Al Sc \n']]
})
```

**Comment by usaikia** [comment]
@pmrv Thanks! I will modify my file accordingly.

**Comment by jan-janssen** [comment]
@usaikia Can you post your .pyiron file? Please remove the passwords before posting. I would like to understand if that is a general issue with the potentials in conda or an issue specific to your configuration or the MPIE cluster.

**Comment by usaikia** [comment]
@jan-janssen Here is my .pyiron file:

```
[DEFAULT]                                                                                                               
TYPE = Postgres                                                                                                         
HOST = pyiron-db-cmmc.esc.rzg.mpg.de                                                                                    
NAME = pyiron                                                                                                           
USER = usaikia                                                                                                          
PASSWD =                                                                                                
JOB_TABLE = jobs_cmmc                                                                                                   
TOP_LEVEL_DIRS = /cmmc/u                                                                                                
VIEWERUSER = cmmc_view                                                                                                 
VIEWERPASSWD =                                                                                        
VIEWER_TABLE = jobs_cmmc_admin                                                                                          
RESOURCE_PATHS = /u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc 
```

**Comment by pmrv** [comment]
@jan-janssen @usaikia I suppose this can be closed?

**Comment by usaikia** [comment]
@pmrv resolved from my side.
