### ISSUE TITLE
Should `Atoms.get_chemical_indices()` return pointer?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#341]
I find the following lines a bit counterintuitive.

```python
>>> structure = pr.create.structure.bulk('Al', cubic=True)
>>> structure[0] = 'Fe'
>>> indices = structure.get_chemical_indices()
>>> print(indices)
>>> structure[:] = 'Al'
>>> print(indices)
[1 0 0 0]
[0 0 0 0]
```

I would rather expect that `Atoms.get_chemical_indices()` returns a copy of the indices and not the pointer, also because changing `indices` has (for some reason) no effect on the atom species. But before I start changing this I just wanted to make sure that this is not the desired behaviour. @sudarsan-surendralal @pmrv @jan-janssen

**Comment by sudarsan-surendralal** [comment]
I agree, this should not return a pointer. Go ahead with the changes!

**Comment by liamhuber** [comment]
Also agreed. It's sometimes nice to have a pointer, but I would say `structure.indices` -> pointer; while `structure.get_chemical_indices()` -> new array as you suggest here.
