### ISSUE TITLE
job is shutting down automatically

### ISSUE THREAD

**Issue by usaikia** [pyiron/pyiron_atomistics#378]
One of my job suddenly killed. I found following information about the killed job in pyiron.log file. Is there something wrong with my pyiron account. Here is the error message:
2021-09-30 11:12:31,063 - pyiron_log - INFO - Reconnecting to DB; connection closed.
2021-09-30 11:13:14,274 - pyiron_log - INFO - Job 15937703 intercept signal 15, job is shutting down

**The same thing happend with another job also:**
2021-09-30 13:54:49,131 - pyiron_log - INFO - Reconnecting to DB; connection closed.
2021-09-30 13:54:49,131 - pyiron_log - INFO - Reconnecting to DB; connection closed.
2021-09-30 13:55:22,399 - pyiron_log - INFO - Job 15939082 intercept signal 15, job is shutting down

**Comment by max-hassani** [comment]
I checked with @usaikia, via the following script, that his connection to the database has no problem.
```
from sqlalchemy import create_engine
from pyiron_base import Settings
s = Setting()
db_engine = create_engine(s._configuration['sql_connection_string'])
db_conn = db_engine.connect()
db_conn.close()
```

**Comment by usaikia** [comment]
**Here is the script I used to submit the job:**

```python
strain_matrix = np.zeros([3,3])
strain = (fitted_lax_gb_s3_111_1m21_Fe71Zn1_conf0_evfit_isif2 - basis_gb_s3_111_1m21_Fe71Zn1_conf0_init.cell[0,0])/ \
                                                                        basis_gb_s3_111_1m21_Fe71Zn1_conf0_init.cell[0,0]

ham_gb_s3_111_1m21_Fe71Zn1_conf0_evfitted_isif2 = pr.create.job.Vasp(job_name='gb_s3_111_1m21_Fe71Zn1_conf0_evfitted_isif2')

strain_matrix[0,0] = strain
tmp = basis_gb_s3_111_1m21_Fe71Zn1_conf0_init.copy()
tmp.apply_strain(strain_matrix)

ham_gb_s3_111_1m21_Fe71Zn1_conf0_evfitted_isif2.structure = tmp
ham_gb_s3_111_1m21_Fe71Zn1_conf0_evfitted_isif2.set_kpoints(scheme='MP', mesh=[3, 14, 12])    
set_vasp_incar_relax(ham_gb_s3_111_1m21_Fe71Zn1_conf0_evfitted_isif2, npar=8, isif=2)
ham_gb_s3_111_1m21_Fe71Zn1_conf0_evfitted_isif2.input.incar['AMIN'] = 0.01

ham_gb_s3_111_1m21_Fe71Zn1_conf0_evfitted_isif2.set_exchange_correlation_functional('PBE')
ham_gb_s3_111_1m21_Fe71Zn1_conf0_evfitted_isif2.potential.Fe = 'Fe'
ham_gb_s3_111_1m21_Fe71Zn1_conf0_evfitted_isif2.potential.Zn = 'Zn'

ham_gb_s3_111_1m21_Fe71Zn1_conf0_evfitted_isif2.server.queue = 'p_cmfe'
ham_gb_s3_111_1m21_Fe71Zn1_conf0_evfitted_isif2.server.cores = 64

ham_gb_s3_111_1m21_Fe71Zn1_conf0_evfitted_isif2.run()
```

**Comment by usaikia** [comment]
I tried "squeue -u usaikia" in the terminal. According to it's output the job is in PD state. How "job.status" commend is showing that this job is aborted.

**Comment by usaikia** [comment]
@muh-hassani Here is my info.log and pyiron.log file -
[info.log](https://github.com/pyiron/pyiron_atomistics/files/7259865/info.log)
[pyiron.log](https://github.com/pyiron/pyiron_atomistics/files/7259866/pyiron.log)

**Comment by pmrv** [comment]
I've had a brief look at the log and line like
```
2021-09-30 11:13:14,274 - pyiron_log - INFO - Job 15937703 intercept signal 15, job is shutting down
```
indicate that something is sending `SIGTERM` to your jobs externally.  Did you check your time limit when submitting to the queue?

**Comment by usaikia** [comment]
@pmrv I found this line "**#SBATCH --time=5760**" in the run_queue.sh file generated by pyiron. This means my job time limit is 4 days, right? But this job was killed before that.

**Comment by niklassiemer** [comment]
There are other reasons a job might get killed by the OS, e.g. if the memory consumption is too high. I am not sure if this could be a problem in this case, though.

**Comment by usaikia** [comment]
@niklassiemer The output of "**sacct --format="MaxRSS" -j 2448460**" for this job is:    
MaxRSS
----------
   286475K
      674K
  5419225K

**Comment by pmrv** [comment]
The default allocation for RAM is 3GB.  Depending on how many cores your job ran with, your numbers are pretty close to this limit.

**Comment by usaikia** [comment]
@pmrv I used 64 cores. Is it possible increase RAM limit for my vasp job in pyiron?

**Comment by pmrv** [comment]
You can set `job.server.memory_max` for maximum ram in GB per node.

**Comment by usaikia** [comment]
@pmrv Thanks! I will give it a try.
