### ISSUE TITLE
Automatic triclinic boxes in LAMMPS?

### ISSUE THREAD

**Issue by t-brink** [pyiron/pyiron_atomistics#38]
When I run a LAMMPS simulation with a barostat and I also apply a barostat to shear components, the simulation can fail when the input simulation cell is orthogonal:

```
job2 = pr.create_job(pr.job_type.Lammps, "test2")
job2.structure = <something orthogonal>
job2.potential = ...
job2.calc_md(
    temperature=1000.0,
    temperature_damping_timescale=100.0,
    pressure=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    pressure_damping_timescale=500.0,
    time_step=1.0,
    n_ionic_steps=100000,
)
```
The reason is that LAMMPS needs to be told if shear of a box is allowed. The command is `change_box all triclinic`. Shouldn't this command be added automatically when applying a barostat with shear components?

**Comment by jan-janssen** [comment]
As far as I see this was addressed by yourself in https://github.com/pyiron/pyiron/pull/1083 so we can close this issue. If this is not fixed feel free to open the issue again.

**Comment by t-brink** [comment]
This has nothing to do with pyiron/pyiron#1083, this bug still exists. If you look at the files in my second comment, they have not been touched by the referenced PR. There is currently a database problem on the cluster, so I cannot test it, but would you please run the provided minimal example in the original comment before assuming this is fixed?

**Comment by jan-janssen** [comment]
What about? 
```
job2.calc_md(
    temperature=1000.0,
    temperature_damping_timescale=100.0,
    pressure=0.0,
    pressure_damping_timescale=500.0,
    time_step=1.0,
    n_ionic_steps=100000,
)
```

**Comment by t-brink** [comment]
I think you are misunderstanding the bug. What you posted might well work, but is completely irrelevant because it doesn't change the shear of the box (if I remember correctly). What about:

```
job2.structure = <something orthogonal>
job2.potential = ...
job2.calc_md(
    temperature=1000.0,
    temperature_damping_timescale=100.0,
    pressure=[0.0, 0.0, 0.0, 6.0, 7.0, 0.0],
    pressure_damping_timescale=500.0,
    time_step=1.0,
    n_ionic_steps=100000,
)
```

(Please also note the crucial part that the input structure has to be orthogonal with zero shear components! If the input box is already "triclinic", as it is called in LAMMPS, then this should works.)

**Comment by jan-janssen** [comment]
So you mean communicating the `change box` from pyiron to LAMMPS once the strain changes, like it is done for interactive jobs in https://github.com/pyiron/pyiron_atomistics/pull/63

**Comment by samwaseda** [comment]
I'll take care of this one.
