### ISSUE TITLE
SPHInX restart_from_charge_density surprisingly starts from atomic density

### ISSUE THREAD

**Issue by freyso** [pyiron/pyiron_atomistics#418]
**Summary**

SPHInX ``restart_from_charge_density`` silently switches to restart from atomic densities if the code believes that no reliable density is available. That produces surprising behavior. It would be better to stop with a warning.
 

**pyiron Version and Platform**

developer version on cmti, as of November 2021.

**Expected Behavior**

Stop with a clear error message.

**Actual Behavior**

pyiron submits job with a different type of charge initialization

**Steps to Reproduce**

It's not entirely clear to me under which circumstances this happens. It was observed by @skatnagallu 

I understand this happens when the main loop was never reached, or when the rho.sxb cannot be found for whatever reason.

The silent workaround seems to be from @samwaseda

**Comment by samwaseda** [comment]
> SPHInX restart_from_charge_density silently switches to restart from atomic densities if the code believes that no reliable density is available.

I don't really understand the phrase here. `rho.sxb` is not meant to be the charge density?

**Comment by skatnagallu** [comment]
When I restart SPHInX jobs based on previous charge density, the function `restart_from_charge_density`  probably does not find the previous job's density file (rho.sxb). Instead of raising an error (that it couldn't find the previous rho.sxb) when this happens, job restarts with a some different charge initialization.

**Comment by samwaseda** [comment]
Ah ok so the atomic density is the estimated charge density based on the atomic configuration then. I didn't get the vocabulary but now I understand the problem. Let me see what VASP does and I'll decide what to do 😎

**Comment by samwaseda** [comment]
So VASP raises an error so I'll fix it in SPHInX then.

```python
/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/shutil.py in copyfile(src, dst, follow_symlinks)
    262         os.symlink(os.readlink(src), dst)
    263     else:
--> 264         with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    265             # macOS
    266             if _HAS_FCOPYFILE:

FileNotFoundError: [Errno 2] No such file or directory: '/cmmc/u/samsstud/RESEARCH/2021/1108/PYIRON/RESTART/vasp_init_hdf5/vasp_init/CHGCAR'
```

**Comment by samwaseda** [comment]
@sudarsan-surendralal VASP raises the error above when `run()` is called, but it might be more helpful to do so when `restart()` is called. In addition, it could be good to say more explicitly that the charge density file was not found

**Comment by sudarsan-surendralal** [comment]
Thanks for pointing this out @samwaseda. I've implemented a generic check in https://github.com/pyiron/pyiron_atomistics/pull/422. Can you have a look at this? If you like it we can also apply them in  https://github.com/pyiron/pyiron_atomistics/pull/420.
