### ISSUE TITLE
Phonon Band Structure

### ISSUE THREAD

**Issue by ibrsam** [pyiron/pyiron_atomistics#42]
How to get the phonon bandstructure using pyiron?

**Comment by jan-janssen** [comment]
https://github.com/pyiron/pyiron_atomistics/blob/master/notebooks/phonopy_example.ipynb

**Comment by jan-janssen** [comment]
I just noticed that the current public example does not included the band structure, so currently it is only available in the old internal example: 
https://github.com/pyiron/pyiron-meeting-mpie/blob/master/handbook/7-thermodynamics/7-3-phonopy/phonopy.ipynb
Maybe you can update the example in this repository and add the band structure calculation to it.

**Comment by ibrsam** [comment]
Thanks! I will do it.
