### ISSUE TITLE
`set_occupancy_smearing` should have `order` but not `ismear`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#434]
https://github.com/pyiron/pyiron_atomistics/blob/75c1edbc228606dd99e0384c2ed9c998e85ad768/pyiron_atomistics/vasp/base.py#L1285

During today's meeting we realised that it makes little sense to have `ismear` in `set_occupancy_smearing`, but it should have `order` (as I did in SPHInX).

**Comment by sudarsan-surendralal** [comment]
Sorry for the delay (see linked PR)
