### ISSUE TITLE
VASP selective dynamics error

### ISSUE THREAD

**Issue by usaikia** [pyiron/pyiron_atomistics#435]
I used pyiron to fix position of an atom during vasp ionic relaxation calculation (isif=2). After running the job I found a line in the OUTCAR saying:
"""
using selective dynamics as specified on POSCAR
   WARNING: If single coordinates had been selected the selection of coordinates
            is made according to the corresponding   d i r e c t   coordinates!
            Don't support selection of single cartesian coordinates -- sorry ...
""" 
Is there any way to write the input structure file (POSCAR) for vasp run in Direct coordinate system in pyiron?

Here is my job submission script:

h = pr.create.job.Vasp('test')
basis = pr.create.structure.bulk('Fe', cubic=True)
basis.set_initial_magnetic_moments(2*[3.0])
basis.add_tag(selective_dynamics=[False, False, False])
basis.selective_dynamics[0] = [True, True, True]
h.structure = basis
h.calc_minimize()
h.input.incar['ISIF'] = 2
h.run()

**Comment by pmrv** [comment]
Our `write_poscar` function appears to support direct coordinates

https://github.com/pyiron/pyiron_atomistics/blob/788d9c7e4c2f5251536c1d9794aaf2e22a07dafa/pyiron_atomistics/vasp/structure.py#L82

I guess the way to implement this is to change the `Input` class to ask for direct coordinates once it detects some atom coordinates are fixed here

https://github.com/pyiron/pyiron_atomistics/blob/788d9c7e4c2f5251536c1d9794aaf2e22a07dafa/pyiron_atomistics/vasp/base.py#L1802

Feel free to give this a shot in a PR and add me as a reviewer.

**Comment by usaikia** [comment]
@pmrv Thanks! I will open a PR to implement this.
