### ISSUE TITLE
Difference between _key_from_property and _lst_from_property?

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_atomistics#45]
Does anyone with interactive experience know what the difference between these two functions is?

https://github.com/pyiron/pyiron_atomistics/blob/bc4c32156d67d584c00f97a1877ebad598768261/pyiron_atomistics/atomistics/job/interactive.py#L444

https://github.com/pyiron/pyiron_atomistics/blob/bc4c32156d67d584c00f97a1877ebad598768261/pyiron_atomistics/atomistics/job/interactive.py#L424

They seem do to the same to me, so if I don't hear from you I'll throw one of them under the bus.

**Comment by jan-janssen** [comment]
As far as I can see the only difference is that for one tilmestep we either store a single entry - like the potential energy - or a matrix like the cell dimensions.
