### ISSUE TITLE
Can I replace random atomistics by Lennard Jones?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#476]
The current `AtomisticExampleJob`-class returns random forces whenever `run` is called. This is good for some classes, but other classes (most notably Phonopy) it is totally useless. If anyway anything can be returned, can I implement simple Lennard Jones using `get_neighbors`? As everyone probably already knows, `get_neighbors` is extremely fast so I don't think there'd be any disadvantage created with this. Let me know what you think @jan-janssen

**Comment by pmrv** [comment]
It would probably be nice, then we can test some of the master jobs with this, too.

**Comment by jan-janssen** [comment]
I like the idea
