### ISSUE TITLE
ase_to_pyiron is slow

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_atomistics#48]
I'm currently importing a large number of ase structures into a structure container and have noticed it is exceedingly slow.  Importing 1000 structures takes ~40s, 10000 ~4min or longer.  After some profiling I identified `ase_to_pyiron` and this line

https://github.com/pyiron/pyiron_atomistics/blob/d9145e632d8871cfe8f6b4bdd1e867be8f7d773a/pyiron_atomistics/atomistics/structure/atoms.py#L163

as the culprits.  It seems for the element conversion `mendelev` consults some kind of SQL database (???) that takes a lot of time.  Can I skip this conversion somehow?

**Comment by jan-janssen** [comment]
@sudarsan-surendralal Do we still use the pyiron Elements or can we use the ASE Elements now that our Atoms class is derived from the ASE Atoms class?

**Comment by sudarsan-surendralal** [comment]
> 
> 
> @sudarsan-surendralal Do we still use the pyiron Elements or can we use the ASE Elements now that our Atoms class is derived from the ASE Atoms class?

I don't think there's an element class in `ase` since they simply use strings to represent elements. 

> as the culprits. It seems for the element conversion `mendelev` consults some kind of SQL database (???) that takes a lot of time. Can I skip this conversion somehow?

I think the problem is that this lookup is done for every element in the structure rather than just every unique species. I'll open a PR soon

**Comment by pmrv** [comment]
> > as the culprits. It seems for the element conversion `mendelev` consults some kind of SQL database (???) that takes a lot of time. Can I skip this conversion somehow?
> 
> I think the problem is that this lookup is done for every element in the structure rather than just every unique species. I'll open a PR soon

Honestly I'm not sure if that's enough, the average number of atoms in the data set I used is ~11, so that's the best speedup you could get.  The profile shows that `ase_to_pyiron` spends essentially all its time in that one line and that for a feature that I have never used.  Is it (easily) possible to load this information only when it is actually accessed, i.e. if someone asks for the mendelev data for that element?

**Comment by sudarsan-surendralal** [comment]
> Honestly I'm not sure if that's enough, the average number of atoms in the data set I used is ~11, so that's the best speedup you could get. 

Wouldn't a 10x improvement be a significant improvement though?

>The profile shows that `ase_to_pyiron` spends essentially all its time in that one line and that for a feature that I have never used. Is it (easily) possible to load this information only when it is actually accessed, i.e. if someone asks for the mendelev data for that element?

I think there are some users who need such features  for user defined element (for example atoms having completely different valence states). So I think we should discuss this in a larger group before we change the behaviour.

Anyway can you chank the linked PR? Perhaps that'll help

**Comment by pmrv** [comment]
> > Honestly I'm not sure if that's enough, the average number of atoms in the data set I used is ~11, so that's the best speedup you could get.
> 
> Wouldn't a 10x improvement be a significant improvement though?

For now yes, since at the workshop participants won't have to do the conversion, but I still feel we should discuss (tomorrow) if we want to take a big performance hit for a rarely used feature.

> Anyway can you chank the linked PR? Perhaps that'll help

Am testing it right now.
