### ISSUE TITLE
Why does interactive LAMMPS become slower?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#481]
I just realised that interactive LAMMPS gets slower and slower. For this, I created the following short example:

```python
pr = Project('RUNTIME')
import time

structure = pr.create.structure.bulk('Ni').repeat(4)
lmp = pr.create.job.Lammps('time')
lmp.potential = '1995--Angelo-J-E--Ni-Al-H--LAMMPS--ipr1'
lmp.interactive_open()

n_iter = 100
t_lst = np.zeros(n_iter)
t = time.process_time()
for i in range(n_iter):
    for j in range(10):
        lmp.structure = structure.copy()
        lmp.structure.positions += np.random.randn(len(lmp.structure), 3)/1000
        lmp.run()
    t_lst[i] = time.process_time() - t
```

And I observed the following evolution of time (of course I plotted `np.diff(t_lst)` and not `t_lst`). Why does interactive LAMMPS get slower and slower?

<img width="386" alt="Unknown" src="https://user-images.githubusercontent.com/37879103/146355501-418c16a1-0fb4-4832-a7cf-3ebb51ae25f6.png">

**Comment by pmrv** [comment]
Probably the best way to find out is to run the for loop under `cProfile`.

**Comment by samwaseda** [comment]
I just made sure that it doesn't happen with `AtomisticExampleJob`, so it must be either LAMMPS or the pyiron-implementation of LAMMPS. I'll try to see how `cProfile` works but I'm a total loss in this kind of stuff XD

**Comment by pmrv** [comment]
I did a quick profile and roughly ~45% of the time is spent in `GenericInteractiveOutput._lst_from_cache`, specifically this list comprehension

https://github.com/pyiron/pyiron_atomistics/blob/3035031f125ee011696c511db8e88085b1827e20/pyiron_atomistics/atomistics/job/interactive.py#L407

I suppose it makes sense, as the cache gets longer during the calculation, more list -> array conversions are done.

Another ~15% are talking to the database, the rest is writing/reading HDF files.

**Comment by samwaseda** [comment]
AAAAAAHA! So it means there could be a huge gain by making it more efficient.
