### ISSUE TITLE
Bug: pip installation of pyiron fails - Additional documentation needed

### ISSUE THREAD

**Issue by lxknll** [pyiron/pyiron_atomistics#495]
Hey everyone,
I am new to pyiron but seem to have encountered a problem with pip-based installations. I am aware that a conda-based installation is recommended. Unfortunately, this was not possible on my particular machine.

**Summary**

After installing pyiron through `pip install pyiron` as described in the documentation, `import pyiron` will raise an Import Error. Afaik this is because of two dependency issues:
1. pyscal is not in the setup.py of pyiron_atomistics as no PyPI image exists. Thus, it is not installed.
2. The PyPI image of aimsgb is outdated and does not conform to the version breaking changes introduced in its dependency pymatgen (v2022.0.*). 

In order to resolve these issues, the user has to manually install the most recent versions of pyscal and aimsgb from source. After that, pyiron functions as expected.

```bash
# Install pyscal from source.
pip install git+https://github.com/pyscal/pyscal

# Install aimsgb from source.
pip install git+https://github.com/ksyang2013/aimsgb aimsgb
```

It would be great if the documentation contained a reference to these additional steps.

**pyiron Version and Platform**

I installed both the current pypi image (0.4.6) and also tried a local installation from source (0.4.6.post0.dev14)
Both releases were installed into a fresh Python (3.10.1) virtual environment using pyenv (2.2.2).

**Expected Behavior**

Error-free import of pyiron after single-command installation with `pip install pyiron`.

**Actual Behavior**

First, pyscal raises:

```python
ImportError: No module named pyscal
```

After resolving this issue by manually installing the latest version of pyscal, pymatgen raises:

```python
[...]
File "[...]/aimsgb/grain.py", line 5, in <module>
      from pymatgen import Structure, Lattice, PeriodicSite
ImportError: cannot import name 'Structure' from 'pymatgen' (unknown location)
```

**Steps to Reproduce**

1. Create a new virtual environment with pyenv: `pyenv virtualenv pyiron-test`
2. Install pyiron using pip: `pip install pyiron`
3. Try to load pyiron (in a Python interactive shell): 
    ```python
    >>> import pyiron
    ```

**Further Information, Files, and Links**

* Link to [pyscal](https://pyscal.org/en/latest/)
* Link to [aimsgb](https://github.com/ksyang2013/aimsgb)
* Link to [pymatgen](https://github.com/materialsproject/pymatgen)

Please let me know if I missed anything. Thank you kindly for your comments!

**Comment by jan-janssen** [comment]
Hi @lxknll, 

Thank you for your feedback. The easiest way to install pyiron is using conda: 
```
conda install -c conda-forge pyiron
```
I created a patch for `aimsgb` https://github.com/conda-forge/aimsgb-feedstock/blob/master/recipe/pymatgen.patch which fixes the compatibility to the latest pymatgen version - it is included in the conda package but unfortunately not in the pip package. But I definitely agree that we should add this information to our documentation.

**Comment by lxknll** [comment]
Hi @jan-janssen,
thank you for your quick reply - great support! :) The conda installation is definitely very convenient and I used it on my personal machine without issues. In the case at hand, though, this was not possible. Nevertheless, I will try to push for the conda-based installation wherever possible in the future.
