### ISSUE TITLE
Is there a reason `ElectronicStructure` has totally different names for attributes and hdf5 tags?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#512]
https://github.com/pyiron/pyiron_atomistics/blob/64a1e60f60562932219a1c6d8b7eca17a84336ad/pyiron_atomistics/dft/waves/electronic.py#L516

The fact that the attributes and the hdf5 tags are different makes it very difficult to replace them by `DataContainer` later on. Is there a particular reason that this is the case right now? @sudarsan-surendralal

**Comment by sudarsan-surendralal** [comment]
This code is pretty ancient and was written way before we had `DataContainer`s. I'm okay with us changing the hdf5 tags as long as backward compatibility is maintained.
