### ISSUE TITLE
scipy 1.8 incompatibility

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron_atomistics#521]
**Summary**

pyiron_atomistics/atomistics/structure/analyse.py tries to 
from scipy.spatial.qhull import _QhullUser
which is not available in scipy 1.8.0 

**Error**
File ~/git_projects/pyiron_atomistics/pyiron_atomistics/atomistics/structure/analyse.py:9, in <module>
      7 from scipy.sparse import coo_matrix
      8 from scipy.spatial import Voronoi, Delaunay
----> 9 from scipy.spatial.qhull import _QhullUser
     10 from pyiron_atomistics.atomistics.structure.pyscal import (
     11     get_steinhardt_parameter_structure,
     12     analyse_cna_adaptive,
   (...)
     16     analyse_find_solids,
     17 )
     18 from pyiron_atomistics.atomistics.structure.strain import Strain

ImportError: cannot import name '_QhullUser' from 'scipy.spatial.qhull' (/nfshome/leimeroth/miniconda3/lib/python3.9/site-packages/scipy/spatial/qhull.py)

**Comment by niklassiemer** [comment]
Also visible and to be solved in #522
