### ISSUE TITLE
calculating lattice thermal conductivity in pyiron

### ISSUE THREAD

**Issue by sinazadeh** [pyiron/pyiron_atomistics#532]
Is there any function in pyiron to calculate Lattice thermal conductivity? There is a package named phono3py (https://phonopy.github.io/phono3py/) for this and I was wondering how to implement it in pyiron. (it is different from phonopy function)

**Comment by jan-janssen** [comment]
Hi @sinazadeh, 

We do not have a phono3py interface yet but in general it should follow analogously to the phonopy interface. First you create the displacements, then from the displacements you generate ASE structures so pyiron can execute them and finally from the forces calculated for the displacements you can calculate the thermal conductivity using phono3py. I briefly looked at the code and to my understanding phono3py class provides these functions: https://github.com/phonopy/phono3py/blob/master/phono3py/api_phono3py.py#L94 
I hope this helps.

Best, 

Jan

**Comment by jan-janssen** [comment]
I wrote a quick example how to couple both package in https://github.com/jan-janssen/phono3py_pyiron/blob/main/phonopy3_calculate.ipynb

**Comment by sinazadeh** [comment]
Thank you. Your example is very helpful.

**Comment by pmrv** [comment]
> Thank you. Your example is very helpful.

Feel free to adapt this into a PR. ;)

**Comment by sinazadeh** [comment]
> > Thank you. Your example is very helpful.
> 
> 
> 
> Feel free to adapt this into a PR. ;)

We are actually on it 😄

**Comment by amirbehbahanian** [comment]
> I wrote a quick example how to couple both package in https://github.com/jan-janssen/phono3py_pyiron/blob/main/phonopy3_calculate.ipynb

Hi Jan,

I followed the procedure in the example you uploaded and the procedure works well using it without a cutoff_pair_distance. But by adding a cutoff distance to reduce the number of jobs:

 _(phono.generate_displacements(cutoff_pair_distance=3.0)_ 
_structure_lst = [phonopy_to_atoms(s) for s in phono.supercells_with_displacements if s is not None]_

the following error is raised. I would appreciate your comment on the problem.

![image (3)](https://user-images.githubusercontent.com/38739465/156287171-e2d869d6-c66a-4c33-b1bc-1a4917267280.png)


Regards,
Amir

**Comment by jan-janssen** [comment]
It is not very elegant but you could use: 
```
forces_new_lst = []
i = 0
for displace in phono.supercells_with_displacements:
    if displace is not None:
        forces_new_lst.append(forces_lst[i])
        i += 1
    else:
        forces_new_lst.append(np.zeros([64, 3]))
phono.forces = np.array(forces_new_lst)
```

**Comment by jan-janssen** [comment]
I uploaded an updated example https://github.com/jan-janssen/phono3py_pyiron/blob/main/phonopy3_calculate_cutoff.ipynb

**Comment by amirbehbahanian** [comment]
Thanks jan

**Comment by jan-janssen** [comment]
@atztogo update the phono3py documentation:

- https://phonopy.github.io/phono3py/phono3py-api.html
- https://phonopy.github.io/phono3py/workflow.html
