### ISSUE TITLE
Setting Phonopy tags from pyiron

### ISSUE THREAD

**Issue by prince-mathews** [pyiron/pyiron_atomistics#549]
Is there a way to set phonopy tags like `FC_SYMMETRY= .TRUE.` or `PM = .TRUE.` directly using pyiron?

**Comment by samwaseda** [comment]
What do they do?

**Comment by jan-janssen** [comment]
Currently these options are not available in pyiron - but you can integrate them. The important steps is mapping them to the input parameters of the `Phonopy` python class: https://github.com/phonopy/phonopy/blob/develop/phonopy/api_phonopy.py#L133

```
Phonopy(
        unitcell,
        supercell_matrix=None,
        primitive_matrix=None,
        nac_params=None,
        factor=VaspToTHz,
        frequency_scale_factor=None,
        dynamical_matrix_decimals=None,
        force_constants_decimals=None,
        group_velocity_delta_q=None,
        symprec=1e-5,
        is_symmetry=True,
        store_dense_svecs=False,
        calculator=None,
        use_lapack_solver=False,
        log_level=0,
)
```

In pyiron `phonopy` is called in https://github.com/pyiron/pyiron_atomistics/blob/master/pyiron_atomistics/atomistics/master/phonopy.py#L203 so you can add the variables to the input https://github.com/pyiron/pyiron_atomistics/blob/master/pyiron_atomistics/atomistics/master/phonopy.py#L164 and then set them to the internal `phonopy` object. @prince-mathews Can you do this?

**Comment by jan-janssen** [comment]
> What do they do?

https://phonopy.github.io/phonopy/setting-tags.html#pm 
https://phonopy.github.io/phonopy/setting-tags.html#fc-symmetry

**Comment by jan-janssen** [comment]
`PM` - https://github.com/phonopy/phonopy/blob/develop/phonopy/api_phonopy.py#L889 
`FC_SYMMETRY` - https://github.com/phonopy/phonopy/blob/master/phonopy/api_phonopy.py#L1050 - I guess

**Comment by prince-mathews** [comment]
Thank you for the links for the exact positions for the tags @jan-janssen. 
I went through the links and I think I can map the 'PM' tag to the parameter in the Phonopy class. However looking at the function corresponding to 'FC_SYMMETRY', it seems that Phonopy by default symmetrizes the force constant matrix, and I couldn't find a tag that could basically switch this off (please correct me if I'm wrong). If this is the case, any suggestions for what can be done?

**Comment by samwaseda** [comment]
I have to say both of these options look like they could potentially destroy the final results (especially `PM = False`, which would correspond to the 1st order fitting that Jörg was mentioning). Are you sure that you need them?

**Comment by prince-mathews** [comment]
> I have to say both of these options look like they could potentially destroy the final results (especially `PM = False`, which would correspond to the 1st order fitting that Jörg was mentioning). Are you sure that you need them?

I want to specifically use `PM=True`. The default tag is 'auto', which considers only plus displacements if the plus and minus displacements are symmetrically equivalent. So with `PM=True`, I can do 2nd order phonon fitting.

**Comment by samwaseda** [comment]
> I want to specifically use `PM=True`. The default tag is 'auto', which considers only plus displacements if the plus and minus displacements are symmetrically equivalent. So with `PM=True`, I can do 2nd order phonon fitting.

I don't think that's true. From what I know, the pyiron implementation of phonopy always considers both plus and minus.

**Comment by prince-mathews** [comment]
> > I want to specifically use `PM=True`. The default tag is 'auto', which considers only plus displacements if the plus and minus displacements are symmetrically equivalent. So with `PM=True`, I can do 2nd order phonon fitting.
> 
> I don't think that's true. From what I know, the pyiron implementation of phonopy always considers both plus and minus.

In the `Phonopy` class, in the link that Jan had shared (https://github.com/phonopy/phonopy/blob/develop/phonopy/api_phonopy.py#L889) the displacements are created using `get_displacements()`, which includes `is_plusminus` argument, which is set to 'auto'. The `get_displacements()` is called in the pyiron implementation of phonopy https://github.com/pyiron/pyiron_atomistics/blob/a5190644f4d83267bb2b82a69dc325f916f360e6/pyiron_atomistics/atomistics/master/phonopy.py#L203 which does not take any input regarding plus minus displacements. So I think currently with every phonopy job we submit, minus displacements are only considered if it is symmetrically inequivalent to the plus displacement. Or am I missing something?

**Comment by samwaseda** [comment]
Here's my proof:

```python
job = pr.create.job.Lammps('lmp')
job.structure = pr.create.structure.bulk('Ni', cubic=True).repeat(3)
job.structure[0] = 'Al'
job.interactive_open()
phono = job.create_job('PhonopyJob', 'phono')
phono.run()
```

```python
run_id, atom_id, xyz_id = np.where(~np.isclose(job.output.total_displacements, 0))
print(job.output.total_displacements[np.where(~np.isclose(job.output.total_displacements, 0))][run_id==1])
print(job.output.total_displacements[np.where(~np.isclose(job.output.total_displacements, 0))][run_id==2])
print(atom_id[run_id==1], xyz_id[run_id==1])
print(atom_id[run_id==2], xyz_id[run_id==2])
```

Output:
```python
[0.00707107 0.00707107 0.00707107 0.00707107]

[-0.00707107 -0.00707107  0.00707107  0.00707107]

[ 1  1 53 53] [0 1 0 1]

[ 1  1 53 53] [0 1 0 1]
```

So both plus and minus are considered

**Comment by samwaseda** [comment]
> So I think currently with every phonopy job we submit, minus displacements are only considered if it is symmetrically inequivalent to the plus displacement.

Correct, and that's what we want, right?

**Comment by prince-mathews** [comment]
> > So I think currently with every phonopy job we submit, minus displacements are only considered if it is symmetrically inequivalent to the plus displacement.
> 
> Correct, and that's what we want, right?

But then what if I want to consider both plus and minus displacements anyway?

**Comment by samwaseda** [comment]
> But then what if I want to consider both plus and minus displacements anyway?

If you are saying that the symmetry recognition of phonopy is not working correctly, then you should rather change the parameters in the symmetry search. Otherwise I don't really see why you should be doing two equivalent calculations, because after all, they are the same...

**Comment by prince-mathews** [comment]
> > But then what if I want to consider both plus and minus displacements anyway?
> 
> If you are saying that the symmetry recognition of phonopy is not working correctly, then you should rather change the parameters in the symmetry search. Otherwise I don't really see why you should be doing two equivalent calculations, because after all, they are the same...

The problem isn't with symmetry recognition of phonopy but if the input structure isn't relaxed then perhaps doing the plus and minus displacements may help?

**Comment by samwaseda** [comment]
> The problem isn't with symmetry recognition of phonopy but if the input structure isn't relaxed then perhaps doing the plus and minus displacements may help?

If the input structure is not relaxed you'll have a loooooooooooooooooooooooooooot more problems so just relax the structure

**Comment by samwaseda** [comment]
Besides there's no relaxation along the direction of the symmetry, so it won't change the results.

**Comment by pmrv** [comment]
I found this by accident and gonna close it, if noone complains.
