### ISSUE TITLE
Unable to run MeamFit job in pyiron

### ISSUE THREAD

**Issue by usaikia** [pyiron/pyiron_atomistics#574]
Hi, I want to construct a EAM potential from a VASP md trajectory using the MeamFit code. My MeamFit job aborts with the following error "Permission denied". Is it a bug in pyiron or I am doing something wrong here (I have added the script I used to run the md job and the MeamFit job for your reference).

```
2022-03-28 11:05:55,790 - pyiron_log - WARNING - Job aborted
2022-03-28 11:05:55,792 - pyiron_log - WARNING - /cmmc/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/thermodynamics/bin/run_meamfit_2.00.sh: line 2: /u/bzg/Thermodynamics/MEAMfit/MEAMfit2_MUST_BE_DISTRIBUTED_VIA_Daresbury_Laboratory_Andrew_Duff: Permission denied
/cmmc/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/thermodynamics/bin/run_meamfit_2.00.sh: line 2: exec: /u/bzg/Thermodynamics/MEAMfit/MEAMfit2_MUST_BE_DISTRIBUTED_VIA_Daresbury_Laboratory_Andrew_Duff: cannot execute: Permission denied
```

#### to run VASP md job
```
j = pr_test.create.job.Vasp('test_md')
tmp = pr_test.create.structure.bulk('Fe', 'bcc', cubic=True, a=2.84)
tmp.set_initial_magnetic_moments(2*[3.0])
tmp.set_repeat([2,2,2])
j.structure = tmp
j.set_kpoints(scheme='GP')
j.calc_md(n_ionic_steps=200, temperature=300, time_step=2)
j.server.queue = 's_cmfe'
j.server.cores = 40
j.run()
```
### to run MeamFit job
```
job = pr_test['test_md']
j = job.create_job(job_type=pr_test.job_type.MeamFit, job_name='meamfit')
j.run()
```

**Comment by pmrv** [comment]
I seems the file `/u/bzg/Thermodynamics/MEAMfit/MEAMfit2_MUST_BE_DISTRIBUTED_VIA_Daresbury_Laboratory_Andrew_Duff` is empty on the cluster and does not have execute permissions, causing the error.

I have no idea how MEAMfit is supposed to be run, but it appears our setup is wrong.

**Comment by pmrv** [comment]
It sounds like you'll need to contact [the author](https://www.scd.stfc.ac.uk/Pages/MEAMfit-v2.aspx) to set it up on the cluster.

**Comment by usaikia** [comment]
@pmrv Thanks the quick response. I will ask at today's pyiron meeting if anyone is familiar with the issue.
