### ISSUE TITLE
Setting convergence precision in sphinx jobs

### ISSUE THREAD

**Issue by skatnagallu** [pyiron/pyiron_atomistics#578]
I am trying to set convergence precision using the function set_convergence_precision function and cal_minimize for sphinx jobs. However, I do not get what I intend to do. Below I am showing three code snippets and their corresponding outputs. 

```python
job = pr.create_job(
          job_type=pr.job_type.Sphinx,
          job_name='test'
          )
job.structure = pr.create_ase_bulk('Al','fcc',3.5)
job.set_convergence_precision(electronic_energy=1e-8, ionic_energy_tolerance=1e-1)
```
output:
```python
print(job.input.sphinx.main.ricQN.dEnergy) #0.0036
print(job.input.sphinx.main.ricQN.bornOppenheimer.scfDiag.dEnergy)#3.6e-06
```

Case 1, sets the ionic energy tolerance correctly but does not set the electronic energy correctly.
 
CASE 2:
```python
job = pr.create_job(
          job_type=pr.job_type.Sphinx,
          job_name='test'
          )
job.structure = pr.create_ase_bulk('Al','fcc',3.5)
job.set_convergence_precision(electronic_energy=1e-8)
job.set_convergence_precision(ionic_energy_tolerance=1e-1)
```
output:
```python
print(job.input.sphinx.main.ricQN.dEnergy) #0.003674
print(job.input.sphinx.main.ricQN.bornOppenheimer.scfDiag.dEnergy) #3.6e-10
```

In case 2, if I call the set_convergence function twice first with only electronic_energy as the parameter and then the second time with only ionic_energy_tolerance as the parameter, it sets the values correctly. However, if I switch the order i.e., I set the ionic_energy_tolerance first and then electronic_energy. The electronic energy is not properly set in the input.

CASE 3:
```python
job = pr.create_job(
          job_type=pr.job_type.Sphinx,
          job_name='test'
          )
job.structure = pr.create_ase_bulk('Al','fcc',3.5)
job.calc_minimize(ionic_steps=100,electronic_steps=100)
job.set_convergence_precision(ionic_energy_tolerance=1e-1,electronic_energy=1e-8)
```
Output:
```python
print(job.input.sphinx.main.ricQN.dEnergy) #3.6e-05
print(job.input.sphinx.main.ricQN.bornOppenheimer.scfDiag.dEnergy)#3.6e-06
```

Finally in case 3 (which is basically what I would like to do), I would set the number of ionic steps and electronic steps using calc_minimize and then set_convergence_precision. This, however, does not set either value to what I intend. However, if I reverse the order in which they are called, the electronic_energy alone is correctly set.

I think this might be a bug.

**Comment by samwaseda** [comment]
By putting `job.calc_minimize()` at the end this problem should be solved.

**Comment by samwaseda** [comment]
Sorry I closed the issue by mistake but I guess with my comment above it should work so I leave it like this :D

**Comment by skatnagallu** [comment]
If I put `job.calc_minimize()` at the end, still sets the ionic_energy_tolerance incorrectly. (As I mentioned with case 3.)

```python
job = pr.create_job(
          job_type=pr.job_type.Sphinx,
          job_name='test'
          )
job.structure = pr.create_ase_bulk('Al','fcc',3.5)

job.set_convergence_precision(ionic_energy_tolerance=1e-1,electronic_energy=1e-8)
job.calc_minimize(ionic_steps=100,electronic_steps=100)
```
Output:

```python
print(job.input.sphinx.main.ricQN.dEnergy)#3.6e-05
print(job.input.sphinx.main.ricQN.bornOppenheimer.scfDiag.dEnergy)#3.6e-10
```

**Comment by samwaseda** [comment]
Ah ok interesting. I guess it's a good new developer task so I'll leave it to you.

**Comment by samwaseda** [comment]
I'll describe what to do in detail later today here.

**Comment by samwaseda** [comment]
So you can take a look at [base.py](https://github.com/pyiron/pyiron_atomistics/blob/master/pyiron_atomistics/sphinx/base.py#L469) - there's one problem in [`load_main_group()`](https://github.com/pyiron/pyiron_atomistics/blob/22fab20c8c6aa9c9e4ed50f47b4fd21934d96154/pyiron_atomistics/sphinx/base.py#L469) (especially from `if "Istep" in self.input:`). Then there's another problem in [`set_convergence_precision()`](https://github.com/pyiron/pyiron_atomistics/blob/22fab20c8c6aa9c9e4ed50f47b4fd21934d96154/pyiron_atomistics/sphinx/base.py#L1029). Feel free to open a PR and let me know if you have difficulties.
