### ISSUE TITLE
Request for function for doing bader charge analysis

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron_atomistics#62]
**Summary**

Hello everyone,
I am looking for a function in pyiron to do Bader charge analysis. 

**Detailed Description**

Usually, it can be done with an executable developed by Prof. Henkelman. [(http://theory.cm.utexas.edu/henkelman/code/bader/)](url)

This executable generates a file (ACF.dat) with the charges of the atoms. 
It would be nice to have a function that can run this executable, generate the ACF.dat file and read the charges of the individual atoms from this file.

The best-case scenario would be when the user can access the Bader charges as an attribute of the job.

**Further Information, Files, and Links**
[(http://theory.cm.utexas.edu/henkelman/code/bader/)](url)

**Comment by sudarsan-surendralal** [comment]
@sravankumarkb Here are the (poorly documented scripts I use). 

First, there's a python script that I place in a suitable directory which creates volumetric cube files of the charge densities provided the pyiron job numbers are given. Let's call this `cube_generator.py`.

```
import sys
from pyiron.vasp.volumetric_data import VaspVolumetricData
from pyiron.atomistics.structure.atoms import Atoms
from pyiron import Project

pr = Project("cube_gen")


job_id = int(sys.argv[1])

print(job_id)
job = pr.inspect(job_id)
print(job.status)
struct = Atoms().from_hdf(job["output"])
working_directory = job.working_directory


cd_core = VaspVolumetricData()
cd_core.from_file(working_directory+"/AECCAR0") 
cd_val = VaspVolumetricData()
cd_val.from_file(working_directory+"/AECCAR2")
cd_val.atoms = struct
cd_total = VaspVolumetricData()
cd_total.total_data = cd_core.total_data + cd_val.total_data
cd_total.atoms = struct
cd_total.total_data *= cd_total.atoms.get_volume()
# cd_val.total_data *= cd_val.atoms.get_volume()
cd_val.write_cube_file(filename=working_directory+"/valence_charge.CUBE")
cd_total.write_cube_file(filename=working_directory+"/total_charge.CUBE")
```


Then I call this to operate on finished pyiron vasp jobs (with the core and valence charges already written out (see the manual for the bader scheme). Then I run the following to get the output from the bader program and parse it: 

```
for ham_new in pr.iter_jobs(convert_to_object=False):
    if ham_new.status == "finished" or ham_new.status == "warning":
        try:
            ham_new["OUTCAR"]
        except ValueError:
            print("decompressing")
            ham_new.decompress()
        struct = Atoms().from_hdf(ham_new["output"])
        filename = ham_new.working_directory+"/ACF.dat"
        if not posixpath.isfile(filename):
            cmd_1 = "python ~/programs/cube_creator.py {}".format(ham_new.job_id)
            subprocess.call(cmd_1, shell=True)
            cmd_1 = "cd " + ham_new.working_directory + " ; "
            cmd_2 = "~/programs/./bader valence_charge.CUBE -ref total_charge.CUBE"
            #print(cmd_1 + cmd_2)
            subprocess.call(cmd_1 + cmd_2, shell=True)
        with open(filename) as f:
            lines = f.readlines()
            charges = np.genfromtxt(lines[2:],max_rows=len(struct))[:, 4]
            volumes = np.genfromtxt(lines[2:],max_rows=len(struct))[:, 6]
```

Keep in mind that the order of the bader charges are sccording to the order in the POSCAR file. So you need to sort it to match the pyiron structure order.

**Comment by samwaseda** [comment]
If it's available on conda-forge shouldn't we have bader analysis as a part of pyiron? @sudarsan-surendralal

**Comment by sudarsan-surendralal** [comment]
> 
> 
> If it's available on conda-forge shouldn't we have bader analysis as a part of pyiron? @sudarsan-surendralal

Actually, yes. I'll add this to my todo list
