### ISSUE TITLE
 `view_potentials` is not listing potentials

### ISSUE THREAD

**Issue by Vishwa-adi** [pyiron/pyiron_atomistics#630]
```python
from pyiron import Project

pr = Project("scratch")

job = pr.create.job.Lammps("LammpsJob")

job.structure = pr.create.structure.bulk("Ni", cubic=True)

job.view_potentials()
```

Problem :
Doesn't show the list of potentials for the structure in lammps calculation (screenshot attached below). I had used the notebook in the garching cluster(using cmti login). It seems to work for Al as described by @liamhuber and only shows 2 potentials . But don't know why not for Ni and also tried by modifying the structure doc string by providing crystalstructure and lattice constant. It still doesn't show. 

![view_potential_problem](https://user-images.githubusercontent.com/106261571/170892599-916423e5-ecb3-43b6-9173-f5ff883d987d.jpeg)

**Comment by pmrv** [comment]
Have you set a structure on the job yet?

**Comment by Vishwa-adi** [comment]
Yes, I did. It still doesn't work, even for Ni as well. It seems to me a problem with pyiron installation. How can I verify this ? Thanks in advance.

**Comment by liamhuber** [comment]
Could you please post a minimum working example, and share your pyiron version?

**Comment by liamhuber** [comment]
I'm just on the latest github version. This works exactly as expected for me:

```python
from pyiron import Project
pr = Project('scratch')
lmp = pr.create.job.Lammps('foo')
lmp.structure = pr.create.structure.bulk('Al')
lmp.view_potentials()
```

You will need to give more details in order for us to reproduce and track down the source of your issue.

**Comment by jan-janssen** [comment]
> It seems to me a problem with pyiron installation. 

Did you install pyiron via conda? Or pip? Or directly from Github?

**Comment by liamhuber** [comment]
It sounds like a path problem. In addition to the info Jan requested, could you please share your resource path? I think it's at pr.state.settings['resource_paths'], but even if my syntax is a bit off that should be enough to find the right thing.

**Comment by Vishwa-adi** [comment]
> > It seems to me a problem with pyiron installation.
> 
> Did you install pyiron via conda? Or pip? Or directly from Github?

None, I used the notebook in the garching cluster. 



> It sounds like a path problem. In addition to the info Jan requested, could you please share your resource path? I think it's at pr.state.settings['resource_paths'], but even if my syntax is a bit off that should be enough to find the right thing.

Here is what I got : ['/cmmc/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc']

**Comment by jan-janssen** [comment]
@tnecnivkcots Can you check the cmmc account from @Vishwa-adi it seems there is an issue with his pyiron configuration?

**Comment by tnecnivkcots** [comment]
@Vishwa-adi what is your username?

@jan-janssen how can I check that? I expect you are talking about the permissions of @Vishwa-adi on the cluster, am I right?

**Comment by Vishwa-adi** [comment]
> @Vishwa-adi what is your username?
> 
> @jan-janssen how can I check that? I expect you are talking about the permissions of @Vishwa-adi on the cluster, am I right?

My username is: avishwakarma

**Comment by tnecnivkcots** [comment]
@Vishwa-adi Thank you for your quick answer. I already checked, if you are in the right group and yes you are.
I expect you just need read and execute permissions to this directory, which are set.

**Comment by pmrv** [comment]
That

> > > It seems to me a problem with pyiron installation.
> > 
> > 
> > Did you install pyiron via conda? Or pip? Or directly from Github?
> 
> None, I used the notebook in the garching cluster.
> 
> > It sounds like a path problem. In addition to the info Jan requested, could you please share your resource path? I think it's at pr.state.settings['resource_paths'], but even if my syntax is a bit off that should be enough to find the right thing.
> 
> Here is what I got : ['/cmmc/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc']

That sounds off.  I get 
```
['/cmmc/u/zora/pyiron/resources',
 '/cmmc/u/zora/software/pyiron-resources-mpie',
 '/cmmc/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc',
 '/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/share/pyiron',
 '/u/system/SLES12/soft/pyiron/dev/anaconda3/share/iprpy',
 '/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/share/iprpy']
```
the first two are added from my `.pyiron`, but the last two should be auto populated and it's where the big potential database is residing.

**Comment by Vishwa-adi** [comment]
> I already checked, if you are in the right group and yes you are. I expect you just need read and execute permissions to this directory, which are set.

I have tried again and it still does not work. 




> That
> 
> > > > It seems to me a problem with pyiron installation.
> > > 
> > > 
> > > Did you install pyiron via conda? Or pip? Or directly from Github?
> > 
> > 
> > None, I used the notebook in the garching cluster.
> > > It sounds like a path problem. In addition to the info Jan requested, could you please share your resource path? I think it's at pr.state.settings['resource_paths'], but even if my syntax is a bit off that should be enough to find the right thing.
> > 
> > 
> > Here is what I got : ['/cmmc/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc']
> 
> That sounds off. I get
> 
> ```
> ['/cmmc/u/zora/pyiron/resources',
>  '/cmmc/u/zora/software/pyiron-resources-mpie',
>  '/cmmc/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc',
>  '/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/share/pyiron',
>  '/u/system/SLES12/soft/pyiron/dev/anaconda3/share/iprpy',
>  '/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/share/iprpy']
> ```
> 
> the first two are added from my `.pyiron`, but the last two should be auto populated and it's where the big potential database is residing.

Thank you for the directories. I can access these last two directories from my terminal. How can I include them to set my potential.

**Comment by jan-janssen** [comment]
@Vishwa-adi Can you post the content of your `~/.pyiron` file ? (please remove any sensitive information, like passwords and so on)

**Comment by Vishwa-adi** [comment]
> @Vishwa-adi Can you post the content of your `~/.pyiron` file ? (please remove any sensitive information, like passwords and so on)

I tried this command on terminal. 
It says: bash: /u/avishwakarma/.pyiron: Permission denied

**Comment by jan-janssen** [comment]
@tnecnivkcots or @freyso Can one of you fix the permissions for @Vishwa-adi ?

**Comment by tnecnivkcots** [comment]
@Vishwa-adi you have to open the file, for example with cat, nano or vim.
example: `cat ~/.pyiron`

If I open the file, I get the following List (I have replaced some details):
```
TYPE = Postgres
HOST = <pyiron-db>
NAME = pyiron
USER = <my_username>
PASSWD = <my_db_password>
JOB_TABLE = jobs_cmmc
TOP_LEVEL_DIRS = /cmmc/u
VIEWERUSER = cmmc_view
VIEWERPASSWD = <my_viewer_password>
VIEWER_TABLE = jobs_cmmc_admin
RESOURCE_PATHS = /u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc
```

**Comment by tnecnivkcots** [comment]
> ```
> ...
> RESOURCE_PATHS = /u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc
> ```

In my case I just have this one resource path, just as @Vishwa-adi and I get the list of potentials
![grafik](https://user-images.githubusercontent.com/82433602/171177188-f68eabe4-6681-447a-8db9-5673f449abfc.png)

Then it is no problem with the path.

@Vishwa-adi Do you have the following in your `.bashrc`?

```bash
test -s ~/.alias && . ~/.alias || true
module load pyiron/dev
```

**Comment by liamhuber** [comment]
Is it possible to migrate issues? We should move this over to an mpie repo. The pyiron code base appears to be functioning exactly as intended.

**Comment by tnecnivkcots** [comment]
Yes it is possible under certain circumstances:
https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by jan-janssen** [comment]
> Is it possible to migrate issues? We should move this over to an mpie repo. The pyiron code base appears to be functioning exactly as intended.

I think we can only transfer issues within one organization not from one organization to another.

**Comment by Vishwa-adi** [comment]
> @Vishwa-adi you have to open the file, for example with cat, nano or vim. example: `cat ~/.pyiron`
> 
> If I open the file, I get the following List (I have replaced some details):
> 
> ```
> TYPE = Postgres
> HOST = <pyiron-db>
> NAME = pyiron
> USER = <my_username>
> PASSWD = <my_db_password>
> JOB_TABLE = jobs_cmmc
> TOP_LEVEL_DIRS = /cmmc/u
> VIEWERUSER = cmmc_view
> VIEWERPASSWD = <my_viewer_password>
> VIEWER_TABLE = jobs_cmmc_admin
> RESOURCE_PATHS = /u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc
> ```

Yes I am able to see my details... it is similar to you:
[DEFAULT]  
TYPE = Postgres
HOST = <pyiron_db>
NAME = pyiron
USER = <my_username>
PASSWD = <my_db_password>
JOB_TABLE = jobs_cmmc
TOP_LEVEL_DIRS = /cmmc/u
VIEWERUSER = cmmc_view
VIEWERPASSWD = <my_viewer_password>
VIEWER_TABLE = jobs_cmmc_admin
RESOURCE_PATHS = /u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc 











> > ```
> > ...
> > RESOURCE_PATHS = /u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc
> > ```
> 
> In my case I just have this one resource path, just as @Vishwa-adi and I get the list of potentials ![grafik](https://user-images.githubusercontent.com/82433602/171177188-f68eabe4-6681-447a-8db9-5673f449abfc.png)
> 
> Then it is no problem with the path.
> 
> @Vishwa-adi Do you have the following in your `.bashrc`?
> 
> ```shell
> test -s ~/.alias && . ~/.alias || true
> module load pyiron/dev
> ```

I have the first line but not the last line i.e :
module load pyiron/dev
I added the last line and saved it.
I ran my jupyter notebook again and it is still not working.

**Comment by freyso** [comment]
@Vishwa-adi: You may need to restart your jupyter server & kernel to see this. bashrc is executed when you open a new bash process, and module load ... sets environment variables that are then passed on along subprocesses.
Please let us know if this solves the problem.

@jan-janssen : I agree that the setup error is pyiron@MPIE specific, BUT the origin of search-paths for potentials is a general pyiron-internal. If Liam is right that the paths have been messed up by Aditya's environment setup - which environment variables are responsible for this? And how can one interrogate pyiron about search paths for different modules (like LAMMPS potentials) (and possibly update them for debugging purposes after "module load pyiron") ?

@tnecnivkcots: is the "module load pyiron/dev" something that every new pyiron user should put into the bashrc? If so, is this documented in our on-boarding docu, and/or done by the "new user" script? I think we should revisit our "get a pyiron user ready" procedures and check where this must happen and who should be responsible.

**Comment by Vishwa-adi** [comment]
> @Vishwa-adi: You may need to restart your jupyter server & kernel to see this. bashrc is executed when you open a new bash process, and module load ... sets environment variables that are then passed on along subprocesses. Please let us know if this solves the problem.
>

These are the commands which I found on internet to restart my jupyter server:

systemctl stop jupyterhub.service
sudo tljh-config reload proxy
sudo tljh-config reload hub

Would you prefer to use these commands or would suggest another one? I have never done this, so would like to have your recommendation @freyso .
Also to mention that I am using the garching cluster from my own laptop i.e using ubuntu for windows(current windows version: Windows 10) and logging in through the vpn, opening ubuntu terminal, using my cmti login credentials and then opening a browser with the url to start working with jupyter-lab.

**Comment by pmrv** [comment]
In your jupyter lab tab, click on `file` in the top left corner, then on `Hub Control Panel` at the very bottom.  There you can stop and restart your server.

**Comment by pmrv** [comment]
> @jan-janssen : I agree that the setup error is pyiron@MPIE specific, BUT the origin of search-paths for potentials is a general pyiron-internal. If Liam is right that the paths have been messed up by Aditya's environment setup - which environment variables are responsible for this? And how can one interrogate pyiron about search paths for different modules (like LAMMPS potentials) (and possibly update them for debugging purposes after "module load pyiron") ?

`pyiron_atomistics` checks whether the `CONDA_PREFIX` or `CONDA_DIR` environment variables are set and if so pushes the path of `iprpy` (the conda package that ships the nist potentials) into the resource path list.  That's a bit ugly, but it means either one has to `module load pyiron/dev` or manually put the `iprpy` path in the config.

**Comment by Vishwa-adi** [comment]
> In your jupyter lab tab, click on `file` in the top left corner, then on `Hub Control Panel` at the very bottom. There you can stop and restart your server.

Thank you! After I restarted my server, I got an build option like this:
![Build_error](https://user-images.githubusercontent.com/106261571/171341796-841284ac-ef4b-49e7-95d9-7a41005aca9d.jpeg)

After clicking on build I got this message:
Build failed with 500.

If you are experiencing the build failure after installing an extension (or trying to include previously installed extension after updating JupyterLab) please check the extension repository for new installation instructions as many extensions migrated to the prebuilt extensions system which no longer requires rebuilding JupyterLab (but uses a different installation procedure, typically involving a package manager such as 'pip' or 'conda').

If you specifically intended to install a source extension, please run 'jupyter lab build' on the server for full output.

> @Vishwa-adi: You may need to restart your jupyter server & kernel to see this. bashrc is executed when you open a new bash process, and module load ... sets environment variables that are then passed on along subprocesses. Please let us know if this solves the problem.

Yes the problem is solved now. I can see the potentials. Thank you very much for the help @pmrv , @jan-janssen , @liamhuber , @freyso and @tnecnivkcots .

**Comment by tnecnivkcots** [comment]
Yeah the "build recommended" message is something I have to check (that is not new).
But if it works now, we can close this issue, right?

**Comment by Vishwa-adi** [comment]
> Yeah the "build recommended" message is something I have to check (that is not new). But if it works now, we can close this issue, right?

Yes we can close the issue.

**Comment by freyso** [comment]
OK, to summarize: it seems that the issue was caused by an incorrect setup of Aditya's MPIE account (missing module load); and Vincent will look at our procedures to ensure this won't happen again. 
It also appears that debugging the issue was severely hindered by the fact that the pyiron developers couldn't point their fingers to the "potential ressource path" as possible origin of the problem right away; it took liam 3 days to come up with the idea, and it was only from @pmrv 's last comment that I learnt that the paths Liam suggested weren't necessarily the ones that ultimately were used. This lack of clues could be leveraged as folllows:  "list_potentials ()" should issue a helpful warning if 0 potentials are found, saying that the ressource search path may be incorrect; printing out the research path list (along with its internal variable name for quick fixes), and possibly a hint that they also may come from environmental variables, listing these. That would give future users the means to identify the source of this problem within 5 min rather than 5 days.

**Comment by tnecnivkcots** [comment]
In Step 2 of our instructions for login the first time, it is already written:
> 2. On CMTI add the following line to your .bashrc (independent of which shell you are using by default,
pyiron is going to be executed within bash, that is why we have to modify the .bashrc):
module load pyiron/dev

Could this be optimized?
Maybe it could be automated, but not without a lack of security. But this is no topic to discuss here.
