### ISSUE TITLE
How to expend JobFactory

### ISSUE THREAD

**Issue by yuyuanjingxuan** [pyiron/pyiron_atomistics#642]
**Summary**

Dear all,

I created a new pyion job class via `TemplateJob` class. Now the creation of such job can be done:
```python
from pyiron import Project
pr = Project('Test')
job = pr.create_job(job_type=ToyJob, job_name='foo')
```

I am trying to create such job in another way:
```python
job = pr.create.job.ToyJob(job_name='foo')
```
However, `ToyJob` is not included in the current `JobFactory`.  I was wondering if there is a flexible way to add a customised job type?
Must I modify the codes in the `pyiron_base/pyiron_base/job/jobtype.py`?
Thank you for your help in advance!

**Comment by pmrv** [comment]
You'll need to add your job to `JOB_CLASS_DICT` that can be imported from `pyiron_base`.  You can check `pyiron_atomistics/__init__.py` for examples how to do it.

Once you're happy with your job, feel free to submit a PR here to add it!

**Comment by yuyuanjingxuan** [comment]
Thanks @pmrv 

The problem is solved by adding a new key to the current `JOB_CLASS_DICT`.

If `ToyJob` is imported by `from toyjob.toyjob import ToyJob`,
then modify
```python
JOB_CLASS_DICT["ToyJob"] = "toyjob.toyjob"
```
