### ISSUE TITLE
job with status "warning" are excluded when creating pyiron table

### ISSUE THREAD

**Issue by jyang2009** [pyiron/pyiron_atomistics#646]
I noticed that when using pyiron tables with pr.create.table, the jobs with status "warning" are excluded in the default. Is there a way to change this and include the "warning" jobs? (Otherwise is there a way to change job status manually?)Thanks a lot for your help.

**Comment by jan-janssen** [comment]
Both is possible, you can run the table again with:
```
table.update_table(job_status_list=["finished", "warning"])
```
This is including jobs with the status `finished` and `warning` in the creation of the job table. 

Alternatively you can change the status of an existing job to `finished` using: 
```
job.status.finished = True
```
