### ISSUE TITLE
evcurve with murnaghan calculation fails

### ISSUE THREAD

**Issue by mdforti** [pyiron/pyiron_atomistics#647]
**Summary**

I am trying to reproduce the calculation of ev curve from sphinx job. The calculation wont find the energies after the loop is performed.

**pyiron Version and Platform**

pyiron as installed for the potentials workshop

**Expected Behavior**

murnaghan calculator gives the list of energies and volumes

**Actual Behavior**

calculation fails with this errors:

WARNING:
job.input.structure != job.structure. The current job.structure will overwrite any changes you may might have made to job.input.structure in the meantime. To disable this overwrite, set job.input.structure.read_only = True. To disable this warning, call job.load_structure_group() after making changes to job.structure.
The job AlfccMurn_0_9 was saved and received the ID: 100
WARNING:
job.input.structure != job.structure. The current job.structure will overwrite any changes you may might have made to job.input.structure in the meantime. To disable this overwrite, set job.input.structure.read_only = True. To disable this warning, call job.load_structure_group() after making changes to job.structure.
The job AlfccMurn_0_92 was saved and received the ID: 101
WARNING:
job.input.structure != job.structure. The current job.structure will overwrite any changes you may might have made to job.input.structure in the meantime. To disable this overwrite, set job.input.structure.read_only = True. To disable this warning, call job.load_structure_group() after making changes to job.structure.
The job AlfccMurn_0_94 was saved and received the ID: 102
WARNING:
job.input.structure != job.structure. The current job.structure will overwrite any changes you may might have made to job.input.structure in the meantime. To disable this overwrite, set job.input.structure.read_only = True. To disable this warning, call job.load_structure_group() after making changes to job.structure.
The job AlfccMurn_0_96 was saved and received the ID: 103
WARNING:
job.input.structure != job.structure. The current job.structure will overwrite any changes you may might have made to job.input.structure in the meantime. To disable this overwrite, set job.input.structure.read_only = True. To disable this warning, call job.load_structure_group() after making changes to job.structure.
The job AlfccMurn_0_98 was saved and received the ID: 104
The job AlfccMurn_1_0 was saved and received the ID: 105
WARNING:
job.input.structure != job.structure. The current job.structure will overwrite any changes you may might have made to job.input.structure in the meantime. To disable this overwrite, set job.input.structure.read_only = True. To disable this warning, call job.load_structure_group() after making changes to job.structure.
The job AlfccMurn_1_02 was saved and received the ID: 106
WARNING:
job.input.structure != job.structure. The current job.structure will overwrite any changes you may might have made to job.input.structure in the meantime. To disable this overwrite, set job.input.structure.read_only = True. To disable this warning, call job.load_structure_group() after making changes to job.structure.
The job AlfccMurn_1_04 was saved and received the ID: 107
WARNING:
job.input.structure != job.structure. The current job.structure will overwrite any changes you may might have made to job.input.structure in the meantime. To disable this overwrite, set job.input.structure.read_only = True. To disable this warning, call job.load_structure_group() after making changes to job.structure.
The job AlfccMurn_1_06 was saved and received the ID: 108
WARNING:
job.input.structure != job.structure. The current job.structure will overwrite any changes you may might have made to job.input.structure in the meantime. To disable this overwrite, set job.input.structure.read_only = True. To disable this warning, call job.load_structure_group() after making changes to job.structure.
The job AlfccMurn_1_08 was saved and received the ID: 109
WARNING:
job.input.structure != job.structure. The current job.structure will overwrite any changes you may might have made to job.input.structure in the meantime. To disable this overwrite, set job.input.structure.read_only = True. To disable this warning, call job.load_structure_group() after making changes to job.structure.
The job AlfccMurn_1_1 was saved and received the ID: 110

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [44], in <module>
----> 1 murn.run()

File /srv/conda/envs/notebook/lib/python3.8/site-packages/pyiron_base/generic/util.py:213, in Deprecator.__deprecate_argument.<locals>.decorated(*args, **kwargs)
    203     if kw in self.arguments:
    204         warnings.warn(
    205             message_format.format(
    206                 "{}.{}({}={})".format(
   (...)
    211             stacklevel=2,
    212         )
--> 213 return function(*args, **kwargs)

File /srv/conda/envs/notebook/lib/python3.8/site-packages/pyiron_base/job/generic.py:704, in GenericJob.run(self, delete_existing_job, repair, debug, run_mode, run_again)
    702     self._run_if_repair()
    703 elif status == "initialized":
--> 704     self._run_if_new(debug=debug)
    705 elif status == "created":
    706     self._run_if_created()

File /srv/conda/envs/notebook/lib/python3.8/site-packages/pyiron_base/job/generic.py:1423, in GenericJob._run_if_new(self, debug)
   1421 else:
   1422     self.save()
-> 1423     self.run()

File /srv/conda/envs/notebook/lib/python3.8/site-packages/pyiron_base/generic/util.py:213, in Deprecator.__deprecate_argument.<locals>.decorated(*args, **kwargs)
    203     if kw in self.arguments:
    204         warnings.warn(
    205             message_format.format(
    206                 "{}.{}({}={})".format(
   (...)
    211             stacklevel=2,
    212         )
--> 213 return function(*args, **kwargs)

File /srv/conda/envs/notebook/lib/python3.8/site-packages/pyiron_base/job/generic.py:706, in GenericJob.run(self, delete_existing_job, repair, debug, run_mode, run_again)
    704     self._run_if_new(debug=debug)
    705 elif status == "created":
--> 706     self._run_if_created()
    707 elif status == "submitted":
    708     self._run_if_submitted()

File /srv/conda/envs/notebook/lib/python3.8/site-packages/pyiron_base/job/generic.py:1442, in GenericJob._run_if_created(self)
   1440     self.run_if_manually(_manually_print=False)
   1441 elif self.server.run_mode.modal:
-> 1442     self.run_static()
   1443 elif (
   1444     self.server.run_mode.non_modal
   1445     or self.server.run_mode.thread
   1446     or self.server.run_mode.worker
   1447 ):
   1448     self.run_if_non_modal()

File /srv/conda/envs/notebook/lib/python3.8/site-packages/pyiron_base/master/parallel.py:677, in ParallelMaster.run_static(self)
    673     self._run_if_master_non_modal_child_non_modal(job)
    674 elif (self.server.run_mode.modal and job.server.run_mode.modal) or (
    675     self.server.run_mode.interactive and job.server.run_mode.interactive
    676 ):
--> 677     self._run_if_master_modal_child_modal(job)
    678 elif self.server.run_mode.modal and job.server.run_mode.non_modal:
    679     self._run_if_master_modal_child_non_modal(job)

File /srv/conda/envs/notebook/lib/python3.8/site-packages/pyiron_base/master/parallel.py:600, in ParallelMaster._run_if_master_modal_child_modal(self, job)
    598 if self.is_finished():
    599     self.status.collect = True
--> 600     self.run()
    601 elif self.status.busy:
    602     self.status.refresh = True

File /srv/conda/envs/notebook/lib/python3.8/site-packages/pyiron_base/generic/util.py:213, in Deprecator.__deprecate_argument.<locals>.decorated(*args, **kwargs)
    203     if kw in self.arguments:
    204         warnings.warn(
    205             message_format.format(
    206                 "{}.{}({}={})".format(
   (...)
    211             stacklevel=2,
    212         )
--> 213 return function(*args, **kwargs)

File /srv/conda/envs/notebook/lib/python3.8/site-packages/pyiron_base/job/generic.py:712, in GenericJob.run(self, delete_existing_job, repair, debug, run_mode, run_again)
    710     self._run_if_running()
    711 elif status == "collect":
--> 712     self._run_if_collect()
    713 elif status == "suspend":
    714     self._run_if_suspended()

File /srv/conda/envs/notebook/lib/python3.8/site-packages/pyiron_base/master/parallel.py:470, in ParallelMaster._run_if_collect(self)
    462 """
    463 Internal helper function the run if collect function is called when the job status is 'collect'. It collects
    464 the simulation output using the standardized functions collect_output() and collect_logfiles(). Afterwards the
    465 status is set to 'finished'.
    466 """
    467 self._logger.info(
    468     "{}, status: {}, finished".format(self.job_info_str, self.status)
    469 )
--> 470 self.collect_output()
    472 job_id = self.get_job_id()
    473 db_dict = {}

File /srv/conda/envs/notebook/lib/python3.8/site-packages/pyiron_atomistics/atomistics/master/murnaghan.py:793, in Murnaghan.collect_output(self)
    791     energy = ham["output/generic/energy_pot"][-1]
    792 else:
--> 793     raise ValueError("Neither energy_pot or energy_tot was found.")
    794 volume = ham["output/generic/volume"][-1]
    795 erg_lst.append(np.mean(energy))

ValueError: Neither energy_pot or energy_tot was found.

**Steps to Reproduce**

```
run this instructions:
from pyiron import Project

pr = Project('EVAlfcc')

alfcc = pr.create.structure.bulk('Al', 'fcc',a=4.0)

base_job = pr.create_job(pr.job_type.Sphinx, 'alfccrefjob', delete_existing_job=True)

base_job.structure = alfcc.copy()

base_job.set_kpoints(k_mesh_spacing=1)

base_job.set_exchange_correlation_functional('PBE')

base_job.set_encut(300)

base_job.calc_static()

base_job['output/generic/energy_tot']

murn = pr.create_job(pr.job_type.Murnaghan, 'AlfccMurn', delete_existing_job=True)

murn.input['num_points'] = 11

murn.ref_job = base_job

murn.run()

results = pr.job_table()

pr['AlfccMurn']

results.iloc[1:].job.map(lambda j: murn[j]['output/generic/energy'])

results.subjob

```

**Further Information, Files, and Links**

**Comment by jan-janssen** [comment]
@samwaseda Can this be related to the latest changes to Sphinx?

**Comment by samwaseda** [comment]
ah ok it's because murnaghan uses `inspect`. This doesn't work anymore in the latest pyiron-SPHInX version.

**Comment by jan-janssen** [comment]
You mean because it is using the `DataContainer` for the output rather than storing the output directly in the HDF5 file?

**Comment by samwaseda** [comment]
So the problem essentially comes from the fact that SPHInX output uses `DataContainer`, which doesn't have the standard folders anymore. I see the following possibilities:

1. Murnaghan uses `load` (or allows to use `load` if `inspect` fails)
2. Make `inspect` compatible with `DataContainer`
3. Revert SPHInX changes

I would love to keep the current SPHInX implementation (and therefore would discard the option 3), mainly because I can imagine that the problem would appear later if other programs start using `DataContainer`. On the other hand, I cannot single-handedly decide whether to use `load` instead of `inspect` in Murnaghan, or to make `inspect` compatible with `DataContainer`. Let me know what you think.

**Comment by jan-janssen** [comment]
@pmrv Can we fix this? It is not only the `Murnaghan` but also the pyiron table which relies on the `inspect` mode so having the content inside the data container not available during `inspect` is very dangerous.

**Comment by pmrv** [comment]
> @pmrv Can we fix this? It is not only the `Murnaghan` but also the pyiron table which relies on the `inspect` mode so having the content inside the data container not available during `inspect` is very dangerous.

I'll pick up https://github.com/pyiron/pyiron_base/pull/658 again after the workshop, that should fix it.

**Comment by pmrv** [comment]
>     2. Make `inspect` compatible with `DataContainer`

My goal was now to first automatically load `DataContainer` lazily from a `JobPath` if it finds one, since that is already almost implemented.   Then midterm I'd want to see again if I can rework how `DataContainer`s store themselves in compatible way.

**Comment by pmrv** [comment]
Fix is coming in the next pyiron_base release.
