### ISSUE TITLE
setting pseudopotentials for vasp

### ISSUE THREAD

**Issue by jyang2009** [pyiron/pyiron_atomistics#648]
Dear all,

I'm just wondering if anyone could send me the correct command for setting pseudopotentials for vasp calculations. For example, I'm running a calculation for Fe and by job.list_potentials I get ['Fe','Fe_GW','Fe_pv', 'Fe_sv','Fe_sv_GW'] as the available potentials. How can I set the Fe pseudopotential to 'Fe_sv'? Thanks a lot.

**Comment by jan-janssen** [comment]
I am not sure who is maintaining the VASP interface after @sudarsan-surendralal left, but the general explanation can be found in the FAQ: https://pyiron.readthedocs.io/en/latest/source/faq.html#how-to-use-a-custom-pseudo-potential-in-vasp

**Comment by jyang2009** [comment]
@tnecnivkcots Hi Vicent, I'm wondering where the potcar files are stored on cmti?

**Comment by tnecnivkcots** [comment]
After a quick search with `find -depth -name vasp` and some comparing to the documentation, I found it in
`/u/system/soft/pyiron/dev/pyiron-resources-cmmc/vasp/potentials/potpaw_PBE`.
If it is the correct path, it is a pleasure to can help.
