### ISSUE TITLE
interactive_open() not working

### ISSUE THREAD

**Issue by Vishwa-adi** [pyiron/pyiron_atomistics#649]
```python
from pyiron import Project
pr = Project("scratch")
job_lmp = pr.create.job.Lammps("SimpleLammps", delete_existing_job=True)
job_lmp.structure = pr.create.structure.bulk('Ni', cubic=True)
with job_lmp.interactive_open() as job:
    job.run()
```
**Summary**
This gives an error as "OSError: libyaml-cpp-pace.so.0.6: cannot open shared object file: No such file or directory" whereas it should run with a warning . However, if you comment out interactive_open() line i.e the second last line, it runs well. 

**pyiron Version and Platform**

TYPE = Postgres
HOST = <pyiron_db>
NAME = pyiron
USER = <my_username>
PASSWD = <my_password>
JOB_TABLE = jobs_cmmc
TOP_LEVEL_DIRS = /cmmc/u
VIEWERUSER = cmmc_view
VIEWERPASSWD = <my_viewer_password>
VIEWER_TABLE = jobs_cmmc_admin
RESOURCE_PATHS = /u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc 

Pyiron version 0.4.6 used from garching cluster.

**Comment by jan-janssen** [comment]
There was an issue with the Lammps version, @tnecnivkcots Can you revert the Lammps conda package? The version you want to use is: 
```
conda install lammps=2021.09.29
```

**Comment by jan-janssen** [comment]
@srmnitc Any update on the `pace` `yaml` issue?

**Comment by srmnitc** [comment]
@jan-janssen I have to ask yury to look into it. Otherwise, we have to simply turn off ML-PACE. I assume some progress will be made after the workshop is over.

**Comment by tnecnivkcots** [comment]
I will do the `conda install lammps=2021.09.29` after the conda environment is stable again. (see also https://github.com/pyiron/pyiron_atomistics/pull/612#issuecomment-1150766371)

**Comment by tnecnivkcots** [comment]
I run the command `conda install lammps=2021.09.29`. It will be available tomorrow.

**Comment by tnecnivkcots** [comment]
lammps is now installed with version 2021.09.29.

**Comment by Vishwa-adi** [comment]
> lammps is now installed with version 2021.09.29.


I ran the code again: 
This is the error which I got: 
AttributeError: LAMMPS Python module installed for LAMMPS version 20211027, but shared library is version 20210929

**Comment by pmrv** [comment]
I've double-checked that this works now after the latest update.  Have you restarted your notebook kernel in between?  I'm guessing what happened was:
1. @tnecnivkcots figured the conda confusion out and during that down graded pyiron_atomistics
2. you start working on this notebook
3. @tnecnivkcots then updated the environment, which included the lammps downgrade
4. you get the error above, because the process has been running since before the update

If restarted the kernel doesn't work, restart your whole server.

**Comment by Vishwa-adi** [comment]
> I've double-checked that this works now after the latest update. Have you restarted your notebook kernel in between? I'm guessing what happened was:
> 
>     1. @tnecnivkcots figured the conda confusion out and during that down graded pyiron_atomistics
> 
>     2. you start working on this notebook
> 
>     3. @tnecnivkcots then updated the environment, which included the lammps downgrade
> 
>     4. you get the error above, because the process has been running since before the update
> 
> 
> If restarted the kernel doesn't work, restart your whole server.

It works now. Thanks!
