### ISSUE TITLE
Parsing large lammps dummps leads to kerneal deaths

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron_atomistics#671]
**Summary**

When trying to parse some lammps dump files I encountered repeated kernel deaths of the jupyter notebook.
I assume the reason is that similar to the parsing of logfiles the dumpfile is read using readlines(), causing out of memory problems because the whole file, that can have the size of a few GB is read into memory as a whole, but the reason could also be different.

Solution is probably to read line by line and fill some buffer with the data, regularly writing to hdf5. But the same problem will probably occur when the job is reloaded from the hdf5 or is that handled somehow already?

**pyiron Version and Platform**

Latest versions, Linux

**Expected Behavior**

Working lammps parse

**Actual Behavior**

Dying Kernel

**Steps to Reproduce**

Try to parse a large lammps dump file.

**Comment by pmrv** [comment]
The diagnosis is correct.  The current lammps parser reads all lines in one go and then iterates over them.  I just never got around to properly do it.  We discussed some solutions already [here](https://github.com/pyiron/pyiron_atomistics/issues/324), including sketches how properly parse from me and iteratively write to HDF5 from @SanderBorgmans.

**Comment by Leimeroth** [comment]
From reading through it I assume we need some c/c++ based solution if we want to read files larger than ~1GB in reasonable time. But that would only solve the parsing, not the reloading from hdf5 part, which could actually be difficult again at least when using h5io instead of h5py directly. Maybe some lazy loading similar to what you did in the DataContainer could help on that end?

**Comment by pmrv** [comment]
@c/c++ I guess beating `np.loadtxt` will be hard in pure python, so it's something we should look into, though probably as a last resort.

EDIT: some discussion [here](https://stackoverflow.com/questions/52232559/numpy-loadtxt-is-way-slower-than-open-readlines).

@h5io Reading binary instead of text files should already mitigate the memory consumption issues to some extent, but I agree that midterm we'll have to drop h5io at least for accesses of large data.  Iirc h5py already does "lazy loading" in the sense that you can ask to load only slices of data from file.

**Comment by Leimeroth** [comment]
Something that could help with memory and probably would be faster because it does not require parsing to be done with python and not multiple list comprehensions:
```
dfs = []
with open("TestFile.txt") as f:
    for l in f:
        if l.startswith("Numbers:"):
            buf = io.StringIO()
            l = f.readline()
            while l.strip():
                buf.write(l)
                l = f.readline()

            buf.seek(0)
            dfs.append(pd.read_table(buf, nrows=3, sep=" ", header=None, engine="c"))
```
Data is directly stored in a dataframe, which could than be used for the mathematical operations necessary for unit conversion and coordinate system transformations.
This still does the reading of lines using python though, so there is probably some room for improvements
