### ISSUE TITLE
How to run SPHInX3.0.8 from pyiron

### ISSUE THREAD

**Issue by usaikia** [pyiron/pyiron_atomistics#682]
How to run SPHInX3.0.8 from pyiron? For a SPHInX job, I checked "job.executable.available_versions" and it is not added to the list of executables yet.

**Comment by pmrv** [comment]
Simply add a new script [here](https://github.com/eisenforschung/pyiron-resources-mpie/tree/master/sphinx/bin).  I've just checked the cluster module definitions and the default version 'latest' should already be 3.0.8.  So technically no change is required on your side, but I'd appreciate it if you could add scripts for the version that are available as modules on the cluster (run `module avail sphinx`), it should simple be copy&paste of the version numbers into the existing scripts.

**Comment by usaikia** [comment]
Thanks Marvin. I will add the scripts for all available sphinx modules. I just noticed that the script "run_sphinx_2.6.2_default.sh" actually load the sphinx module 2.7.1 (module load sphinx/2.7.1-noopenmp). Same for the script "run_sphinx_2.6.2_default_mpi.sh". Is it intentional or I should change it to the correct versions as well?

**Comment by niklassiemer** [comment]
Probably, someone updated the script without renaming it is as well (at least I would guess so).

**Comment by usaikia** [comment]
@niklassiemer Thanks. Then, I will change the names to the correct versions numbers.
