### ISSUE TITLE
Is it possible to know the normal of grain boundary plane with `Aimsgb`?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#691]
I am struggling with the fact that `pr.create.structure.aimsgb.build` creates grain boundaries, the normals of which show sometimes x-direction, sometimes y-direction and sometimes z-direction. For example, for `axis = [1, 1, 0]` and `sigma = 3`, the three possible GB (`planes = [[-1, 1, 1], [1, -1, 2], [1, 1, 0]]`) give all different grain boundary normals. Is there a possibility to know the direction of the normal from `pr.create.structure.aimsgb.info` or somehow specify which direction the normal should show?

**Comment by usaikia** [comment]
@samwaseda I couldn't found any option to control direction of the GB normal in Aimsgb (@liamhuber please correct me if I missed something). However, you can determine it from pr.create.structure.aimsgb.info

Here is a simple example:

```python
my_axis = [1, 1, 0]
info = pr.create.structure.aimsgb.info(axis=my_axis, max_sigma=3)

# select the sigma value and GB plane you are interested
my_sigma = 3 
my_plane = [1, 1, 0]

arr = np.array(info.get(my_sigma).get('plane'))
index = np.argwhere(np.all(arr==my_plane, axis=2))[0,1]
if index==0:
    print("direction normal to the GB plane is x")
elif index==1:
    print("direction normal to the GB plane is y")
else:
    print("direction normal to the GB plane is z")
```

EDIT: (ghost edit from @pmrv :P)

**Comment by usaikia** [comment]
sorry for the wrong indentations in the if statements. It changed when I post the comment.

**Comment by usaikia** [comment]
@pmrv Thanks :)

**Comment by samwaseda** [comment]
Ah that means the planes are always given in the oder of `x`, `y` and `z`? That would actually answer my question.

**Comment by samwaseda** [comment]
Ok I did a few test cases and it indeed looks like that. Thanks for your help!
