### ISSUE TITLE
Restarting SPHInX jobs from charge density doesn't take the appropriate structure.

### ISSUE THREAD

**Issue by skatnagallu** [pyiron/pyiron_atomistics#692]
When I restart SPHInX jobs from an aborted previous job, using `restart_from_charge_density`,  it does not take the appropriate structure. The new restarted job takes the starting structure of the previous job when in fact it should take the final structure from the previous job since there are multiple ionic steps.

I guess the problem is in pyiorn_atomistics.sphinx.base.py,
``` python
    def restart(
        self,
        job_name=None,
        job_type=None,
        from_charge_density=True,
        from_wave_functions=True,
    ):
        ....
        new_job = super(SphinxBase, self).restart(job_name=job_name, job_type=job_type)
        new_job.input = self.input.copy() 
```

I think the last line `new_job.input = self.input.copy() `  in the above code snippet, overwrites the final structure (which it got from `AtomisticGenericJob.restart()`) with the initial structure in the old job's input. A simple fix would be to remove the last line, as the restart method from GenericJob class should already have copied the input.

**Comment by samwaseda** [comment]
I just gave it a try and it looks like `restart` is taking indeed the final positions:

```python
pr = Project('SPX_RESTART')
spx = pr.create.job.Sphinx('spx')
spx.structure = pr.create.structure.bulk('Al', cubic=True).repeat(2)
del spx.structure[0]
spx.calc_minimize()
spx.run()
spx_restart = spx.restart()
print(np.linalg.norm(spx_restart.structure.positions - spx.get_structure().positions))
print(np.linalg.norm(spx_restart.structure.positions - spx.structure.positions))
```

Output
```
0
0.10557152115500801
```

**Comment by skatnagallu** [comment]
You are right. This seems to be working. Somehow for my previous jobs, it did not. Probably it is something I did. I will close this.
