### ISSUE TITLE
sphinx potential tests are resource dependent

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_atomistics#695]
I fear these tests strongly depend on the current settings in the resources -  Am I right?
https://github.com/pyiron/pyiron_atomistics/blob/dd6266b95ed107d51328de77cba500451af455d0/tests/sphinx/test_base.py#L115-L122
On the cluster they fail since 
```python-traceback
AssertionError: Lists differ: ['Fe_GGA'] != ['Fe', 'Fe_GW', 'Fe_pv', 'Fe_sv', 'Fe_sv_GW']
```

**Comment by samwaseda** [comment]
aaaah I knew that someone would notice it at some point

**Comment by samwaseda** [comment]
I would simply remove this test, because it makes little sense. What do you think?

**Comment by niklassiemer** [comment]
No, I would leave it in. I am just wondering where we install these resources xD 
We should either document that better or have a trimmed down test resource attached to the repo to make the tests running everywhere.

**Comment by jan-janssen** [comment]
You can find the resources in https://github.com/pyiron/pyiron_atomistics/tree/master/tests/static and they are installed in https://github.com/pyiron/pyiron_atomistics/blob/master/.github/workflows/unittests.yml#L39 `python .ci_support/pyironconfig.py`
