### ISSUE TITLE
-partition possible?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#75]
On [this page](https://github.com/lammps/lammps/blob/master/examples/prd/in.prd), there's an example for Parallel Replica Dynamics with LAMMPS. Here, I see the command:

```
mpirun -np 4 lmp_g++ -partition 4x1 -in in.prd
```

I wonder whether `-partition` is available in pyiron. This should be analogous to NEB. If not, is there a good way to incorporate it?

**Comment by jan-janssen** [comment]
Not yet, but you can we can add a separate executable script.

**Comment by samwaseda** [comment]
Hm ok thanks

**Comment by jan-janssen** [comment]
I would create a separate shell script. And then in the shell script use the thread variable `$2` to split the partition. It is a hack but it should work for now.
