### ISSUE TITLE
Constrained cell relaxation in vasp

### ISSUE THREAD

**Issue by jyang2009** [pyiron/pyiron_atomistics#760]
Dear all,

I'm trying to run some interface calculations with vasp and I'm wondering if it is possible to fix the lattice parameters in xy direction and allow the z direction to relax from pyiron. My previous experience is that one need to change the file constr_cell_relax.F and recomiple vasp to do this. Is there such a version already complied on cmti cluster? Please let me know. Thanks a lot.

Best,
Jing

**Comment by pmrv** [comment]
I have a work in progress job for this [here](https://github.com/pyiron/pyiron_atomistics/pull/636).  It works with VASP jobs without problems, but it's not merged because of other technical reasons.

**Comment by jyang2009** [comment]
Dear Marvin,

Does this only work with the Murnaghan job type or does it also work with the vasp job type? Could you please give a short example of how this version could be used? Thanks a lot. 

Best,
Jing

**Comment by pmrv** [comment]
The Murnaghan job works with any atomistic job including VASP.  There should some examples in the handbook distributed on the cluster.  The use case that you need is depending on the PR I linked.  I'll see if I can get it in by tomorrow.

**Comment by pmrv** [comment]
Pending on #775.

**Comment by pmrv** [comment]
@jyang2009, #636 is merged, so after the next update on the cluster (~Tuesday) you can use the `Murnaghan` job together with a vasp one.  There's an example [here](https://github.com/pyiron/pyiron_atomistics/blob/master/notebooks/energy_volume_curve.ipynb) (replace `Gpaw` by `Vasp`).  Once the update is in the murnaghan job will have an additional input `axes`, which you can set to a list like `['x', 'y']` to allow only relaxation in x and y directions.

**Comment by jyang2009** [comment]
Thanks, Marvin! I will check it out. 

Best,
Jing
