### ISSUE TITLE
restart from a existing pyiron job by using the same job_name?

### ISSUE THREAD

**Issue by appassionate** [pyiron/pyiron_atomistics#761]
Summary
Hi,
maybe some restart job by the same job_name will be helpful for condition handling of calculation tasks

Detailed Description
In DFT calculation, it is common that a traditional HPC job hit the walltime and the calculation stopped when actually not satisfy our expect, i guess... Usually, in no pyiron calculation process, we just edit the INCAR or other software input to restart the task in the current dir.
Pyiron does have some 'restart' feature for it, but it seems to be create a new job. it will lead to a analysis burden in my cases. such OUTCAR_1, OUTCAR_2 ,... OUTCAR_N will be hard to collect to do some advanced analysis. So, if we can do some implements for 'recovering from a existing job', there wil be only one OUTCARS and some 'ancient' analysis script will be quickly ultilized for me :P.

I' d like to develop some method (maybe some hacking in job)... Some points might be considered in the following, i guess...

    'restart_file_list' might have some default value for some job type
    'input file editing' action will be performed in a special type job to trans the init input to a 'restart input' i guess? and then, how to consider the SomeTypeJob.input param will be a problem.
    how to update the existing job record in database such as cpu time or others?

Any suggestions will be helpful for me, thks.

Further Information, Files, and Links

EDIT: I accidentally edited this message instead of reply, so I've copied the notification text over.  Hope your message didn't get lost, @pmrv

**Comment by samwaseda** [comment]
One thing you might be interested to use could be something like:

```python
job_name = old_job.job_name
old_job.job_name = job_name + '_old'
new_job = old_job.restart(job_name=job_name)
```

This allows you to create a new job with the same name. Of course behind the scenes the directory's name of the job will be modified as well.

Otherwise I'm not really sure what you mean by "recovering from a existing job". Could you elaborate on it?

**Comment by pmrv** [comment]
>  Pyiron does have some 'restart' feature for it, but it seems to be create a new job. it will lead to a analysis burden in my cases. such OUTCAR_1, OUTCAR_2 ,... OUTCAR_N will be hard to collect to do some advanced analysis. 

Can I ask what makes it burdensome?  Maybe there is something else we can fix.  If you analyze your results with pyiron tables, aborted jobs are automatically skipped, so your analysis would go only over the correct (-ly restarted) jobs.  Which is presumably what you want.  If you are iterating over jobs manually for some reason, be aware that you can filter jobs, e.g.

```python
for j in pr.iter_jobs(status='finished'):
   ... # goes over finished jobs

for j in pr.iter_jobs(status='finished', convert_to_object=False):
   some_manual_analysis(j.working_directory) # calls the function on working directory of each finished job

df = pr.job_table(status='!finished')
for job_id in df.id:
   ... # do something with jobs that have not finished
```

**Comment by appassionate** [comment]
@samwaseda @pmrv 
Many thanks for your very kind suggestions! I believe "iter_jobs" will be a very useful method for me for batch analysis.
Actually im considering some implements in MD calculations, which always cost a lot of time unlike structure optimization or others. Also, i tried to implements the interface of cp2k, which i called "cp2kjob" derived from the outstanding design of atomisticjobs to do the MD task in the pyiron way.
we will do some analysis about the complete trajectory but not the traj_restart_0, traj_restart_1 combinations.

MD task will not be finished in the queue manager such as slurm or lsf in lammps(job) or my "cp2kjob" when hit the walltime.
In lammps, after lammps_restart editing, if u try to "restart the job in the same directory", which means restart the same pyironic job, the result will be overwritted i guess...  A new_job has to be created, and pyiron can restart this situation very well.
https://matsci.org/t/appending-colvars-output-to-file/33168

However, cp2k restart allows us to restart the calculation in the same directory. you can just edit the input settings about "EXT_RESTART_FILE", and the result about ener and positions will not be overwritted.
some the hacking way will be like:  to refresh the exsiting job status, and submit to the queue. More details should be considered.
```python
def retry_job(job, use_wfn=True):
    
    # update database
    job.status._reset()
    job._status._status_dict["initialized"] = True
    job.status.database.set_job_status(job.job_id, 'created')
   
    #some way to add the cp2kjob input EXT_RESTART_FILE settings
    #balabala
    return job

job = retry_job(a_cp2k_job)
job.server.queue = "our-hpc-queue"
job.run()
```



Anyway thanks, I wish i have explained the situation well. : )

**Comment by pmrv** [comment]
Just as an aside @jan-janssen prepared an initial wrapping for cp2k already [here](https://github.com/pyiron/pyiron_contrib/pull/286), that might be useful for you to extend.

**Comment by appassionate** [comment]
> Just as an aside @jan-janssen prepared an initial wrapping for cp2k already [here](https://github.com/pyiron/pyiron_contrib/pull/286), that might be useful for you to extend.

Hi @pmrv. Inspired by [first_draft_cp2k_interface](https://github.com/pyiron/pyiron_contrib/pull/286) by @jan-janssen , I have developed some simple implementation in cp2k, [pyiron_ecbeta](https://github.com/appassionate/pyiron_ecbeta), thanks to the good design of pyiron_atomistics! Sorry, maybe i am not a "qualified" developer, but such a cp2k interface is helpful for me.
And, the restart  implements of cp2kjob is in [retry_cp2k_job](https://github.com/appassionate/pyiron_ecbeta/blob/main/pyiron_echem/utils.py).  It might be just suitable for me, or someone is interested in.

Now, i think "restart from an existing pyiron job" need a more complete restart mechanism by the simulation software but not the pyiron, cp2k can do that in some way, but lammps and vasp means to create a new job, (Sorry ,having no experience with other simulation software). 

thanks.
