### ISSUE TITLE
Confusing warning messages for primitive cell generation

### ISSUE THREAD

**Issue by ahmedabdelkawy** [pyiron/pyiron_atomistics#763]
**Summary**

- Using `structure.get_symmetry().primitive_cell` gives the following warning and recommends using `structure.get_primitive_cell(standardize=False)`:
pyiron_atomistics.atomistics.structure.symmetry.primitive_cell is deprecated: Use `get_primitive_cell(standardize=False)` instead. Which fails, because standardize is not a keyword argument

- However, using `structure.get_primitive_cell()` without standardize keyword gives the following deprecation warning and recommends using the previous method `structure.get_symmetry().primitive_cell`:
pyiron.atomistics.structure.atoms.get_primitive_cell is deprecated: Use `structure.get_symmetry().primitive_cell` instead

**Expected Behavior**

One of them should be without warning!

**Actual Behavior**

Both give a Deprecation Warning!

**Steps to Reproduce**
`from pyiron.project import Project`
`pr = Project('primitive_cell_bug')`
`structure = pr.create.structure.bulk('NaCl', crystalstructure='rocksalt', a=5.63, cubic=True)`
`structure_prim_1 = structure.get_symmetry().primitive_cell`
`structure_prim_2 = structure.get_primitive_cell()`

**Comment by niklassiemer** [comment]
Thanks for the detailed issue!
> **Summary**
> 
> * Using `structure.get_symmetry().primitive_cell` gives the following warning and recommends using `structure.get_primitive_cell(standardize=False)`:

It actually recommends using `structure.get_symmetry().get_primitive_cell(standardize=False)` which works as expected. The `Symmetry` class returned by `structure.get_symmetry()` is emitting this warning. However, I absolutely agree that this is somewhat misleading!
>   pyiron_atomistics.atomistics.structure.symmetry.primitive_cell is deprecated: Use `get_primitive_cell(standardize=False)` instead. Which fails, because standardize is not a keyword argument
> * However, using `structure.get_primitive_cell()` without standardize keyword gives the following deprecation warning and recommends using the previous method `structure.get_symmetry().primitive_cell`:
>   pyiron.atomistics.structure.atoms.get_primitive_cell is deprecated: Use `structure.get_symmetry().primitive_cell` instead
> 
Yes, here the deprecation warning was not updated. Done in #762 
> **Expected Behavior**
> 
> One of them should be without warning!
> 
> **Actual Behavior**
> 
> Both give a Deprecation Warning!
> 
> **Steps to Reproduce** `from pyiron.project import Project` `pr = Project('primitive_cell_bug')` `structure = pr.create.structure.bulk('NaCl', crystalstructure='rocksalt', a=5.63, cubic=True)` `structure_prim_1 = structure.get_symmetry().primitive_cell` `structure_prim_2 = structure.get_primitive_cell()`

**Comment by ahmedabdelkawy** [comment]
Thank you very much, Niklas!
