### ISSUE TITLE
`ModuleNotFoundError: No module named 'mp_api'`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#771]
https://github.com/pyiron/pyiron_atomistics/blob/58947bb1978d66e59e646cdd96f8dfd9e514f970/pyiron_atomistics/atomistics/structure/factories/materialsproject.py#L2

Our resource problem?

**Comment by pmrv** [comment]
Did you pull master yourself?  I would guess @tnecnivkcots hasn't updated the global conda env yet.

Quick fix `pip install --user mp_api`, then once the global env is updated remove it again.

**Comment by niklassiemer** [comment]
Actually, since this is not yet released, this is not on the cluster, yet. However, I can install the package tomorrow :)

**Comment by liamhuber** [comment]
> Quick fix `pip install --user mp_api`, then once the global env is updated remove it again.

It's also available via conda if you have a local version of that or are using HEAD on your home machine

**Comment by tnecnivkcots** [comment]
> 

Conda Update on the cluster was done yesterday at about 11 am.

**Comment by jan-janssen** [comment]
@tnecnivkcots Did you install `mp-api` ? This is a new dependency we added in https://github.com/pyiron/pyiron_atomistics/pull/757 which was not yet included in the current release of `0.2.56`.

**Comment by niklassiemer** [comment]
I just read in the https://github.com/conda-forge/staged-recipes/pull/20471 that one dependency of `mp-api` is not available on windows! Can we use the `ImportAlarm` for the `mp-api` to avoid excluding windows user from updates?

**Comment by niklassiemer** [comment]
FYI - conda/mamba do not seem to find the `mp-mpi` package out of the box right now?! I had to first install `emmet-api` (which was added to conda-forge in the same PR) to then install `mp-mpi`

**Comment by jan-janssen** [comment]
it is `mp-api` rather than `mp-mpi` does this help?

**Comment by niklassiemer** [comment]
at least `mamba search mp-api` gives some results on the cluster! Probably, I just had that typo trying to install it directly and not a typo after I installed `emmet-api`... Thanks for pointing this out again...!

**Comment by pmrv** [comment]
> I just read in the [conda-forge/staged-recipes#20471](https://github.com/conda-forge/staged-recipes/pull/20471) that one dependency of `mp-api` is not available on windows! Can we use the `ImportAlarm` for the `mp-api` to avoid excluding windows user from updates?

Make it an issue and I can do it next week after vacation.

**Comment by niklassiemer** [comment]
The `mp-api` package is now installed on the cluster
