### ISSUE TITLE
GPAW: Needs separate environment variable

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_atomistics#774]
Right now on our cluster, if one tries to run a gpaw calculation it fails because the `GPAW_SETUP_PATH` environment variable is not set.  I guess we should set this variable to `/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/share/gpaw` in the pyiron module definition (that is the cluster module shell file).

**Comment by jan-janssen** [comment]
This should be set automatically when you call `condo activate` https://github.com/conda-forge/gpaw-feedstock/blob/main/recipe/activate.sh

**Comment by niklassiemer** [comment]
It should currently also be already set by `module load pyiron/dev` at least such a variable is set there (see `module show pyiron/dev`).

**Comment by pmrv** [comment]
Can someone double check on their setup?  At least for me it does not work.

**Comment by jan-janssen** [comment]
Does the `module load pyiron/dev` internally call `conda activate`? or does it only set the `PATH` variable?

**Comment by niklassiemer** [comment]
It only sets paths and environment variables, however, this is similar to what conda does on the conda-init step. And also I do not have to do anything else to use `conda update` for the environment. Of course some things might not be set correctly?

`module show pyiron/dev` results in 
```
prepend-path    PATH /u/system/SLES12/soft/pyiron/dev/anaconda3//bin
setenv          ANACONDA_HOME /u/system/SLES12/soft/pyiron/dev/anaconda3/
setenv          ANACONDA_ROOT /u/system/SLES12/soft/pyiron/dev/anaconda3/
setenv          CONDA_PREFIX /u/system/SLES12/soft/pyiron/dev/anaconda3/
setenv          HDF5_DISABLE_VERSION_CHECK 1
setenv          GPAW_SETUP_PATH /u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/gpaw/potentials/gpaw-setups-0.9.20000
prepend-path    PYTHONPATH /u/system/SLES12/soft/pyiron/dev/pyiron_backwards
prepend-path    PYTHONPATH /u/system/SLES12/soft/pyiron/dev/pyiron_mpie
prepend-path    PYTHONPATH /u/system/SLES12/soft/pyiron/dev/pyiron_mpie/pyiron
```

**Comment by niklassiemer** [comment]
However, the path set by conda activate `GPAW_SETUP_PATH="${CONDA_PREFIX}/share/gpaw"` from https://github.com/conda-forge/gpaw-feedstock/blob/main/recipe/activate.sh resolves to 
`/u/system/SLES12/soft/pyiron/dev/anaconda3/share/gpaw` and this is different from the path we set explicitly `/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/gpaw/potentials/gpaw-setups-0.9.20000`...

**Comment by pmrv** [comment]
> However, the path set by conda activate `GPAW_SETUP_PATH="${CONDA_PREFIX}/share/gpaw"` from https://github.com/conda-forge/gpaw-feedstock/blob/main/recipe/activate.sh resolves to `/u/system/SLES12/soft/pyiron/dev/anaconda3/share/gpaw` and this is different from the path we set explicitly `/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/gpaw/potentials/gpaw-setups-0.9.20000`...

That's the issue then, when I set it to the first path manually it works.

**Comment by niklassiemer** [comment]
I will try to update the module then

**Comment by niklassiemer** [comment]
@jan-janssen the module file is after all yours 😆 Could you change the group to pyiron and grant the group write access? If you want, you could also directly modify the GPAW setup to `setenv GPAW_SETUP_PATH $DIRECTORY/share/gpaw`.

**Comment by jan-janssen** [comment]
> @jan-janssen the module file is after all yours 😆 Could you change the group to pyiron and grant the group write access? If you want, you could also directly modify the GPAW setup to `setenv GPAW_SETUP_PATH $DIRECTORY/share/gpaw`.

Maybe it makes more sense to ask @freyso to transfer the ownership to @tnecnivkcots as I am currently at the lab and only have access to the cluster again in ~8h.

**Comment by niklassiemer** [comment]
I fear we would need to open a ticket for this... And it is not time critical xD

**Comment by tnecnivkcots** [comment]
> I fear we would need to open a ticket for this... And it is not time critical xD

One option is to transfer the ownership to me. For that it is neccessary to open a MPCDF ticket.
Maybe it could even better to transfer the ownership to pyironhb.

**Comment by jan-janssen** [comment]
I updated the module file in `/cmmc/system_sle15_sp1/modules.addon/CMMC/pyiron/dev` to: 
```
# GPAW setup 
setenv GPAW_SETUP_PATH $PYIRONPATH/dev/anaconda3/share/gpaw
```
Still I am not sure if that is the right way to do it, as before we had to place the module files somewhere else and then they were copied once per day. I thought these details were included in the documentation for the administration of the cmti cluster - or at least they should be. 

@tnecnivkcots What is your username on the cluster, then I can transfer the permission to you?

**Comment by pmrv** [comment]
@jan-janssen thanks for doing the update!  Changes to the module files should be live immediately, so I'm assuming it works now.

**Comment by tnecnivkcots** [comment]
@jan-janssen Do you still need my username?
It is vistock.
