### ISSUE TITLE
ImportAlarm for `mp-api` instead of direct dependency?!

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_atomistics#780]
Currently, the `mp-api` package does not work on windows due to a missing dependency. It would be great to have this as an opt-in feature. However, pymatgen is now also using the `mp-api` package (https://github.com/pyiron/pyiron_atomistics/pull/779) and sooner or later there has to be a solution to import the package on windows as well.

**Comment by jan-janssen** [comment]
for reference https://github.com/pyiron/pyiron_atomistics/issues/771

**Comment by jan-janssen** [comment]
> Currently, the `mp-api` package does not work on windows due to a missing dependency. 

This is wrong - `mp-api` is working for windows - otherwise our tests in https://github.com/pyiron/pyiron_atomistics/pull/757 would have failed.
