### ISSUE TITLE
Selective dynamics in some directions of a VASP POSCAR in ASE Atoms is not supported (pymatgen Structure -> Atoms converter) pymatgen_to_pyiron(structure)

### ISSUE THREAD

**Issue by ligerzero-ai** [pyiron/pyiron_atomistics#786]
Trying to set limited degrees of freedom is not supported in the ASE atoms object (e.g. Selective Dynamics with [ T T F ])

**Expected behaviour:**

It should accept this! Otherwise jobs with relaxations only in certain ionic directions is forbidden and kills entire workflows.

**To reproduce:**

```
import numpy as np
import os; import shutil
import pandas as pd

from pymatgen.io.vasp.inputs import Potcar, Incar, Kpoints
from pymatgen.core import Structure
from pymatgen.core.lattice import Lattice
from pymatgen.io.ase import AseAtomsAdaptor
import pymatgen.core.structure
from pymatgen.core.operations import SymmOp

from ase.lattice.cubic import FaceCenteredCubic as fcc
from ase.lattice.cubic import BodyCenteredCubic as bcc
from ase.build import stack, add_vacuum, fcc111, surface, bulk
from ase import build as build

from pyiron.project import Project
import pyiron.atomistics.structure.atoms as pi_atoms

Bulk = build.bulk('Ni', 'fcc', a = 3.518, cubic = True)
struct = AseAtomsAdaptor.get_structure(Bulk)
sd_list = [[False, False, True] for x in struct]
# Update the site dynamics list into the new siteproperties object
new_sp = struct.site_properties
new_sp['selective_dynamics'] = sd_list
# Apply the new site properties into the new structure
struct = struct.copy(site_properties = new_sp)
job = pr.create_job(job_type=pr.job_type.Vasp, job_name='SELECTIVEDYNAMICSDOESNTWORK')
job.structure = pi_atoms.pymatgen_to_pyiron(struct_adj)
```

yields
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_6296/3826973976.py in <cell line: 11>()
      9 struct = struct.copy(site_properties = new_sp)
     10 job = pr.create_job(job_type=pr.job_type.Vasp, job_name='SELECTIVEDYNAMICSDOESNTWORK')
---> 11 job.structure = pi_atoms.pymatgen_to_pyiron(struct_adj)

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_atomistics/atomistics/structure/atoms.py in pymatgen_to_pyiron(pymatgen_obj)
   3213         pyiron atoms object
   3214     """
-> 3215     return ase_to_pyiron(AseAtomsAdaptor().get_atoms(structure=pymatgen_obj))
   3216 
   3217 

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pymatgen/io/ase.py in get_atoms(structure, **kwargs)
    112                 site_prop = site.properties["selective_dynamics"]
    113                 if site_prop not in [[True, True, True], [False, False, False]]:
--> 114                     raise ValueError(
    115                         "ASE FixAtoms constraint does not support selective dynamics in only some dimensions."
    116                         "Remove the selective dynamics and try again if you do not need them."

ValueError: ASE FixAtoms constraint does not support selective dynamics in only some dimensions.Remove the selective dynamics and try again if you do not need them
```

**To fix:**

I have no idea, since this is inherited from ASE (?). Is it possible to wrangle the job.structure object to accept a pymatgen writer?

I have no issues writing the POSCAR using pymatgen.

**Comment by pmrv** [comment]
That is a bug on pymatgen's side, right?  Our subclass of `Atoms` allows specifying direction dependent constraints like this

```python
structure = pr.create.structure.bulk('Fe')
structure.add_tag(selective_dynamics=[True, True, True])
structure.selective_dynamics[0] = [False, True, False]
```

Is there a reason you need pymatgen and ase specific creation routines?  Our standard is always that users do not need to touch anything outside pyiron, so if you think there's anything missing for your work, we should wrap it.

FYI: You can convert from pymatgen/ase structure objects more conveniently with `pr.create.structure.from_{ase,pymatgen}`.

**Comment by ligerzero-ai** [comment]
Thanks, I am using pymatgen just out of habit - I didn't think that it would be an issue to convert structures to atoms objects to feed into pyiron. 

There are some features in ASE that I like, and some features in pymatgen that I like, so I swap between them often.

For example, I can build GBs using ASE's stack function, using two slabs with specified directions, which is nice and tidy, compared to the unwieldy way of trying to do it in pymatgen. ( at least I haven't found a better way of generating slabs in pymatgen's SlabGenerator and then a whole bunch of other complex classes, e.g. GrainBoundaryGenerator ).

But I also use pymatgen as there are some really useful classes and modules for some niche applications (finding non-orthogonal GBs for minimising supercell size, voronoi interstitial algorithms, parsers for external codes etc.)

What I find confusing is the recommendation to interact with pyiron for the creation routines? Isn't that just a lot of extra work and overhead for what is essentially a solved (or at least somebody else's (ASE, pymatgen)) problem? For example, there is tons of google-able documentation for how to create specific structures using ASE or pymatgen, but comparably almost nothing for (wrapped) pyiron.

Unless there is a truly herculean effort to overhaul, wrap and maintain documentation for creation routines in pyiron (e.g. How-to), I can't see that the community will stop using external tools for creation routines simply because it is recommended by the devs. It's just harder to interact with the creation routines in pyiron compared to pymatgen/ASE. The alternative is simply the path of least resistance.

**Comment by pmrv** [comment]
> For example, I can build GBs using ASE's stack function, using two slabs with specified directions, which is nice and tidy, compared to the unwieldy way of trying to do it in pymatgen. ( at least I haven't found a better way of generating slabs in pymatgen's SlabGenerator and then a whole bunch of other complex classes, e.g. GrainBoundaryGenerator ).

This we can actually do already, `pr.create.structure.ase.stack` and friends. (Also ASE's modification routines should work with our structures natively, being a subclass)

> But I also use pymatgen as there are some really useful classes and modules for some niche applications (finding non-orthogonal GBs for minimising supercell size, voronoi interstitial algorithms, parsers for external codes etc.)

Fair, that's why we have the conversion functions.

> What I find confusing is the recommendation to interact with pyiron for the creation routines? Isn't that just a lot of extra work and overhead for what is essentially a solved (or at least somebody else's (ASE, pymatgen)) problem? For example, there is tons of google-able documentation for how to create specific structures using ASE or pymatgen, but comparably almost nothing for (wrapped) pyiron.
> 
> Unless there is a truly herculean effort to overhaul, wrap and maintain documentation for creation routines in pyiron (e.g. How-to), I can't see that the community will stop using external tools for creation routines simply because it is recommended by the devs. It's just harder to interact with the creation routines in pyiron compared to pymatgen/ASE. The alternative is simply the path of least resistance.

I would say it's less effort than you make it sound.  We only aim to offer a compatible interface to the same functions so that users do not need to manually convert the structure classes.  This is fairly low effort with the wrappers that we have (see the decorators that we use in the `AseFactory`).


On a more practical note, I see now that the issue is that to convert from pymatgen we first convert to ase and then to us.  The easy solution for you would then be to add a few lines to our `pymatgen_to_pyiron` function (and the converse) that saves selective dynamics tags and restores them manually after calling pymatgen's `AseAdapter`.
