### ISSUE TITLE
Sphinx Output not readable from inspect mode

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_atomistics#798]
Ever since #505 the generic output of sphinx jobs is no longer accessible from inspected jobs, because of the change to store the output in a `DataContainer`.  Long term I think the solution should be change the `DataContainer` HDF layout to not do any mangling of the names.  I don't know when I'll get around to that though.  Any ideas for a short term fix, @samwaseda ?

**Comment by samwaseda** [comment]
I think the best would be to make `inspect` compatible with `DataContainer`. What do you think?

**Comment by pmrv** [comment]
This still breaks Murnaghan job with sphinx, btw.

**Comment by samwaseda** [comment]
Wasn't this problem solved?

**Comment by pmrv** [comment]
Eh, should. Let me check in a bit.

**Comment by pmrv** [comment]
Works now.
