### ISSUE TITLE
how to run external executable in pyiron

### ISSUE THREAD

**Issue by usaikia** [pyiron/pyiron_atomistics#818]
I compiled a MEAMfit executable inside the directory "/cmmc/u/usaikia/apps/MEAMfit2/src"
Next I created a file name "run_MEAMfit.sh" and write the following line inside this file:
exec /cmmc/u/usaikia/apps/MEAMfit2/src/MEAMfit

In the pyiron job (pr.create.job.MeamFit("test") ) I assigned the executable as:
job.executable = "/cmmc/u/usaikia/apps/MEAMfit2/src/run_MEAMfit.sh"

When I run the job (job.run()) without job.server.queue = "s_cmfe" it is running fine. But if I assign the queue, it fails to run and complain about "executable is not assigned or not found".

Is there any way to solve this problem?

**Comment by jan-janssen** [comment]
For pyiron to find the executable you should store the `run_meamfit.sh` script in your resource path, which is defined in your `~/.pyiron` config. In the resource directory your should create the subfolders `meamfit/bin` and then in `bin` place your script `run_meanfit_2.0.sh`. If you want to run with multiple cores you also need to add an mpi enabled version `run_meamfit_2.0_mpi.sh`.

**Comment by usaikia** [comment]
Resource path defined in my ~/.pyiron is: /u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc 
But I don't have permission to create folder in that directory. Also, to use meamfit each user need permission separately from the developer. Hence, I installed it locally inside my user home directory.  It seems to work fine when I am running directly in the login node using pyiron. I am facing problem only when I tried to run the job in queue. So, if I ask any privileged user to create the meamfit/bin folder and put the run_meanfit_2.0.sh script there will it work (although my code is installed inside my home directory)?

**Comment by jan-janssen** [comment]
You can simply add an additional resource path in your home directory, the `.pyiron` configuration supports multiple resource paths.

**Comment by pmrv** [comment]
I guess I forgot to add a meamfit script to our resources when we merged the Meamfit job in contrib.  @usaikia once you have a working script can you create a PR in our [resources repo](https://github.com/eisenforschung/pyiron-resources-mpie)?

**Comment by usaikia** [comment]
> You can simply add an additional resource path in your home directory, the `.pyiron` configuration supports multiple resource paths.

@jan-janssen Thanks a lot for solution.

**Comment by usaikia** [comment]
> I guess I forgot to add a meamfit script to our resources when we merged the Meamfit job in contrib. @usaikia once you have a working script can you create a PR in our [resources repo](https://github.com/eisenforschung/pyiron-resources-mpie)?

@pmrv sure, I will do that.

**Comment by samwaseda** [comment]
Has this been solved?

**Comment by usaikia** [comment]
Yes, It is solved.
