### ISSUE TITLE
How to re-generate the output using updated Output parsers so that job["output/generic/dft/..."]  is updated for a job.

### ISSUE THREAD

**Issue by ligerzero-ai** [pyiron/pyiron_atomistics#824]
I'm currently trying to debug my draft implementation of the sorting behaviour removal #799 , currently trying to validate output parsing for VASP.

Can someone tell me what I need to do to re-read the output so that:
```
pr = Project("test_module_idx_map_2")

job_nosort = pr.load("forbidden")
job_nosort["output/generic/dft/final_magmoms"]
```
`job_nosort["output/generic/dft/final_magmoms"]` is re-generated/refreshed using an updated version of the output readers? Is the stuff in square brackets just reading from a stored HDF file?

I am not sure how to achieve this. I see that job_nosort.reset_output() exists, but not sure if it is doing something intended because I can see that I am still getting the same result for the above line which is not expected behaviour (I think)

**Comment by pmrv** [comment]
Yep, square brackets just access parsed data and files.

I guess the hacky way is

```python
job.status.collect = True
job.run()
```

Not sure if that will error when there is already output inside the HDF.  In that case

```python
job.project_hdf5['output'].remove_group()
```

before the stuff above could work.

**Comment by ligerzero-ai** [comment]
I see, thanks, great it works. This is really useful to me because I would like to avoid having to rerun the job every single time I change something in the output parsing for validation and testing.
```
job.status.collect = True
job.run()
```
It returns a message like "The files are already compressed!" in the notebook, but calling `job_nosort["output/generic/dft/final_magmoms"]` again shows that it has changed from the original output. I'm guessing that it works! (?) I'll come back if anything weird happens.

**Comment by pmrv** [comment]
You might have to do `job.decompress()` first.  Successful jobs are automatically tar'ed but the logic around it is a bit weird.

**Comment by ligerzero-ai** [comment]
ah, I had decompressed them manually, so maybe that's why it worked? I had both the tarball and the raw output files present. Maybe it's detecting if there's a tarball in the folder. Maybe it breaks when they're not. I'll test that later. For now, I'm happy that this works.
