### ISSUE TITLE
cache speed up test failing.

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#830]
https://github.com/pyiron/pyiron_atomistics/blob/2fe894a5100022ab2662198d8362977992edf193/test_benchmarks/atomistics/structure/test_atoms.py#L47

In [this PR](https://github.com/pyiron/pyiron_atomistics/pull/588), the unit test above is failing, but it's totally unrelated to my PR. Is there something I missed? @niklassiemer

**Comment by niklassiemer** [comment]
The benchmark tests are prone to fail. Probably due to different load of the servers for the execution? For that reason we separated them from the other unit tests. Just rerun the failed tests (like I did now) and we have a closer look if it stays failing :)
