### ISSUE TITLE
Tag not a release?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_atomistics#85]
pyiron_contrib [requires pyiron_atomistics=0.2.3](https://github.com/pyiron/pyiron_contrib/blob/master/.ci_support/environment.yml), but although we have an 0.2.3 tag [0.2.2 is showing as the latest release](https://github.com/pyiron/pyiron_atomistics/releases/tag/pyiron_atomistics-0.2.2). I think pushing the new release is probably preferable to downgrading the contrib dependency, so I'm posting here.

**Comment by liamhuber** [comment]
I can't remember who on the dev-dev team was handling releases now, so I just assign all three, sorry to whoever was not touching this ;)

**Comment by jan-janssen** [comment]
For creating a pip package we only need a Git tag and that is the one we reference in the setup.py and which is also used for the conda package. @niklassiemer in addition created GitHub releases

**Comment by liamhuber** [comment]
Somehow `conda update pyiron_contrib` is still stuck at 0.2.2. I should have dug deeper though as you are, of course, absolutely right and 0.2.3 is showing up on conda and in my pycharm package manager. I'm still having trouble getting it installed, but I think that's just on my end.
