### ISSUE TITLE
stop vasp job during the run

### ISSUE THREAD

**Issue by jyang2009** [pyiron/pyiron_atomistics#867]
Dear all,

I would like to know if it is possible to stop a vasp job during the run via pyiron (same as creating a STOPCAR file). Please let me know. Thanks a lot.

Best,
Jing

**Comment by pmrv** [comment]
It's being worked on [here](https://github.com/pyiron/pyiron_base/pull/875).  Until that is in, I would guess

```python
!touch {job.working_directory}/STOPCAR
```

in a notebook cell will do the trick.

**Comment by jyang2009** [comment]
Got it. Thanks a lot, Marvin!

**Comment by ligerzero-ai** [comment]
@jyang2009 actually I found `job.stop_calculation(next_electronic_step=False)` for vasp already implemented.
