### ISSUE TITLE
Warning when expected memory potentially too large

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#87]
It occurred to me several times that I submit a LAMMPS job for a relatively large structure with a relatively large number of steps and I surpass the memory limit. In the case of MPIE cluster, this forces all simulations to stop since there wouldn't be any update to the output anymore. This problem is mostly avoided in the traditional LAMMPS calculations, because there we have to specify the frequency of output, which in pyiron we don't have to. I think it makes sense to issue a warning if the number of data points to collect times the number of atoms becomes larger than a certain value. What do you guys think?

**Comment by liamhuber** [comment]
I don't have any objection to the idea but I would want to be careful that the implementation is (a) actually useful and (b) doesn't clutter the code too much.

For (a) my main concern is specifying how much warrants a a warning? I guess this would need to be stored in the .pyiron config file? I suppose it should be possible to accurately map size*steps/print_period to get a memory estimate, but I wouldn't know the details.

(b) is just making sure it's a tidy decorator on the relevant methods or something and not a bunch of code repetition or huge complication. i.e. I would get worried if people always rely on this but we need custom warning implementations for different routines (like NEB, hypothetically speaking, where there is an extra n_images multiplier).

**Comment by samwaseda** [comment]
I would claim the problems requiring larger systems are also quite complex, so they tend to require also a relatively complex input structure. At least in my case it happens very often that I check the physics in detail, and forget about the numerical aspect in the end.

And as an example for a system of 10^6 atoms (which is not very large) with 1 ns (which is not very long), my quick estimation already gives me around 1 TB if we don't change `n_print` (assuming double is 8 byte in python just like in C++). Together with my claim above, I'm quite sure that the problem I'm talking about here is not something very special and can happen to many of us.

Indeed there are cases like NEB where we need extra care, but I wouldn't be worried too much, firstly because we don't have it (and anything else that would have the same problem) in the main pyiron version, secondly it's somewhat understandable that the check works only on each of the child jobs (at least that's probably what I'd expect if I was an outside user) and thirdly it changes at most one order of magnitude, which is large but not like in normal LAMMPS jobs where you're free to change orders of magnitude as you like (i.e. just by mistyping the number of steps you might end up killing all your running jobs).

This being said, I agree that we should be careful about the memory threshold. I'd support the idea of setting it in `.pyiron`, so that the user can change it if needed.

**Comment by niklassiemer** [comment]
The available RAM is per node, so would you issue a warning on the server object if the estimated RAM is in the order of nodes times RAM per node or/and if the requires RAM is 'gigantic'? 
At what point of the run do these calculations requiring to much RAM actually crash? In the beginning or after some extended calculations?
The hard part would be to estimate a sensible order of magnitude for the threshold which is valid for HPC as well as single computer usage...

**Comment by samwaseda** [comment]
Here I'm talking about disk space, but RAM is certainly also something we should look into.

**Comment by niklassiemer** [comment]
Ops, thanks for pointing this out!  
In this case, I am just fine with a warning if the expected output is bigger than a threshold which can be changed in `.pyiron`.

**Comment by niklassiemer** [comment]
What would we consider a good value for such a (default) threshold?

**Comment by samwaseda** [comment]
100 GB, 1 TB ?

**Comment by niklassiemer** [comment]
ok, this is an awful lot of data considering an personal computer, so I would rather go for the lower threshold and let more experienced/ HPC users extend this in the `.pyiron` config.

**Comment by liamhuber** [comment]
Ah, I had also understood it as a RAM threshold! If we're talking storage threshold then I guess we care about `len(structure) * n_ionic_steps / n_print`.

I agree with Niklas that a lower threshold is wise, especially since we're talking about (a) for a *single* calculation, and (b) it's only a warning anyway and won't stop anything. I would suggest 10GB estimated storage for a single run is already something the user should get pinged about.

**Comment by samwaseda** [comment]
Yeah sorry I shouldn't have said memory since a normal person would indeed understand RAM :D.

I'm also fine with 10 GB. What basically happens to me is that I get something which is by orders of magnitude too large. So whether it's 1 TB, 100 GB or 10 GB doesn't really matter.

**Comment by niklassiemer** [comment]
And you could set it to 100GB if you want to. On HPC systems with big structures and reasonable long trajectories 10GB might trigger a warning each run... 
I can have a look at the settings which parses the `.pyiron` to add a new flag there. However, you would need to implement the storage estimation and the warning based on the settings item.
