### ISSUE TITLE
job.get_neighbors() gives an error

### ISSUE THREAD

**Issue by jyang2009** [pyiron/pyiron_atomistics#885]
Hi all,

I'm getting the following error when running job.get_neighbors() 

~/Program/pyiron_atomistics/pyiron_atomistics/pyiron_atomistics/atomistics/job/atomistic.py in __getitem__(self, item)
    901                     cells=self._cells[snapshots],
    902                     structure=self[snapshots[0]],
--> 903                     indices=self._indices[snapshots],
    904                 )
    905             else:

TypeError: only integer scalar arrays can be converted to a scalar index

I tried it on several jobs but got the same error. Does anyone get the same thing? Thanks for your help in advance.

Best,
Jing

**Comment by mbruns91** [comment]
Can you maybe post as few lines as possible which reproduce this error? I just worked with `get_neighbors()` without any problem.
