### ISSUE TITLE
plot3d() does not work

### ISSUE THREAD

**Issue by jyang2009** [pyiron/pyiron_atomistics#890]
Dear all,

I think since some time today the structure.plot3d() method does not work any more on cmti001. The structure is not shown. It is probably a problem with the ngl library. 
Could you please check this? Thanks a lot. 

Here is a short code that could be used to test it:
pr = Project('Al')
structure = pr.create.structure.bulk('Al')
structure.plot3d()

Best,
Jing

**Comment by mbruns91** [comment]
This is already resolved. Restart your jupyterhub server and it should be fine again.
Also: Please ask cluster specific questions in the MPIE rocketchat.
