### ISSUE TITLE
Plot QHA Free energy-Volume-Temperature curves

### ISSUE THREAD

**Issue by usaikia** [pyiron/pyiron_atomistics#911]
Hi, I have some finished pyiron phonopy jobs. I run these jobs individually for different volumes of the same structure. Now I want to plot the QHA Free energy-Volume-Temperature curves with phonopy by using all these jobs. Is there any function in Pyiron to do it automatically?

**Comment by jan-janssen** [comment]
The QHA is covered in the virtual course: 
https://pyiron.org/phasediagram-workshop-2020/ThermodynamicProperties.html
the corresponding cells are: 
https://pyiron.org/phasediagram-workshop-2020/Exercise4.html#quasi-harmonic-approximation
Finally, the solution to the notebooks discussed in the tutorials is:
https://github.com/pyiron/phasediagram-workshop-tutors-2020/blob/main/Sol_4_Free_Energies.ipynb
The access to the last link might be restricted, still I guess the first two should be sufficient.

**Comment by pmrv** [comment]
The question here is more, what if I have already a finished Phonopy job and I don't want to re-run it (because it is expensive).

**Comment by jan-janssen** [comment]
> The question here is more, what if I have already a finished Phonopy job and I don't want to re-run it (because it is expensive).

I guess that depends on how the data is stored or the jobs are named. But basically it is nothing else than a for loop over the quasi-harmonic calculation at different volumes https://github.com/pyiron/pyiron_atomistics/blob/main/pyiron_atomistics/atomistics/master/quasi.py#L101 and storing the free_energy, entropy and cv.

**Comment by samwaseda** [comment]
To give a short answer to the original question: No.

I think the first thing is to refactor [this function](https://github.com/pyiron/pyiron_atomistics/blob/b096732c16dd19d4522ca57ea1ac10979736b765/pyiron_atomistics/atomistics/master/quasi.py#L138) and [the function that @jan-janssen posted](https://github.com/pyiron/pyiron_atomistics/blob/main/pyiron_atomistics/atomistics/master/quasi.py#L101). It's probably not very difficult to do. However, I don't think we can effectively keep using the current class in general (including the case that @usaikia raises). I'm working on the [new QHA class](https://github.com/pyiron/pyiron_contrib/pull/369) in `pyiron_contrib` for some time. From there, you can import the `Thermodynamics`-class and it will do the job automatically.

**Comment by usaikia** [comment]
Thanks a lot @jan-janssen and @samwaseda for your answers. It looks like I can use the solution suggested by @jan-janssen or by @samwaseda both will solve my problem.
