### ISSUE TITLE
NumPy version 1.24.0 pr.create_job not working

### ISSUE THREAD

**Issue by co-dani-f** [pyiron/pyiron_atomistics#915]
### Summary

NumPy version 1.24.0 removed np.float and np.int, AttributeError leads to "pr.create_job" not working.

### pyiron Version and Platform

Installation done following instructions on website.
https://pyiron.readthedocs.io/en/latest/source/installation.html
Configuration was not changed. Versions:
pyiron 0.4.7
pyiron-data 0.0.20
pyiron_atomistics 0.2.58
pyiron_base 0.5.30

### Expected Behavior

pr.create_job(job_type=pr.job_type.Lammps, job_name='Al_T800K') working properly.
(see below)

### Actual Behavior and Steps to Reproduce

After fresh install.
Following the steps under
https://pyiron.readthedocs.io/en/latest/source/notebooks/first_steps.html#Perform-a-LAMMPS-MD-simulation
I encountered a deprecation warning and a bug.
First of all, pyiron states that "pr.create_ase_bulk" is deprecated.
I guess one should use "pr.create.structure.bulk".

Secondly, "job = pr.create_job(job_type=pr.job_type.Lammps, job_name='Al_T800K')" is not working.
An AttributeError popped up, stating at the very bottom: "AttributeError: module 'numpy' has no attribute 'float'".

Downgrading the NumPy-version to the latest before 1.24.0, which is 1.23.5, solved the issue
(conda install -c conda-forge numpy=1.23.5).
The reason being that NumPy removed np.float (and np.int) in version 1.24.0.

Following the path of the error, which is:
"...\anaconda3\envs\testMD\lib\site-packages\pyiron_atomistics\lammps\units.py:160"
one gets to the file units.py.
Copying this file to windows subsystem for linux and using "grep np.float units.py" in a directory only containing units.py to find other instances, one gets:
"dtype_dict[v] = np.float"
which is the instance python reports in line 160.
Optional fix without downgrading NumPy to version 1.23.5:
dtype_dict[v] = float
Afterwards a new error appeared 2 lines above, "AttributeError: module 'numpy' has no attribute 'int'".
Optional fix without downgrading NumPy to version 1.23.5:
dtype_dict[v] = int

**Comment by jan-janssen** [comment]
@co-dani-f Thank you for opening this issue. We are aware that there is currently an issue with the recent update of numpy to version 1.24.0 . We are working on it in https://github.com/pyiron/pyiron_atomistics/pull/904 still given the end of the year coming up, we might not be able to fix it as quick as we would like to.

**Comment by pmrv** [comment]
We are on `numpy==1.24.2`, so I assume we fixed it.
