### ISSUE TITLE
Reading POSCAR or CONTCAR files with selective dynamics inverts them

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron_atomistics#932]
When using pr.create.structure.read("POSCAR") on VASP CONTCAR or POSCAR format selective dynamic tags are inversed.
I did not trace it back to its origin yet and did not check for other codes, so I don't know whether this is a bug inherited from ase,
a matter of different definitions or some messed up stuff on pyiron/ase conversion.

**Comment by ligerzero-ai** [comment]
I touched this a while back so I will take a look at it tonight.

**Comment by ligerzero-ai** [comment]
Hi, I need some time over the weekend to fix this - but the current workaround suggested by me is to do: 
```
from pyiron_atomistics.atomistics.structure.atoms import pyiron_to_pymatgen, pymatgen_to_pyiron
from pymatgen.core import Structure

structure = pymatgen_to_pyiron(Structure.from_file("POSCAR"))
```
I'm fairly sure that the above will be safe (as I have tests specifically checking the sel dyn tags implemented)

**Comment by ligerzero-ai** [comment]
I checked ASE, there is no problem on their `ase.io.read` function so it must be on our end.

**Comment by ligerzero-ai** [comment]
Actually, I stand corrected. This is inherited from ASE. 

MWE:
```
from pyiron_atomistics.atomistics.structure.atoms import pyiron_to_pymatgen, pymatgen_to_pyiron
from pymatgen.core import Structure
from pyiron import Project

pr = Project("asdf")
pi_atoms = pr.create.structure.bulk("Fe") * [2, 2, 1]
struct = pyiron_to_pymatgen(pi_atoms)
struct.add_site_property("selective_dynamics", values=[[False, False, False], [False, False, True], [False, False, False], [True, True, False]])
struct.to(fmt="poscar", filename="test_sel_dyn.vasp")
read_struct = pr.create.structure.read("test_sel_dyn.vasp")
read_struct
```
yields:
```
Fe: [0. 0. 0.]
Fe: [ 1.435 -1.435  1.435]
Fe: [-1.435  1.435  1.435]
Fe: [0.   0.   2.87]
tags: 
    selective_dynamics: [[False, False, False] [True, True, False] [False, False, False] [False, False, True]]
pbc: [ True  True  True]
cell: 
Cell([[-2.87, 2.87, 2.87], [2.87, -2.87, 2.87], [1.435, 1.435, -1.435]])
```

Honestly, between the very dangerous bugs/bombs lurking in the `get_chemical_*`/`get_species` interface (which is a toxic wasteland that nobody wants to touch despite the possible multi-million-hour cpu wastage potential), unserialisable Atoms objects, and these kinds of bugs, I'm of half a mind to suggesting a hard switch to using pymatgen `Structure` objects as the base structure objects for pyiron. I have not experienced any of these errors with prior work with them, compared to the buggy (in comparison) mess with ASE atoms objects. Is there any objection to this besides "this is what we've always used/it is what I'm used to"? I believe this will significantly reduce the amount of work on our part to fix/patch in workarounds to what I view as unnecessary problems and labour hours and creation of code that we have to maintain and understand.

People would still be free to use the ASE atoms by themselves, but I view it to be a worse default compared to pymatgen Structure objects as atomic structure object representations.

**Comment by ligerzero-ai** [comment]
Should be fixed by #934, reopen if you still have issues

**Comment by jan-janssen** [comment]
I just get into this and remember there are two different conventions for selective dynamics. In the VASP manual it states `This allows to provide extra flags for each atom signaling whether the respective coordinate(s) of this atom will be allowed to change during the ionic relaxation.` Here `True` means the atom can move while `False` means the atom is fixed. In contrast in ASE as well as in LAMMPS atoms are fixed to their positions. In this case `True` means this atom is fixed and `False` means this atom is free to move. So we have to be very careful here that this remains consistent. Do we follow the VASP or the ASE notation?

**Comment by ligerzero-ai** [comment]
the pymatgen reader cannot read lammps output. So the current fix handles it implicitly, as it switches to ASE if the pymatgen reader fails. I can add this explicitly in a docstring if needed, however.

**Comment by jan-janssen** [comment]
I mean, does it work when you read a `POSCAR` file and then write it again with `pyiron` does it return the same file? At least in terms of which atoms move and which ones do not?

**Comment by ligerzero-ai** [comment]
I will check this carefully tomorrow.

But I cannot see why not, as I have used this code:

```
from pyiron_atomistics.atomistics.structure.atoms import pyiron_to_pymatgen, pymatgen_to_pyiron
from pymatgen.core import Structure

structure = pymatgen_to_pyiron(Structure.from_file("POSCAR"))
```
in my own work and it does fix the atoms properly on write to disk. So I'm 95% sure that it shouldn't do anything weird.

**Comment by jan-janssen** [comment]
The issues is that ASE has the opposite naming scheme for selective dynamics compared to VASP.

**Comment by ligerzero-ai** [comment]
yes, and with this new fix, we default to pymatgen. The bug still exists on the ase reader, and it causes inversion on not all tags, so it is definitely bugged, not just a matter of naming convention.

In the MWE I set [False, False, False], [False, False, True], [False, False, False], [True, True, False]

and the generated structure from ase.io.read yields:
[False, False, False] [True, True, False] [False, False, False] [False, False, True]

So it is selectively inverting some tags but not others. So it is absolutely wrong, just a matter of how much.

**Comment by ligerzero-ai** [comment]
So I guess what you are concerned about is practically, what is happening on the `write` step. The error is occurring solely on the `read()` function on ASE. I have this extensively tested this in production runs and there is no issue on the write step, only on the `read()` step.  

See below on something that I copied from a production run POSCAR in pyiron where I intentionally fixed the "x, y" coords and only allow "z" to relax.

```
Poscar file generated with pyiron
1.0
2.487601656214275 0.000000000000000 0.000000000000000
0.000000000000000 10.256644383032885 0.000000000000000
0.000000000000000 0.000000000000000 58.020342363691718
Ni
66
Selective dynamics
Direct
0.500006953675637 0.791019657868337 0.266828270023116 F F T
0.000005359910580 0.991594114869312 0.260514168444894 F F T
0.000009939064171 0.587606423394950 0.273702156946720 F F T
0.500008836189614 0.382400643173480 0.280709515380068 F F T
0.000008243582393 0.177401719063960 0.286860474427311 F F T
0.500005449014686 0.971883929378964 0.295794636271414 F F T
0.000008336668919 0.763944176272260 0.303118522471017 F F T
0.500006229119788 0.557826025129059 0.309891794311399 F F T
0.000008868604246 0.351588719485312 0.316910620144783 F F T
0.500010384286816 0.146946946950368 0.324367261353646 F F T
0.000003558074527 0.940598051498792 0.332388490617072 F F T
0.499999000376001 0.734807132690349 0.339666692093109 F F T
0.999999394324504 0.529241409712831 0.346430621641227 F F T
0.500004606475843 0.322906344214489 0.353664523323882 F F T
0.999995951259167 0.116832434727610 0.361350174453079 F F T
0.499996095206570 0.910652681546863 0.369349263199492 F F T
0.999985018997816 0.705458538305897 0.376517412614020 F F T
0.499977743426358 0.499897004065036 0.382826683897058 F F T
0.999994044820678 0.292836493350529 0.390523937657371 F F T
0.499997075371047 0.086899881829753 0.398285269958777 F F T
0.999985015089152 0.881035559887888 0.406464604201467 F F T
0.499955728360934 0.676632410334570 0.413484449279624 F F T
0.999953060888926 0.470840110527896 0.418857961899762 F F T
0.499993883111600 0.262319351343681 0.427481876545424 F F T
0.999989261349655 0.057565323758532 0.435243423473039 F F T
0.499958205983167 0.852253249001819 0.443989704335756 F F T
0.999904898570471 0.648685663048586 0.450485553169315 F F T
0.499908391085648 0.442368670165751 0.454316629245478 F F T
0.999990081079091 0.231867661840899 0.465161277119095 F F T
0.499985006182889 0.030103072865443 0.471998214179789 F F T
0.999889383707290 0.825280296169943 0.482606775667000 F F T
0.499864225726070 0.621730350202276 0.487006334996182 F F T
0.999853624117998 0.417643903469066 0.488541373565732 F F T
0.500009258808913 0.225007953750339 0.507252955965477 F F T
0.000015356242611 0.015862305653771 0.507461874533130 F F T
0.100181497966345 0.616270305906317 0.526218386523753 F F T
0.600145675974999 0.820557093658842 0.527964151691809 F F T
0.100094540670451 0.024405289918542 0.532238110483407 F F T
0.600049698172638 0.228942418776829 0.542903455507369 F F T
0.100050121315396 0.430759767681470 0.549570109104613 F F T
0.600130352980398 0.641858070734170 0.560425927516148 F F T
0.100122036911980 0.848297922737143 0.564483520170262 F F T
0.600078009220042 0.051643434349870 0.570983477275605 F F T
0.100051953907719 0.256961777974514 0.579610269167996 F F T
0.600049110641018 0.461931313626281 0.587234725124713 F F T
0.100092593452295 0.670736746028295 0.595875060108754 F F T
0.600078446428660 0.876612358180171 0.601565586677486 F F T
0.100062522555361 0.080803284018290 0.608613241686987 F F T
0.600043097210379 0.286382231342765 0.616473757581865 F F T
0.100053758436893 0.492594476334386 0.624111710066534 F F T
0.600062219477488 0.699843974059131 0.631912424104141 F F T
0.100072618214692 0.905573103073563 0.638663836224237 F F T
0.600066366307813 0.110688846469096 0.645852703037947 F F T
0.100054467894685 0.316469402185449 0.653273613601789 F F T
0.600058502209458 0.522492877855048 0.660838351548603 F F T
0.100059258010876 0.729253303418590 0.668359799714241 F F T
0.600058155036672 0.935258649980324 0.675721242860927 F F T
0.100064164178603 0.139514817784745 0.682810501967974 F F T
0.600055104084121 0.345561016637475 0.689999726012498 F F T
0.100056486958027 0.552052488327325 0.697334779771125 F F T
0.600044604840007 0.760507881148989 0.704735327006837 F F T
0.100063219566927 0.965846319458992 0.713226159747430 F F T
0.600053827004101 0.170673214592535 0.719103703965472 F F T
0.100041162477091 0.375595402158834 0.726306702595603 F F T
0.600033775613241 0.579164862376216 0.733591711512892 F F T
0.100031574342224 0.780051362224066 0.739944430235223 F F T
```

As you can see, there is no error on the write. It is just something weird that happens solely on the `read()`

**Comment by jan-janssen** [comment]
I guess it is still a good test case we could add to our test. Read an ASE file and then write it again to make sure nothing changed.

**Comment by ligerzero-ai** [comment]
oh, I just realised that we have our own custom writer for POSCARs, so you're right. the write function in ASE might actually have this weird behaviour too. lol. I'll check if two wrongs somehow make a right in the ase `write()` tomorrow. I find it amusing that I couldn't find any mentions of this bug on ASE's gitlab. I would have imagined that something as widely used as selective dynamics would have triggered alarm bells earlier, but I guess I'm overestimating the amount of people that use ase for `io`, or the amount of people that use selective dynamics with ase.
