### ISSUE TITLE
Restarting Vasp MD-Jobs

### ISSUE THREAD

**Issue by fldei101** [pyiron/pyiron_atomistics#939]
**Summary**

Hi, is there a way to restart a Vasp-MD-Job properly?
if I try job_next = job_old.restart() it creates a POSCAR which contains the positions of the last job but the velocities which are written in the CONTCAR file are not there. I also tried job_next.restart_file_list.append(job_old.working_directory + "/CONTCAR") but then it only copies the CONTCAR in the working directory without overwriting the POSCAR. Is there any command or flag that I am missing or is this feature available?

**pyiron Version and Platform**

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by ligerzero-ai** [comment]
job.restart_file_dict["CONTCAR"] = "POSCAR"

as per:

https://github.com/pyiron/pyiron_atomistics/issues/570

It is inelegant, and I'll put it on the list of things to fix/document better.
