### ISSUE TITLE
Pip check failing due to pyiron_base vs mendeleev

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_atomistics#958]
Our pip checks fail:

```
mendeleev 0.12.1 has requirement SQLAlchemy<2.0.0,>=1.4.0, but you have sqlalchemy 2.0.1.
```

Because:
- pyiron_base/.ci_support/environment.yml: `- sqlalchemy =2.0.3`
- [mendeleev/pyproject.toml](https://github.com/lmmentel/mendeleev/blob/master/pyproject.toml): `SQLAlchemy = "^1.4.0"` [(carat means don't allow changes to the leftmost non-zero digit)](https://stackoverflow.com/questions/54720072/dependency-version-syntax-for-python-poetry)

This is also causing pip-check failures in all our downstream repos that depend on atomistics. Mybinder envs are still compiling so this is not an earth-shattering problem to be having, but it would be good to fix. I'm not going to get to it this afternoon, I just wanted to document exactly what's happening.

Unfortunately, we seem to be up-to-date with [the latest version of mendeleev](https://anaconda.org/conda-forge/mendeleev), so we'll either need to convince them to bump their dep, or pin pyiron_base's dep lower.

**Comment by jan-janssen** [comment]
Yes, the short answer is there is an issue with pandas requiring `sqlalchemy=1.4.6` but there were no restrictions, so we currently primarily hope the update pandas soon https://github.com/pyiron/pyiron_atomistics/pull/949

**Comment by liamhuber** [comment]
So this is actually becoming a bit of an issue for me. For packages that depend on atomistics, if I _don't_ pin the atomistics version, conda pushes me back down to atomistics 0.2.34 (and corresponding base). If I _do_ pin the atomistics version, MyBinder complains that the environment is unresolvable and I can't open any notebooks on binder.

I know it's more or less out of our control, I just wanted to clarify my earlier comment that "Mybinder envs are still compiling"... I guess I was previously just getting atomistics downgraded and it was a non-issue...

**Comment by liamhuber** [comment]
Pip check works after Jan's [downgrade of the SQLAlchemy dependency](https://github.com/pyiron/pyiron_base/pull/1043). A long term solution still waits on the upstream libraries, but we're not getting test failure any more, which is good enough for me.
