### ISSUE TITLE
Do we need `SparseList`?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#980]
We have been using our own tags for years now, but I see the following problems:

- A lot of extra lines of code which have to be maintained
- It's not numpy, and therefore either does not support the mathematical operations or repeated in our own class
- It is actually not even stored as sparse data (as shown [here](https://github.com/pyiron/pyiron_atomistics/issues/979))
- Not clear whether we gain a lot of space by using sparse list
  - For example, if we set `structure.selective_dynamics[:] = [True, True, False]`, then it becomes a dictionary containing every atom, which makes the data larger
  - There must be a more intelligent way to compress data.

**Comment by samwaseda** [comment]
@jan-janssen @liamhuber @pmrv

**Comment by pmrv** [comment]
Yeah, I'm not attached to it at all.  It's actually a performance bottleneck when `repeat`ing structures as well (#734).  I'm ok with axing it making something better.  Preferably something that integrates better with ASE tag system as well.

**Comment by liamhuber** [comment]
I don't think I've ever used it, so it can die and I wouldn't even notice.

**Comment by jan-janssen** [comment]
I am in progress of removing the pyiron specific atoms class and replace it with pure ASE atoms in https://github.com/pyiron/structuretoolkit there are still a couple of open issues but I guess it can be done.

**Comment by samwaseda** [comment]
I already started working on it, but I'm gonna in principle remove it.
