### ISSUE TITLE
Ideas for `pr.create.potential`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#997]
First: Anything currently available will stay unchanged -> ✔️ backward compatibility

Currently pyiron is either limited to the existing potentials, or the user has to look up how the potential is read by LAMMPS, if they want to overlay multiple potentials. Also, I find it annoying to have to define a job and a structure to be able to look up available EAM potentials. I want to introduce `pr.create.potential` to solve these issues.

Case I: Simple EAM Al potential:

```python
job = pr.create.job.Lammps(“eam_Al”)
job.structure = pr.create.structure.bulk(“Al”)
eam = pr.create.potential.effective.EAM(“Al”)
eam.set_potential(eam.list_potentials()[0])
job.potential = eam
```

Case II: Morse potential:

```python
job = pr.create.job.Lammps(“morse_Al”)
job.structure = pr.create.structure.bulk(“Al”)
morse = pr.create.potential.effective.Morse(“Al”)
morse.set_potential(alpha=0.1, D_0=10, r_0=3) # Following LAMMPS convention; should be explained in DocStr
job.potential = morse
```

Case III: Overlay EAM and Morse

```python
job = pr.create.job.Lammps(“EAM_morse_Al_C”)
job.structure = pr.create.structure.bulk(“Al”, cubic=True)
job.structure[1] = “C”
eam = pr.create.potential.effective.EAM(“Al”)
eam.set_potential(eam.list_potentials()[0])
morse_Al_C = pr.create.potential.effective.Morse(“Al”, “C”)
morse_Al_C.set_potential(alpha=0.1, D_0=10, r_0=3)
morse_C = pr.create.potential.effective.Morse(“C”)
morse_C.set_potential(alpha=0.24, D_0=4, r_0=1.1)
job.potential = eam * morse_C * morse_Al_C # pair_style hybrid ?
job.potential = eam + morse_C + morse_Al_C # pair_style  hybrid/overlay ?
job.potential = 0.5 * eam + 0.3 * morse_Al_C + 0.5 * morse_C # pair_style  hybrid/scale ?
job.potential = eam + morse_Al_C # missing C-C interactions -> error
```

And I guess for DFT it should look more or less the same:

```python
job = pr.create.job.Sphinx(“dft_Al”)
job.structure = pr.create.structure.bulk(“Al”)
pseudo = pr.create.potential.pseudo(“Al”)
pseudo.set_potential(“GW”)
job.potential = pseudo
```

But to be honest I haven’t really thought much about DFT. Most of the work has already been done by @Ahmed-Aslam a few years ago, so I will just have to implement it in the new factory class. Maybe we can also try to use the EAM class provided by ASE. Let me know what you think.

**Comment by liamhuber** [comment]
I really like it. I previously extracted something similar for the Lammps potentials ([`from pyiron_atomistics.lammps.potential import list_potentials; list_potentials(some_struct)`](https://github.com/pyiron/pyiron_atomistics/commit/f38741ade53e2db904b20e2c0b0987baa5321e78)) because I wanted something simpler that creating a damned job every time.

This is a much more powerful and accessible version of that same idea, so I am strongly in support.

I would only add some syntactic sugar, e.g.

```python
eam = pr.create.potential.effective.EAM(“Al”)
eam.set_potential(eam.list_potentials()[n])
job.potential = eam
```

should be equivalent to

```python
job.potential = pr.create.potential.effective.EAM(“Al”, choice=n)
```

and

```python
morse_Al_C = pr.create.potential.effective.Morse(“Al”, “C”)
morse_Al_C.set_potential(alpha=0.1, D_0=10, r_0=3)
```

to 

```python
morse_Al_C = pr.create.potential.effective.Morse(
  “Al”, “C”, alpha=0.1, D_0=10, r_0=3
)
```

**Comment by pmrv** [comment]
`Project` also has `somethingsometing_emperical_potentials` to search for potentials without creating the job.  I agree that it'd be nice to have syntax for hybrid potential styles.

**Comment by samwaseda** [comment]
> I would only add some syntactic sugar, e.g.
> 
> ```python
> eam = pr.create.potential.effective.EAM(“Al”)
> eam.set_potential(eam.list_potentials()[n])
> job.potential = eam
> ```
> 
> should be equivalent to
> 
> ```python
> job.potential = pr.create.potential.effective.EAM(“Al”, choice=n)
> ```

Hmmm, I see where the idea comes from, but I’m not really sure if we should support something like `n` as an input. My concern is that while `eam.set_potential(eam.list_potentials()[n])` makes the user understand the meaning of `n` (or rather lack of meaning, because it shows that it takes the `n`-th item from some list), `choice = n` makes me feel `n` has a special meaning. So I might prefer something like `pr.create.potential.effective.EAM(“Al”, name=“potential_name”)`. And not setting any name would give the first entry with a warning, which is the current behaviour.

This being said I don’t have a very strong feeling, so if you prefer `choice = n`, I’m also ok with that.

**Comment by liamhuber** [comment]
> This being said I don’t have a very strong feeling, so if you prefer `choice = n`, I’m also ok with that.

I mean, I'm just using `n` as a stand-in for the pseudocode to represent some integer. The relevant bit is `choice: int`. I don't have strong feelings that the kwarg should be called `choice` but I don't think it's a terrible name. 

My main thrust was to tighten things up by calling `set_potential` at instantiation and moving all the `set_potential` args and kwargs into the `__init__`. 

I am very open to a kwarg `name: str`, but personally I can _never_ remember what we call the potentials, so I would allow `name: str` XOR `choice: int` as input.

**Comment by pmrv** [comment]
I'd somewhat prefer `name: str`, because the order of potentials is not guaranteed to be stable.

**Comment by niklassiemer** [comment]
I would like to support something like
```
eam = pr.create.potential.effective.EAM(“Al”)
```
to accept a structure
```
eam = pr.create.potential.effective.EAM(some_structure)
```

**Comment by liamhuber** [comment]
> I'd somewhat prefer `name: str`, because the order of potentials is not guaranteed to be stable.

For me, providing an integer is not so much about being able to select a particular one, as it is about being able to iterate over some (usually entirely or mostly arbitrary) subset.

**Comment by pmrv** [comment]
I think that's more easily solved with `inspect_emperical_potentials`, like so

```python
for name in pr.inspect_emperical_potentials().find('Cu').Name:
   eam = pr.create.potential.effective.EAM(“Al”, name=name)
```

Or just making it return a list of potential objects in the first place rather then the dataframe it returns now.

**Comment by liamhuber** [comment]
> Or just making it return a list of potential objects in the first place rather then the dataframe it returns now.

This is also fine for me. Critical for me is that the syntax allows:
- Creating and assigning the potential in a single (relatively brief) line
- Changing the selected potential without knowing or caring what its name is (e.g. (probably i.e.) with an index)

Any solution that fulfills that gets the green light from me.
